Repository DataDog/dd-trace-java, pull requests merged in 2018-12, with the labels that each got.

#608 Update misc versions.
  dd-java-agent-ittests/dd-java-agent-ittests.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
  dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
  dd-java-agent/instrumentation/mongo-3.1/mongo-3.1.gradle
  dd-trace-java.gradle
  dd-trace-ot/dd-trace-ot.gradle
  gradle/dependencies.gradle
  gradle/java.gradle
Labels: core

#621 Fix wildfly startup by injecting context classes into bootstrap package
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
  dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
Labels: bug

#628 Do not set the sampler rate for RateByServiceSampler
  dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/RateByServiceSamplerTest.groovy
Labels: bug

#632 remove errorprone
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
  dd-trace-java.gradle
  gradle/java.gradle
Labels: bug

#634 Properly capture callable statement queries
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
Labels: bug, integrations
