Repository DataDog/dd-trace-java, pull requests merged in 2018-09, with the labels that each got.

#464 Couchbase 2.0+ instrumentation
  .circleci/config.yml
  dd-java-agent/instrumentation/couchbase-2.0/couchbase-2.0.gradle
  dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseBucketInstrumentation.java
  dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClusterInstrumentation.java
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseConfig.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringRepositoryTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/Doc.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/DocRepository.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
  dd-java-agent/instrumentation/elasticsearch-rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Config.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
  dd-java-agent/instrumentation/spymemcached-2.12/spymemcached-2.12.gradle
  dd-java-agent/testing/testing.gradle
  gradle/java.gradle
  settings.gradle
Labels: integrations

#478 Stop sending params with AWS traces
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/SpanDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/aws-java-sdk-1.11.106/src/main/java/datadog/trace/instrumentation/aws/v106/SpanDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.106/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
Labels: bug, integrations

#495 Add span.type and remove bucket name from resource.name for Couchbase
  dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseBucketInstrumentation.java
  dd-java-agent/instrumentation/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClusterInstrumentation.java
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringRepositoryTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/DDSpanTypes.java
Labels: integrations

#500 Add slashes if missing from annotation values
  dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsInstrumentation.java
  dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
Labels: bug, integrations

#496 Refactor DDTraceConfig to a Config we can use globally
  dd-trace-api/dd-trace-api.gradle
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/ServletContextDecorator.java
  dd-trace-ot/src/main/java/datadog/opentracing/resolver/DDTracerResolver.java
  dd-trace-ot/src/main/java/datadog/trace/common/DDTraceConfig.java
  dd-trace-ot/src/main/java/datadog/trace/common/sampling/Sampler.java
  dd-trace-ot/src/main/java/datadog/trace/common/util/Config.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/Writer.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/resolver/DDTracerResolverTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/resolver/TracerResolverTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTraceConfigTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
  dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
Labels: breaking-change, core

#502 Better error handling for older JDBC drivers
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
Labels: bug, integrations

#501 Upgrade gradle to 4.10.1
  dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle
  dd-java-agent/instrumentation/play-2.4/play-2.4.gradle
  dd-trace-java.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dev/tooling
