Repository DataDog/dd-trace-java, pull requests merged in 2018-04, with the labels that each got.

#280 Add the errorprone compiler.
  .circleci/config.yml
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-trace-api/src/main/java/datadog/trace/api/DDTraceApiInfo.java
  dd-trace-java.gradle
  dd-trace-ot/src/main/java/datadog/opentracing/DDTraceOTInfo.java
  gradle/java.gradle
Labels: dev/tooling

#281 Use CallDepthThreadLocalMap in sql Connection init
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/CallDepthThreadLocalMap.java
  dd-java-agent/instrumentation/classloaders/src/main/java/datadog/trace/instrumentation/classloaders/CallDepthThreadLocalMap.java
  dd-java-agent/instrumentation/classloaders/src/main/java/datadog/trace/instrumentation/classloaders/ClassLoaderInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
Labels: bug

#283 Add startTime and Duration methods to MutableSpan interface
  dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
Labels: core, enhancement

#279 Add sampling for server mem usage after startup
  dd-java-agent/benchmark-integration/run-perf-test.sh
Labels: dev/testing

#277 Play 2.4-2.6 Instrumentation
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/instrumentation/play-2.4/play-2.4.gradle
  dd-java-agent/instrumentation/play-2.4/play-2.6-testing/play-2.6-testing.gradle
  dd-java-agent/instrumentation/play-2.4/play-2.6-testing/src/test/groovy/Play26Test.groovy
  dd-java-agent/instrumentation/play-2.4/play-2.6-testing/src/test/scala/Play26TestUtils.scala
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java
  dd-java-agent/instrumentation/play-2.4/src/test/groovy/Play24Test.groovy
  dd-java-agent/instrumentation/play-2.4/src/test/scala/Play24TestUtils.scala
  dd-java-agent/testing/src/main/java/datadog/trace/agent/test/TestUtils.java
  gradle/test-with-scala.gradle
  settings.gradle
Labels: integrations

#284 Fix CI Flickers
  .circleci/config.yml
Labels: bug, dev/testing

#285 Build with Java 8, but run tests with other JDKs
  .circleci/collect_artifacts.sh
  .circleci/config.yml
  .gitignore
  dd-java-agent-ittests/dd-java-agent-ittests.gradle
  dd-java-agent/instrumentation/aws-sdk/aws-sdk.gradle
  dd-java-agent/instrumentation/datastax-cassandra-3.2/datastax-cassandra-3.2.gradle
  dd-java-agent/instrumentation/jax-rs-client/jax-rs-client.gradle
  dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle
  dd-java-agent/instrumentation/play-2.4/play-2.4.gradle
  dd-java-agent/instrumentation/play-2.4/play-2.6-testing/play-2.6-testing.gradle
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java
  dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServletTest.groovy
  dd-java-agent/instrumentation/spring-web/src/test/java/test/TestForm.java
  dd-trace-java.gradle
  dd-trace-ot/dd-trace-ot.gradle
  gradle/checkstyle.gradle
  gradle/java.gradle
  settings.gradle
Labels: dev/tooling

#282 Toggleable Async Propgation on the trace context
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/instrumentation/java-concurrent/akka-testing/src/main/scala/AkkaActors.scala
  dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle
  dd-java-agent/instrumentation/java-concurrent/scala-testing/scala-testing.gradle
  dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/groovy/ScalaInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/scala/ScalaConcurrentTests.scala
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/java/AsyncChild.java
  dd-java-agent/instrumentation/play-2.4/.gitignore
  dd-java-agent/instrumentation/play-2.4/play-2.6-testing/src/test/groovy/Play26Test.groovy
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play/PlayInstrumentation.java
  dd-java-agent/instrumentation/play-2.4/src/test/groovy/Play24Test.groovy
  dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContextualScopeManager.java
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/SimpleScope.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
Labels: integrations

#290 Handle spans registered after trace is written
  dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy
Labels: bug

#254 Spark Java Framework Instrumentation
  buildSrc/src/main/groovy/VersionScanPlugin.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
  dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HandlerInstrumentation.java
  dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
  dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServletTest.groovy
  dd-java-agent/instrumentation/sparkjava-2.4/sparkjava-2.4.gradle
  dd-java-agent/instrumentation/sparkjava-2.4/src/main/java/datadog/trace/instrumentation/sparkjava/RoutesInstrumentation.java
  dd-java-agent/instrumentation/sparkjava-2.4/src/test/groovy/SparkJavaBasedTest.groovy
  dd-java-agent/instrumentation/sparkjava-2.4/src/test/java/TestSparkJavaApplication.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
  settings.gradle
Labels: community, integrations

#294 Inject jax InjectAdapter helper class.
  dd-java-agent/instrumentation/jax-rs-client/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsClientInstrumentation.java
Labels: bug

#296 Use hardcoded operation names for integrations
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/httpclient/ApacheHttpClientTest.groovy
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/apache-httpclient-4.3/src/main/java/datadog/trace/instrumentation/apachehttpclient/DDTracingClientExec.java
  dd-java-agent/instrumentation/aws-sdk/src/main/java/datadog/trace/instrumentation/aws/TracingRequestHandler.java
  dd-java-agent/instrumentation/aws-sdk/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-3.2/datastax-cassandra-3.2.gradle
  dd-java-agent/instrumentation/datastax-cassandra-3.2/src/main/java/datadog/trace/instrumentation/datastax/cassandra/CassandraClientInstrumentation.java
  dd-java-agent/instrumentation/datastax-cassandra-3.2/src/main/java/datadog/trace/instrumentation/datastax/cassandra/TracingSession.java
  dd-java-agent/instrumentation/datastax-cassandra-3.2/src/test/groovy/CassandraClientTest.groovy
  dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
  dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HandlerInstrumentation.java
  dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HttpServletRequestExtractAdapter.java
  dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/OkHttp3Instrumentation.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/OkHttpClientSpanDecorator.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/RequestBuilderInjectAdapter.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TagWrapper.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracedCallable.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracedExecutor.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracedExecutorService.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracedRunnable.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracingCallFactory.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracingInterceptor.java
  dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
  dd-java-agent/instrumentation/servlet-2/servlet-2.gradle
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/FilterChain2Instrumentation.java
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/HttpServlet2Instrumentation.java
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/HttpServletRequestExtractAdapter.java
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/ServletFilterSpanDecorator.java
  dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/FilterChain3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServletRequestExtractAdapter.java
  examples/rest-spark/rest-spark.gradle
Labels: breaking-change, integrations

#298 Remove timeouts.
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/httpclient/ApacheHttpClientTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/jdbc/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/aws-sdk/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-3.2/src/test/groovy/CassandraClientTest.groovy
  dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
  dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JerseyTest.groovy
  dd-java-agent/instrumentation/jax-rs-client/src/test/groovy/JaxRsClientTest.groovy
  dd-java-agent/instrumentation/jboss-classloading/src/test/groovy/JBossClassloadingTest.groovy
  dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
  dd-java-agent/instrumentation/jms-1/src/test/groovy/JMS1Test.groovy
  dd-java-agent/instrumentation/jms-2/src/test/groovy/JMS2Test.groovy
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
  dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
  dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
  dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy
  dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServletTest.groovy
  dd-java-agent/instrumentation/sparkjava-2.4/src/test/groovy/SparkJavaBasedTest.groovy
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HTTPCodecTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDSpanContextTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTraceConfigTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/RateByServiceSamplerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/WriterQueueTest.groovy
Labels: dev/testing

#293 Upgrade Byte-buddy to 1.8.8
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java
  dd-java-agent/benchmark/out/jmh/resources/dd-trace.yaml
  dd-java-agent/dd-java-agent.gradle
  examples/dropwizard-mongo-client/dropwizard-mongo-client.gradle
  examples/dropwizard-mongo-client/gradle/wrapper/gradle-wrapper.jar
  examples/dropwizard-mongo-client/gradle/wrapper/gradle-wrapper.properties
  examples/dropwizard-mongo-client/out/production/resources/configuration.yaml
  examples/rest-spark/gradle/wrapper/gradle-wrapper.jar
  examples/rest-spark/gradle/wrapper/gradle-wrapper.properties
  examples/rest-spark/out/production/resources/configuration.yaml
  examples/rest-spark/rest-spark.gradle
  examples/spring-boot-jdbc-redis/gradle/wrapper/gradle-wrapper.jar
  examples/spring-boot-jdbc-redis/gradle/wrapper/gradle-wrapper.properties
  gradle/dependencies.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: core
