Repository DataDog/dd-trace-java, pull requests merged in 2018-02, with the labels that each got.

#224 Add exception for version segments in URLs
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/URLAsResourceName.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy
Labels: core

#225 Agent Bootstrapping
  dd-java-agent-ittests/dd-java-agent-ittests.gradle
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/TestLoggerRewrite.groovy
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/ShadowPackageRenamingTest.java
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/agent/PatchLogger.java
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDAdvice.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDJavaAgentInfo.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/BadAdvice.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperClass.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/apache-httpclient-4.3/apache-httpclient-4.3.gradle
  dd-java-agent/instrumentation/aws-sdk/aws-sdk.gradle
  dd-java-agent/instrumentation/datastax-cassandra-3.2/datastax-cassandra-3.2.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jms-1/jms-1.gradle
  dd-java-agent/instrumentation/jms-2/jms-2.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
  dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
  dd-java-agent/instrumentation/mongo-3.1/mongo-3.1.gradle
  dd-java-agent/instrumentation/mongo-async-3.3/mongo-async-3.3.gradle
  dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle
  dd-java-agent/instrumentation/servlet-2/servlet-2.gradle
  dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
  dd-java-agent/instrumentation/spring-web/spring-web.gradle
  dd-java-agent/instrumentation/trace-annotation/trace-annotation.gradle
  dd-java-agent/src/main/java/datadog/trace/agent/DDJavaAgentInfo.java
  dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
  dd-java-agent/testing/testing.gradle
  dd-trace-ot/dd-trace-ot.gradle
  settings.gradle
Labels: enhancement

#227 Add instrumentation for spring error handling
  dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServletTest.groovy
  dd-java-agent/instrumentation/spring-web/spring-web.gradle
  dd-java-agent/instrumentation/spring-web/src/main/java/datadog/trace/instrumentation/springweb/SpringWebInstrumentation.java
  dd-java-agent/instrumentation/spring-web/src/test/groovy/SpringBootBasedTest.groovy
  dd-java-agent/instrumentation/spring-web/src/test/java/test/Application.java
  dd-java-agent/instrumentation/spring-web/src/test/java/test/TestController.java
  dd-java-agent/instrumentation/spring-web/src/test/java/test/TestForm.java
  dd-trace-ot/src/main/java/datadog/trace/common/util/ConfigUtils.java
  gradle/dependencies.gradle
Labels: integrations

#226 Bootstrap + Dedicated Classloader
  dd-java-agent-ittests/dd-java-agent-ittests.gradle
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/TestLoggerRewrite.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ClassToInstrument.java
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/httpclient/ApacheHttpClientTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/jdbc/JDBCInstrumentationTest.groovy
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/ClassLoaderTest.java
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/ShadowPackageRenamingTest.java
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/instrumentation/annotation/TraceAnnotationsTest.java
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/integration/MongoAsyncClientInstrumentationTest.java
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/integration/MongoClientInstrumentationTest.java
  dd-java-agent-ittests/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/agent/bootstrap/DatadogClassLoader.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/agent/bootstrap/ExceptionLogger.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/agent/bootstrap/JDBCMaps.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/agent/bootstrap/PatchLogger.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
  dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
Labels: bug, enhancement

#229 classloader validation
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatcherTest.groovy
Labels: bug, enhancement

#230 Add resource naming instrumentation for jax-rs
  dd-java-agent/instrumentation/jax-rs/jax-rs.gradle
  dd-java-agent/instrumentation/jax-rs/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsInstrumentation.java
  dd-java-agent/instrumentation/jax-rs/src/test/groovy/JaxRsInstrumentationTest.groovy
  dd-java-agent/instrumentation/jax-rs/src/test/groovy/JerseyTest.groovy
  dd-java-agent/instrumentation/jax-rs/src/test/java/TestResource.java
  dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
  dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
  dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
  dd-java-agent/src/test/resources/logback.xml
  dd-java-agent/testing/src/main/java/datadog/trace/agent/test/AgentTestRunner.java
  dd-java-agent/testing/testing.gradle
  dd-java-agent/tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/ListWriter.java
  settings.gradle
Labels: enhancement, integrations

#231 Bootstrap delegation for wildfly/jboss
  dd-java-agent/instrumentation/jboss-classloading/jboss-classloading.gradle
  dd-java-agent/instrumentation/jboss-classloading/src/main/java/datadog/trace/instrumentation/jboss/JBossClassloadingInstrumentation.java
  dd-java-agent/instrumentation/jboss-classloading/src/test/groovy/JBossClassloadingTest.groovy
  settings.gradle
Labels: enhancement

#235 Move SpringBootBasedTest to package folder.
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
Labels: bug, dev/testing

#236 Set short timeouts for api test to prevent startup delays
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
Labels: bug, core

#238 Remove unneeded dependencies on dd-trace-ot.
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/instrumentation/apache-httpclient-4.3/apache-httpclient-4.3.gradle
  dd-java-agent/instrumentation/aws-sdk/aws-sdk.gradle
  dd-java-agent/instrumentation/datastax-cassandra-3.2/datastax-cassandra-3.2.gradle
  dd-java-agent/instrumentation/jax-rs/jax-rs.gradle
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jms-1/jms-1.gradle
  dd-java-agent/instrumentation/jms-2/jms-2.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
  dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
  dd-java-agent/instrumentation/mongo-3.1/mongo-3.1.gradle
  dd-java-agent/instrumentation/mongo-async-3.3/mongo-async-3.3.gradle
  dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle
  dd-java-agent/instrumentation/servlet-2/servlet-2.gradle
  dd-java-agent/instrumentation/spring-web/spring-web.gradle
  dd-java-agent/instrumentation/trace-annotation/trace-annotation.gradle
Labels: integrations

#237 Set timeouts on all the tests.
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/httpclient/ApacheHttpClientTest.groovy
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/jdbc/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/aws-sdk/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-3.2/src/test/groovy/CassandraClientTest.groovy
  dd-java-agent/instrumentation/jax-rs/src/test/groovy/JaxRsInstrumentationTest.groovy
  dd-java-agent/instrumentation/jax-rs/src/test/groovy/JerseyTest.groovy
  dd-java-agent/instrumentation/jboss-classloading/src/test/groovy/JBossClassloadingTest.groovy
  dd-java-agent/instrumentation/jms-1/src/test/groovy/JMS1Test.groovy
  dd-java-agent/instrumentation/jms-2/src/test/groovy/JMS2Test.groovy
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
  dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
  dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
  dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy
  dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServletTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/TomcatServletTest.groovy
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/HTTPCodecTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDSpanContextTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTraceConfigTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/ServiceTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/sampling/RateByServiceSamplerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/WriterQueueTest.groovy
Labels: dev/testing

#239 Use nanotime for additional clock resolution
  dd-java-agent/instrumentation/jboss-classloading/src/test/groovy/JBossClassloadingTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
Labels: core, enhancement
