Repository DataDog/dd-trace-java, pull requests merged in 2018-06, with the labels that each got.

#340 Add instrumentation for Java’s UrlConnection
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/instrumentation/url-connection/src/main/java/datadog/trace/instrumentation/url_connection/MessageHeadersInjectAdapter.java
  dd-java-agent/instrumentation/url-connection/src/main/java/datadog/trace/instrumentation/url_connection/UrlConnectionInstrumentation.java
  dd-java-agent/instrumentation/url-connection/src/main/java/datadog/trace/instrumentation/url_connection/UrlInstrumentation.java
  dd-java-agent/instrumentation/url-connection/src/test/groovy/HttpUrlConnectionTest.groovy
  dd-java-agent/instrumentation/url-connection/src/test/groovy/UrlConnectionTest.groovy
  dd-java-agent/instrumentation/url-connection/url-connection.gradle
  dd-java-agent/testing/src/main/java/datadog/trace/agent/test/TestUtils.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
  settings.gradle
Labels: integrations

#343 Refactor HttpUrlConnection Instrumentation
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
  dd-java-agent/instrumentation/http-url-connection/http-url-connection.gradle
  dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
  dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/MessageHeadersInjectAdapter.java
  dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
  dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionTest.groovy
  dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
  settings.gradle
Labels: dev/testing

#341 Fix thread pool instrumentation to work with Scala Slick, and add tests for Slick
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/CallDepthThreadLocalMap.java
  dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/slickTest/groovy/SlickTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/slickTest/scala/SlickUtils.scala
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TagsAssert.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TraceAssert.groovy
  gradle/jacoco.gradle
Labels: enhancement, integrations

#336 lettuce 5 redis client integration
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/instrumentation/lettuce-5/lettuce-5.gradle
  dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceAsyncCommandsInstrumentation.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceClientInstrumentation.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce/LettuceReactiveCommandsInstrumentation.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/ConnectionFutureAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/LettuceAsyncBiFunction.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/LettuceAsyncCommandsAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/LettuceInstrumentationUtil.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceFluxCreationAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceFluxTerminationRunnable.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceMonoCreationAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/rx/LettuceMonoDualConsumer.java
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceAsyncClientTest.groovy
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceReactiveClientTest.groovy
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceSyncClientTest.groovy
  settings.gradle
Labels: enhancement, integrations

#355 Upgrade some versions.
  dd-java-agent/dd-java-agent.gradle
  dd-trace-java.gradle
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
  gradle/dependencies.gradle
  gradle/java.gradle
  gradle/wrapper/gradle-wrapper.jar
Labels: core, dev/tooling

#345 CorrelationIdentifier for MDC frameworks.
  dd-java-agent/testing/src/test/groovy/TraceCorrelationTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/CorrelationIdentifier.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/OTTraceCorrelation.java
Labels: feature-request

#357 Close scope for async servlet requests
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/FilterChain3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServlet3Test.groovy
  dd-trace-ot/src/main/java/datadog/trace/common/writer/ListWriter.java
Labels: bug, integrations

#352 Netty HTTP client and server instrumentation
  buildSrc/src/main/groovy/VersionScanPlugin.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HandlerInstrumentation.java
  dd-java-agent/instrumentation/netty-4.0/netty-4.0.gradle
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientResponseTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/NettyResponseInjectAdapter.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerResponseTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/NettyRequestExtractAdapter.java
  dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ClientTest.groovy
  dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
  dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientResponseTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/NettyResponseInjectAdapter.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerResponseTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/NettyRequestExtractAdapter.java
  dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ClientTest.groovy
  dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TagsAssert.groovy
  gradle/java.gradle
  settings.gradle
Labels: integrations

#360 Improve jms1/jms2 receive handling
  dd-java-agent/instrumentation/jms-1/src/main/java/datadog/trace/instrumentation/jms1/JMS1MessageConsumerInstrumentation.java
  dd-java-agent/instrumentation/jms-1/src/test/groovy/JMS1Test.groovy
  dd-java-agent/instrumentation/jms-2/src/main/java/datadog/trace/instrumentation/jms2/JMS2MessageConsumerInstrumentation.java
  dd-java-agent/instrumentation/jms-2/src/test/groovy/JMS2Test.groovy
Labels: breaking-change, integrations

#364 Close Jetty Handler scope
  dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HandlerInstrumentation.java
  dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
Labels: bug

#372 Upgrade to gradle 4.8.1
  dd-trace-java.gradle
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dev/tooling

#358 Fix span time boundaries
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
  dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
  dd-trace-ot/src/main/java/datadog/trace/common/util/Clock.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy
Labels: core

#371 Set servlet’s user-principal as a tag when available
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/FilterChain2Instrumentation.java
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/HttpServlet2Instrumentation.java
  dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServlet2Test.groovy
  dd-java-agent/instrumentation/servlet-2/src/test/resources/realm.properties
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/FilterChain3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/JettyServlet3Test.groovy
  dd-java-agent/instrumentation/servlet-3/src/test/resources/realm.properties
Labels: enhancement, integrations

#354 JSP instrumentation first pass
  dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle
  dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JSPInstrumentation.java
  dd-java-agent/instrumentation/jsp-2.3/src/main/java/datadog/trace/instrumentation/jsp/JasperJSPCompilationContextInstrumentation.java
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/common/hello.html
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/common/javaLoopH2.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/common/loop.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/compileError.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToCompileError.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToHtml.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToIncludeMulti.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToJspForward.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToNoJavaJsp.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToNonExistent.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardToSimpleJava.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/forwards/forwardWithCompileError.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/getQuery.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/includes/includeHtml.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/includes/includeMulti.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/invalidMarkup.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/invalidWrite.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/nojava.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/post.jsp
  dd-java-agent/instrumentation/jsp-2.3/src/test/resources/webapps/jsptest/runtimeError.jsp
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java
  settings.gradle
Labels: integrations

#378 Remove most shadow relocates
  dd-java-agent-ittests/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/dd-java-agent.gradle
Labels: bug
