Repository DataDog/dd-trace-java, pull requests merged in 2018-10, with the labels that each got.

#521 Refactor Apache HttpClient Instrumentation.
  dd-java-agent/instrumentation/apache-httpclient-4.3/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
  dd-java-agent/instrumentation/apache-httpclient-4.3/src/main/java/datadog/trace/instrumentation/apachehttpclient/DDTracingClientExec.java
  dd-java-agent/instrumentation/apache-httpclient-4/apache-httpclient-4.gradle
  dd-java-agent/instrumentation/apache-httpclient-4/src/latestDepTest/groovy/ApacheHttpClientTest.groovy
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/test/groovy/ApacheHttpClientTest.groovy
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/SpanDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/aws-java-sdk-1.11.106/aws-java-sdk-1.11.106.gradle
  dd-java-agent/instrumentation/aws-java-sdk-1.11.106/src/main/java/datadog/trace/instrumentation/aws/v106/SpanDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.106/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-rest-5/elasticsearch-rest-5.gradle
  dd-java-agent/instrumentation/elasticsearch-transport-5/elasticsearch-transport-5.gradle
  dd-java-agent/instrumentation/elasticsearch-transport-6/elasticsearch-transport-6.gradle
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/HTTPComponent.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/OperationDecorator.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/URLAsResourceName.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy
  settings.gradle
Labels: breaking-change, integrations

#477 Upgrade Byte Buddy to 1.9.0
  .circleci/config.yml
  buildSrc/build.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy
  gradle/dependencies.gradle
Labels: core

#480 Run tests on Java 11
  .circleci/config.yml
  gradle/jacoco.gradle
  gradle/java.gradle
Labels: dev/testing

#529 Integration for Dropwizard Views
  dd-java-agent/instrumentation/apache-httpclient-4/apache-httpclient-4.gradle
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/dropwizard-views.gradle
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/main/java/datadog/trace/instrumentation/dropwizard/view/DropwizardViewInstrumentation.java
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/test/groovy/ViewRenderTest.groovy
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/test/resources/views/ftl/iso88591.ftl
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/test/resources/views/ftl/utf8.ftl
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/test/resources/views/mustache/iso88591.mustache
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/src/test/resources/views/mustache/utf8.mustache
  dd-java-agent/instrumentation/dropwizard/dropwizard.gradle
  dd-java-agent/instrumentation/jax-rs-client/jax-rs-client.gradle
  settings.gradle
Labels: integrations

#534 Fix trace id can't be decoded by agent due to being transmitted as float
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanSerializationTest.groovy
Labels: community, core

#538 Add additional retries for ES tests.
  dd-java-agent/instrumentation/elasticsearch-rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/latestDepTest/groovy/Elasticsearch5NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/latestDepTest/groovy/Elasticsearch5TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch-transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
Labels: dev/testing

#537 instrumentation context map-backed impl
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InstrumentationContext.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/InstrumentationContextProvider.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/MapBackedProvider.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/context/MapBackedProviderTest.groovy
  dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/test/context/BadClassToRemap.java
  dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/test/context/ClassToRemap.java
  dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
Labels: core
