Repository DataDog/dd-trace-java, pull requests merged in 2019-03, with the labels that each got.

#768 Agent doesn’t like getting floats.
  dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
  dd-trace-ot/src/test/groovy/datadog/trace/DDSpanContextTest.groovy
Labels: bug

#766 Implement HTTP timeout when sending traces to Datadog agent
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
Labels: core

#710 Change DDAgentWriter to use Disruptor
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
  dd-trace-ot/dd-trace-ot.gradle
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/trace/common/util/DaemonThreadFactory.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/ListWriter.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/LoggingWriter.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/Writer.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/WriterQueue.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/SpanFactory.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/DDApiTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/SerializationTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/api/writer/WriterQueueTest.groovy
  dd-trace-ot/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
Labels: core

#773 Improve selectivity of Hibernate instrumentation application
  dd-java-agent/instrumentation/hibernate/core-3.3/core-3.3.gradle
  dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/AbstractHibernateInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/CriteriaInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/QueryInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/SessionFactoryInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/SessionInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_3/TransactionInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/AbstractHibernateTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/CriteriaTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/QueryTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/SessionTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/java/Value.java
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/resources/hibernate.cfg.xml
  dd-java-agent/instrumentation/hibernate/core-3.5/src/main/java/datadog/trace/instrumentation/hibernate/core/v3_5/QueryInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-4.0/core-4.0.gradle
  dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/AbstractHibernateInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/CriteriaInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/QueryInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/SessionFactoryInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-4.0/src/main/java/datadog/trace/instrumentation/hibernate/core/v4_0/SessionInstrumentation.java
  dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
  settings.gradle
Labels: bug, integrations
