Repository DataDog/dd-trace-java, pull requests merged in 2019-07, with the labels that each got.

#885 Additional testing for split-by-instance config
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
  dd-java-agent/instrumentation/spymemcached-2.12/src/test/groovy/datadog/trace/instrumentation/spymemcached/SpymemcachedTest.groovy
Labels: dev/testing

#905 Run JmxFetch app as a daemon
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
Labels: core

#916 Remove default instance
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCConnectionUrlParser.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy
Labels: bug, integrations

#920 Container ID Tagging
  dd-trace-ot/src/main/java/datadog/opentracing/ContainerInfo.java
  dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/ContainerInfoTest.groovy
Labels: core

#914 Instrumentation of Google Http Client
  dd-java-agent/instrumentation/google-http-client/google-http-client.gradle
  dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientDecorator.java
  dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientInstrumentation.java
  dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/RequestState.java
  dd-java-agent/instrumentation/google-http-client/src/test/groovy/AbstractGoogleHttpClientTest.groovy
  dd-java-agent/instrumentation/google-http-client/src/test/groovy/GoogleHttpClientAsyncTest.groovy
  dd-java-agent/instrumentation/google-http-client/src/test/groovy/GoogleHttpClientTest.groovy
  settings.gradle
Labels: integrations

#917 Assert span in scope can't be null and add tests to verify
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/SimpleScope.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
Labels: breaking-change, core

#924 Kafka-clients: records(TopicPartition): unit tests + some (potential) improvements
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterable.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingList.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
Labels: community, integrations

#925 Add resource name to the @Trace annotation
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/SayTracedHello.java
  dd-trace-api/src/main/java/datadog/trace/api/Trace.java
Labels: enhancement

#927 Better hostname detection
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: breaking-change

#922 Cli Application Smoke Test
  dd-smoke-tests/README.md
  dd-smoke-tests/cli/cli.gradle
  dd-smoke-tests/cli/src/main/java/datadog/smoketest/cli/CliApplication.java
  dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy
  settings.gradle
Labels: dev/testing
