Repository DataDog/dd-trace-java, pull requests merged in 2019-06, with the labels that each got.

#874 Update Jackson Databind to 2.9.9
  gradle/dependencies.gradle
Labels: core

#866 Attempt to properly parse out instance name from JDBC url
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
  dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/slickTest/groovy/SlickTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/slickTest/scala/SlickUtils.scala
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBInfo.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCConnectionUrlParser.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCMaps.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCUtils.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCConnectionUrlParserTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
Labels: integrations

#863 Avoid usage of static getters when accessing configuration parameters
  dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/BaseDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/BaseDecoratorTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/DefaultInstrumenterTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
  dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/Slf4jMDCTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/ConfigUtils.groovy
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: core

#873 Run latestDepTests in a separate job
  .circleci/config.yml
Labels: dev/testing

#862 Provide a way to configure the tracer using properties file
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  dd-trace-api/src/test/resources/dd-java-tracer.properties
Labels: core
