Repository DataDog/dd-trace-java, pull requests merged in 2019-02, with the labels that each got.

#689 Don't break Clojure's protocols
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
Labels: bug, community

#692 Make test results in netty-4.0 client tests more readable
  dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ClientTest.groovy
Labels: dev/testing

#690 Collect JVM crashes in circleci artifacts
  .circleci/collect_reports.sh
  dd-trace-java.gradle
  gradle/java.gradle
Labels: dev/testing, dev/tooling

#695 Remove codec registry for inject/extract
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/Codec.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/DatadogHttpCodec.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/HTTPCodec.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/DatadogHttpExtractorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
Labels: core

#688 Fix webflux integration to not rely in active span
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/instrumentation/jms/src/test/groovy/SpringTemplateJMS1Test.groovy
  dd-java-agent/instrumentation/spring-webflux/spring-webflux.gradle
  dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/AbstractWebfluxInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/DispatcherHandlerInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/HandlerAdapterInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/RequestMappingInfoHandlerMappingInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java/datadog/trace/instrumentation/springwebflux/RouterFunctionInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/AdviceUtils.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/DispatcherHandlerAdvice.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/DispatcherHandlerMonoBiConsumer.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/DispatcherHandlerOnCancel.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/DispatcherHandlerOnSuccessOrError.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/HandlerAdapterAdvice.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/HandlerFunctionAdapterAdvice.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/RequestMappingInfoHandlerMappingAdvice.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/RouteOnSuccessOrError.java
  dd-java-agent/instrumentation/spring-webflux/src/main/java8/datadog/trace/instrumentation/springwebflux/RouterFunctionAdvice.java
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/SingleThreadedSpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/SpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/datadog/trace/instrumentation/springwebflux/FooModel.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/EchoHandler.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/EchoHandlerFunction.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/FooModel.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/SpringWebFluxTestApplication.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/TestController.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/java/dd/trace/instrumentation/springwebflux/RedirectComponent.java
  dd-java-agent/instrumentation/spring-webflux/src/test/resources/logback.xml
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
Labels: bug, integrations

#696 JMXFetch bundled integrations disabled by default
  dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: enhancement, integrations

#699 New API: Allow creating timestamp with custom time.
  dd-trace/src/main/java/datadog/trace/tracer/Clock.java
  dd-trace/src/main/java/datadog/trace/tracer/Timestamp.java
  dd-trace/src/main/java/datadog/trace/tracer/Tracer.java
  dd-trace/src/test/groovy/datadog/trace/tracer/ClockTest.groovy
  dd-trace/src/test/groovy/datadog/trace/tracer/TimestampTest.groovy
Labels: core

#700 New API: Add shutdown callback to shutdown the Tracer
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace/src/main/java/datadog/trace/tracer/Span.java
  dd-trace/src/main/java/datadog/trace/tracer/SpanImpl.java
  dd-trace/src/main/java/datadog/trace/tracer/Tracer.java
  dd-trace/src/test/groovy/datadog/trace/tracer/JsonSpan.groovy
  dd-trace/src/test/groovy/datadog/trace/tracer/SpanImplTest.groovy
  dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
Labels: core

#701 Allow non-wrapped tasks in disabled executors
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
  dd-java-agent/instrumentation/java-concurrent/akka-2.5-testing/src/test/groovy/AkkaExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/groovy/ScalaExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/FutureInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContinuableScope.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
Labels: bug, core, integrations

#704 Log when test starts
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
Labels: dev/testing

#698 Upgrade Byte Buddy to 1.9.9
  gradle/dependencies.gradle
Labels: core

#697 Upgrade Gradle to 4.10.3
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/benchmark/benchmark.gradle
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/testing/testing.gradle
  dd-smoke-tests/play/play.gradle
  dd-smoke-tests/springboot/springboot.gradle
  dd-smoke-tests/wildfly/wildfly.gradle
  dd-trace-java.gradle
  gradle/checkstyle.gradle
  gradle/java.gradle
  gradle/pom.gradle
  gradle/publish.gradle
  gradle/util.gradle
  gradle/version.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dev/tooling

#712 Limit ES-rest tests to 6.x.x versions
  dd-java-agent/instrumentation/elasticsearch-rest-6.4/elasticsearch-rest-6.4.gradle
Labels: dev/testing

#715 Exclude tests generated by “test-sets” plugin from alternate JVM tests
  gradle/java.gradle
Labels: dev/testing

#714 Fix how we evaluate if customlogger is on classpath
  dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
  dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
Labels: bug, core

#719 Trace Analytics Config
  dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/AnalyticsSampleRateDecorator.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
Labels: core

#720 Introduce base decorators
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/BaseDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/ClientDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpClientDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/ServerDecorator.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/BaseDecoratorTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/ClientDecoratorTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpClientDecoratorTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpServerDecoratorTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/ServerDecoratorTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: core

#721 Servlet migrate to decorators
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/AbstractServlet2Instrumentation.java
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
  dd-java-agent/instrumentation/servlet-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Decorator.java
  dd-java-agent/instrumentation/servlet-2/src/test/groovy/JettyServlet2Test.groovy
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/AsyncContextInstrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/FilterChain3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/HttpServlet3Instrumentation.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Decorator.java
  dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/TagSettingAsyncListener.java
  dd-java-agent/instrumentation/servlet-3/src/test/groovy/AbstractServlet3Test.groovy
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
Labels: core

#722 Akka and Apache HttpClient migrate to decorators
  dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy
  dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpClientDecorator.java
  dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpClientInstrumentation.java
  dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpClientTransformFlow.scala
  dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpServerDecorator.java
  dd-java-agent/instrumentation/akka-http-10.0/src/main/scala/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java
  dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientDecorator.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
  dd-java-agent/instrumentation/play-2.4/src/latestDepTest/groovy/Play26Test.groovy
Labels: core

#734 Increase time we wait for smoke tests servers to start up
  dd-smoke-tests/play/play.gradle
  dd-smoke-tests/springboot/springboot.gradle
  dd-smoke-tests/wildfly/wildfly.gradle
Labels: dev/testing

#741 Add instrumentation for Tomcat webapp classloading
  dd-java-agent/instrumentation/tomcat-classloading/src/main/java/datadog/trace/instrumentation/tomcat/TomcatClassloadingInstrumentation.java
  dd-java-agent/instrumentation/tomcat-classloading/src/test/groovy/TomcatClassloadingTest.groovy
  dd-java-agent/instrumentation/tomcat-classloading/tomcat-classloading.gradle
  settings.gradle
Labels: integrations
