Repository DataDog/dd-trace-java, pull requests merged in 2019-10, with the labels that each got.

#1025 Update vertx tests to play nice with latest version
  dd-java-agent/instrumentation/vertx/src/test/groovy/client/VertxRxCircuitBreakerWebClientTest.groovy
  dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxRxCircuitBreakerHttpServerTest.groovy
Labels: dev/testing

#1022 Change default for Spring and Ratpack analytics to be off
  dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/RatpackServerDecorator.java
  dd-java-agent/instrumentation/spring-web/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
Labels: breaking-change

#1045 Skip `@Decorator` classes when instrumenting
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/instrumentation/cdi-1.2/cdi-1.2.gradle
  dd-java-agent/instrumentation/cdi-1.2/src/test/groovy/CDIContainerTest.groovy
  dd-java-agent/instrumentation/cdi-1.2/src/test/java/datadog/trace/instrumentation/TestBean.java
  settings.gradle
Labels: bug

#641 Minimal changes required for OT 0.32
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/GlobalTracerUtils.java
  dd-trace-ot/docs/opentracing-api.md
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/B3HttpCodec.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/DatadogHttpCodec.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/HaystackHttpCodec.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/HttpCodec.java
  dd-trace-ot/src/main/java/datadog/opentracing/propagation/TagContext.java
  dd-trace-ot/src/main/java/datadog/opentracing/scopemanager/ContextualScopeManager.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
  gradle/dependencies.gradle
Labels: core

#1047 Add instrumentation for all of Apache HttpClient methods
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HostAndRequestAsHttpUriRequest.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/test/groovy/ApacheHttpClientTest.groovy
Labels: bug, integrations

#1052 Treat empty proc file as `Not Running In Container`
  dd-trace-ot/src/main/java/datadog/opentracing/ContainerInfo.java
Labels: bug

#1059 Remove opentracing api documentation in dd-trace-ot
  dd-trace-ot/docs/opentracing-api.md
Labels: docs
