Repository DataDog/dd-trace-java, pull requests merged in 2019-09, with the labels that each got.

#973 Run all tests on all java versions
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/hibernate/core-3.3/core-3.3.gradle
  dd-java-agent/instrumentation/hibernate/core-4.0/core-4.0.gradle
  dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
  dd-java-agent/instrumentation/http-url-connection/http-url-connection.gradle
  dd-java-agent/instrumentation/java-concurrent/akka-2.5-testing/akka-2.5-testing.gradle
  dd-java-agent/instrumentation/java-concurrent/akka-testing/akka-testing.gradle
  dd-java-agent/instrumentation/java-concurrent/java-concurrent.gradle
  dd-java-agent/instrumentation/java-concurrent/scala-testing/scala-testing.gradle
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-trace/src/test/groovy/datadog/trace/tracer/SpanImplTest.groovy
  dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
  gradle/java.gradle
Labels: dev/testing

#979 Apply fixed default operation name for @Trace generated spans
  dd-java-agent/instrumentation/akka-http-10.0/src/lagomTest/groovy/LagomTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy
  dd-java-agent/instrumentation/java-concurrent/akka-testing/src/test/groovy/AkkaActorTest.groovy
  dd-java-agent/instrumentation/java-concurrent/kotlin-testing/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/groovy/ScalaInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/scala-testing/src/test/scala/ScalaAsyncChild.java
  dd-java-agent/instrumentation/java-concurrent/src/slickTest/groovy/SlickTest.groovy
  dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/SpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux/src/test/groovy/dd/trace/instrumentation/springwebflux/server/EchoHandler.groovy
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy
Labels: breaking-change

#980 Fix span error tagging in grpc server interceptor
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerBuilderInstrumentation.java
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/GrpcServerDecorator.java
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
Labels: community

#957 Java 9 Modules Smoketest
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DriverInstrumentation.java
  dd-smoke-tests/java9-modules/java9-modules.gradle
  dd-smoke-tests/java9-modules/src/main/java9/datadog/smoketest/moduleapp/ModuleApplication.java
  dd-smoke-tests/java9-modules/src/main/java9/module-info.java
  dd-smoke-tests/java9-modules/src/test/groovy/datadog/smoketest/Java9ModulesSmokeTest.groovy
  gradle/java.gradle
  settings.gradle
Labels: dev/testing

#990 Migrate spring-web to base httpserver test
  dd-java-agent/instrumentation/glassfish/src/test/groovy/TestServlets.java
  dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyAsyncTest.groovy
  dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyTest.groovy
  dd-java-agent/instrumentation/spring-web/spring-web.gradle
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/AppConfig.groovy
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/ServletTestInstrumentation.java
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/SpringBootBasedTest.groovy
  dd-java-agent/instrumentation/spring-web/src/test/groovy/test/TestController.groovy
  dd-java-agent/instrumentation/spring-web/src/test/java/test/Application.java
  dd-java-agent/instrumentation/spring-web/src/test/java/test/TestController.java
  dd-java-agent/instrumentation/spring-web/src/test/java/test/TestForm.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Labels: dev/testing
