Repository DataDog/dd-trace-java, pull requests merged in 2019-05, with the labels that each got.

#811 Add support for HystrixObservableCommand
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpClientDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/HttpServerDecorator.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
  dd-java-agent/instrumentation/hystrix-1.4/hystrix-1.4.gradle
  dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixCommandInstrumentation.java
  dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixDecorator.java
  dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixInstrumentation.java
  dd-java-agent/instrumentation/hystrix-1.4/src/main/java/rx/DDTracingUtil.java
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
  dd-java-agent/instrumentation/jboss-classloading/src/test/groovy/JBossClassloadingTest.groovy
  dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
Labels: enhancement, integrations

#815 Remove latestDepTest for Elasticsearch Transport 5
  dd-java-agent/instrumentation/elasticsearch/transport-5/src/latestDepTest/groovy/Elasticsearch5NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5/src/latestDepTest/groovy/Elasticsearch5TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5/transport-5.gradle
Labels: dev/testing

#816 Add transient modifier to added context fields.
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
  dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
Labels: bug

#817 Bump version 0.27.0
  dd-trace-java.gradle
Labels: core

#821 Add implementation details to each jar manifest.
  gradle/java.gradle
Labels: dev/tooling

#824 Update to latest versions of groovy and spock
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-java-agent/instrumentation/okhttp-3/okhttp-3.gradle
  dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  gradle/dependencies.gradle
Labels: core

#833 Fix resource name for Ratpack
  dd-java-agent/instrumentation/ratpack-1.4/src/main/java8/datadog/trace/instrumentation/ratpack/RatpackServerDecorator.java
  dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/RatpackTest.groovy
Labels: bug, integrations

#827 Detect hostname
  CONTRIBUTING.md
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
Labels: core

#839 Glassfish: prevent blacklisting of specific classes and dump stacktrace in debug mode if this happens
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/UtilsTest.groovy
  dd-java-agent/instrumentation/glassfish/glassfish.gradle
  dd-java-agent/instrumentation/glassfish/src/main/java/datadog/trace/instrumentation/glassfish/GlassfishInstrumentation.java
  settings.gradle
Labels: core
