Repository DataDog/dd-trace-java, pull requests merged in 2019-12, with the labels that each got.

#1126 HelperInjector optimization
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
Labels: performance

#1131 apply comma split logic to servlet request extract adapter
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/OpenTracing32.java
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Labels: community

#1152 Disable decorators via config
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
Labels: feature-request

#1128 Add RMI support
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ThreadLocalContext.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/instrumentation/rmi/rmi.gradle
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/client/RmiClientDecorator.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/client/RmiClientInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/ContextPayload.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/ContextPropagator.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/client/RmiClientContextInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/server/ContextDispatcher.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/server/RmiServerContextInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/server/RmiServerDecorator.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/server/RmiServerInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/test/groovy/RmiTest.groovy
  dd-java-agent/instrumentation/rmi/src/test/java/rmi/app/Greeter.java
  dd-java-agent/instrumentation/rmi/src/test/java/rmi/app/Server.java
  dd-java-agent/instrumentation/rmi/src/test/java/rmi/app/ServerLegacy.java
  settings.gradle
Labels: integrations
