Repository DataDog/dd-trace-java, pull requests merged in 2019-01, with the labels that each got.

#643 Moves all ittests to be tests under dd-java-agent.
  dd-java-agent-ittests/dd-java-agent-ittests.gradle
  dd-java-agent-ittests/src/test/resources/logback.xml
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/java-concurrent/akka-testing/akka-testing.gradle
  dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/DDInfoTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/muzzle/MuzzleBytecodeTransformTest.groovy
  dd-java-agent/src/test/java/datadog/test/ClassToInstrument.java
  dd-java-agent/src/test/java/datadog/test/ClassToInstrumentChild.java
  dd-java-agent/src/test/java/datadog/trace/agent/integration/MongoAsyncClientInstrumentationTest.java
  dd-java-agent/src/test/java/datadog/trace/agent/integration/MongoClientInstrumentationTest.java
  dd-java-agent/src/test/java/datadog/trace/agent/integration/OkHTTPInstrumentationTest.java
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/src/test/java/jvmbootstraptest/CustomLogManager.java
  dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
  gradle/java.gradle
  settings.gradle
Labels: dev/testing

#654 Workaround LogManager startup issue and add springboot test
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-smoke-tests/README.md
  dd-smoke-tests/dd-smoke-tests.gradle
  dd-smoke-tests/play/play.gradle
  dd-smoke-tests/springboot/springboot.gradle
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/SpringbootApplication.java
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/WebController.java
  dd-smoke-tests/springboot/src/main/resources/application.properties
  dd-smoke-tests/springboot/src/test/groovy/datadog/trace/agent/SpringBootSmokeTest.groovy
  dd-smoke-tests/wildfly/wildfly.gradle
  dd-trace-java.gradle
  gradle/util.gradle
  settings.gradle
Labels: bug, dev/testing

#661 Tag JMX metrics with `service` in addition to `service.name`
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: bug

#658 Upgrade jackson to 2.9.8
  dd-java-agent/instrumentation/elasticsearch-transport-2/elasticsearch-transport-2.gradle
  dd-trace-ot/dd-trace-ot.gradle
  dd-trace/src/test/groovy/datadog/trace/tracer/JsonSpan.groovy
  dd-trace/src/test/groovy/datadog/trace/tracer/writer/AgentClientTest.groovy
  gradle/dependencies.gradle
Labels: core

#657 Play nice with Java's LogManager across all JVMs
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/instrumentation/jre-logging/jre-logging.gradle
  dd-java-agent/instrumentation/jre-logging/src/main/java/datadog/trace/instrumentation/jre/logging/LoggerInstrumentation.java
  dd-java-agent/instrumentation/jre-logging/src/test/groovy/LoggerPatchTest.groovy
  dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
  dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  settings.gradle
Labels: bug, dev/testing

#662 Add support for partial trace flush
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy
Labels: core

#640 Initial support for setting Event Sample Rate via tags
  dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/DDDecoratorsFactory.java
  dd-trace-ot/src/main/java/datadog/opentracing/decorators/EventSampleRateDecorator.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/SpanDecoratorTest.groovy
  dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
Labels: core

#663 Update test-sets plugin to 2.1.1
  dd-trace-java.gradle
Labels: dev/testing

#664 Update shadow plugin to 4.0.4
  dd-java-agent/dd-java-agent.gradle
  dd-smoke-tests/springboot/springboot.gradle
Labels: dev/tooling

#671 Improve OSGi class loader instrumentation
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/instrumentation/jboss-classloading/src/main/java/datadog/trace/instrumentation/jboss/JBossClassloadingInstrumentation.java
  dd-java-agent/instrumentation/osgi-classloading/osgi-classloading.gradle
  dd-java-agent/instrumentation/osgi-classloading/src/main/java/datadog/trace/instrumentation/osgi/OSGIClassloadingInstrumentation.java
  dd-java-agent/instrumentation/osgi-classloading/src/test/groovy/OSGIClassloadingTest.groovy
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
Labels: integrations

#673 Makedir before creating file, Fail build if script errors
  dd-java-agent/agent-jmxfetch/copy-metric-configs.sh
Labels: dev/tooling

#666 Initial AWS2 SDK instrumentation
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test_1_11_106/groovy/AWSClientTest.groovy
  dd-java-agent/instrumentation/aws-java-sdk-2.2/aws-java-sdk-2.2.gradle
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AbstractAwsClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsHttpClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/AwsClientTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AdviceUtils.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/FutureInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableCallableInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/java/AsyncChild.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/ChannelFutureListenerInstrumentation.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/NettyChannelPipelineInstrumentation.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
  settings.gradle
Labels: integrations

#670 Move awaitGC to common utility package
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestUtils.java
  dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
  dd-java-agent/testing/src/test/java/muzzle/MuzzleWeakReferenceTest.java
  dd-java-agent/testing/testing.gradle
  dd-trace-ot/dd-trace-ot.gradle
  dd-trace-ot/src/test/groovy/datadog/opentracing/PendingTraceTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/scopemanager/ScopeManagerTest.groovy
  dd-trace/dd-trace.gradle
  dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
  settings.gradle
  utils/gc-utils/gc-utils.gradle
  utils/gc-utils/src/main/java/datadog/trace/util/gc/GCUtils.java
Labels: dev/testing

#676 netty40 improvements
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/ChannelFutureListenerInstrumentation.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/NettyChannelPipelineInstrumentation.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
Labels: integrations

#675 Ensure the copyMetricConfigs task runs after processResources
  .circleci/collect_libs.sh
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-jmxfetch/copy-metric-configs.sh
Labels: dev/tooling

#678 Use lombok builder for Tracer construction.
  dd-trace-ext/src/main/java/datadog/trace/tracer/ext/Examples.java
  dd-trace/dd-trace.gradle
  dd-trace/src/main/java/datadog/trace/tracer/Span.java
  dd-trace/src/main/java/datadog/trace/tracer/Tracer.java
  dd-trace/src/main/java/datadog/trace/tracer/writer/AgentWriter.java
  dd-trace/src/test/groovy/datadog/trace/tracer/TracerTest.groovy
Labels: core

#684 Replace jboss classpath check with ENV check for jmxfetch delay
  dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java
Labels: bug, core

#683 Hard-code Hystrix operation (span) name, leaving the resource name dynamic
  .gitignore
  dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixCommandInstrumentation.java
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixTest.groovy
Labels: integrations
