Repository DataDog/dd-trace-java, pull requests merged in 2020-08, with the labels that each got.

#1741 finer grained synchronization for classloading of agent classes
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InternalJarURLHandlerTest.groovy
Labels: no release notes

#1728 haystack/datadog context propagation
  dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy
Labels: community

#1760 Rework string handling
  .palantir/revapi.yml
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Codec.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Packer.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/StringWritingTest.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UTF8BytesString.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/Utf8ByteStringTest.groovy
Labels: no release notes

#1765 mapadapter tweaks
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
Labels: no release notes

#1758 Add synchronization while adding dd tags to thread context(MDC) map
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/ThreadLocalWithDDTagsInitValue.java
  dd-java-agent/instrumentation/log4j1/src/test/groovy/Log4j1MDCTest.groovy
  dd-java-agent/instrumentation/log4j2/src/main/java/datadog/trace/instrumentation/log4j2/ThreadContextInstrumentation.java
  dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextTest.groovy
  dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
  dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/Slf4jMDCTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy
Labels: bug

#1778 simplify scope manager
  .palantir/revapi.yml
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/EventScopeInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ListenerScopeInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ScopeInterceptor.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Labels: enhancement, low-hanging-fruit, performance

#1781 replace guava Joiner with Strings.join
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/Elasticsearch2TransportClientInstrumentation.java
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/Elasticsearch53TransportClientInstrumentation.java
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/main/java/datadog/trace/instrumentation/elasticsearch5_3/TransportActionListener.java
  dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/Elasticsearch5TransportClientInstrumentation.java
  dd-java-agent/instrumentation/elasticsearch/transport-5/src/main/java/datadog/trace/instrumentation/elasticsearch5/TransportActionListener.java
  dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/Elasticsearch6TransportClientInstrumentation.java
  dd-java-agent/instrumentation/elasticsearch/transport-6/src/main/java/datadog/trace/instrumentation/elasticsearch6/TransportActionListener.java
  internal-api/src/main/java/datadog/trace/api/utils/Strings.java
  internal-api/src/test/groovy/datadog/trace/api/utils/StringsTest.groovy
Labels: remove guava

#1779 Replace SLF4J SimpleLogger with own compatible implementation
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-logging/agent-logging.gradle
  dd-java-agent/agent-logging/src/main/java/datadog/slf4j/impl/StaticLoggerBinder.java
  dd-java-agent/agent-logging/src/main/java/datadog/slf4j/impl/StaticMDCBinder.java
  dd-java-agent/agent-logging/src/main/java/datadog/slf4j/impl/StaticMarkerBinder.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/DDLogger.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/DDLoggerFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LogLevel.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LoggerHelper.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LoggerHelperFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatHelper.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
  dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/DDLoggerTest.groovy
  dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/LogLevelTest.groovy
  dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatHelperTest.groovy
  dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatSettingsTest.groovy
  dd-java-agent/agent-logging/src/test/resources/slcompatsettingstest.properties
  dd-java-agent/agent-profiling/agent-profiling.gradle
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Constants.java
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
  dd-smoke-tests/opentracing/opentracing.gradle
  settings.gradle
Labels: no release notes

#1777 Fix db query is not get when using scalikejdbc
  dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle
  dd-java-agent/instrumentation/jdbc/scalikejdbc/src/test/groovy/ScalikeJDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jdbc/scalikejdbc/src/test/scala/ScalikeSqlExecutor.scala
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
  settings.gradle
Labels: community

#1786 don't use getHeader in GrizzlyRequestExtractAdapter
  dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyRequestExtractAdapter.java
Labels: no release notes

#1787 Use blocking queue implementation for prioritisation
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Prioritization.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/PrioritizationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceProcessingWorkerTest.groovy
Labels: no release notes

#1788 Fix double read of shared atomic in reactor instrumentation
  dd-java-agent/instrumentation/reactor-core-3.1/src/main/java8/datadog/trace/instrumentation/reactor/core/TracingSubscriber.java
Labels: bug

#1784 CI-App: JUnit4 - Use a RunListener to send traces
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Utils.java
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
Labels: no release notes

#1789 CI-App: TestNG instrumentation
  dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
  dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGInstrumentation.java
  dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TracingListener.java
  dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/BaseTestInheritance.java
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestError.java
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestFailed.java
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestFailedWithSuccessPercentage.java
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestInheritance.java
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestSkipped.java
  dd-java-agent/instrumentation/testng-6.4/src/test/java/org/example/TestSucceed.java
  dd-java-agent/instrumentation/testng-6.4/testng-6.4.gradle
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  gradle/java.gradle
  settings.gradle
Labels: no release notes

#1798 abstract FixedSizeCache to allow interchangeability
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/cache/CHMCache.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/cache/DDCache.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/cache/DDCaches.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/cache/FixedSizeCache.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/cache/QualifiedClassNameCache.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/cache/FixedSizeCacheTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/cache/QualifiedClassNameCacheTest.groovy
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/hystrix-1.4/src/main/java/datadog/trace/instrumentation/hystrix/HystrixDecorator.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageExtractAdapter.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
  dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringWebHttpServerDecorator.java
Labels: no release notes

#1803 Don't add webflux filter multiple times
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/WebClientTracingFilter.java
  dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBase.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBasicTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBuilderReuseTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFilterBuilderReuseTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientFilterTest.groovy
Labels: bug

#1783 CI-App: JUnit5 Instrumentation
  dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
  dd-java-agent/instrumentation/junit-5.3/junit-5.3.gradle
  dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
  dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/JUnit5Decorator.java
  dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/TracingListener.java
  dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/BaseTestInheritance.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestError.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestFactory.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestFailed.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestInheritance.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestParameterized.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestRepeated.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSkipped.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSkippedClass.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestSucceed.java
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestTemplate.java
  dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
  gradle/java.gradle
  settings.gradle
Labels: no release notes

#1799 CI-App: Set CI and git tags in test spans
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Decorator.java
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/TracingListener.java
  dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
  dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
  dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGDecorator.java
  dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
Labels: no release notes

#1809 Spring boot/gRPC combined integration test
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/State.java
  dd-smoke-tests/springboot-grpc/springboot-grpc.gradle
  dd-smoke-tests/springboot-grpc/src/main/java/datadog/smoketest/springboot/SpringbootApplication.java
  dd-smoke-tests/springboot-grpc/src/main/java/datadog/smoketest/springboot/controller/WebController.java
  dd-smoke-tests/springboot-grpc/src/main/java/datadog/smoketest/springboot/grpc/LocalInterface.java
  dd-smoke-tests/springboot-grpc/src/main/java/datadog/smoketest/springboot/grpc/Responder.java
  dd-smoke-tests/springboot-grpc/src/main/java/datadog/smoketest/springboot/grpc/SynchronousGreeter.java
  dd-smoke-tests/springboot-grpc/src/main/proto/message.proto
  dd-smoke-tests/springboot-grpc/src/main/resources/application.properties
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootSmokeTest.groovy
  settings.gradle
Labels: no release notes
