Repository DataDog/dd-trace-java, pull requests merged in 2020-11, with the labels that each got.

#2043 MongoDB 4 driver instrumentation
  dd-java-agent/instrumentation/mongo/driver-4/driver-4.gradle
  dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Mongo4ClientDecorator.java
  dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Mongo4ClientInstrumentation.java
  dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Tracing4CommandListener.java
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy
  settings.gradle
Labels: integrations

#2068 remove counterproductive optimisations
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/URLAsResourceNameRule.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UTF8BytesString.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/Utf8ByteStringTest.groovy
Labels: no release notes

#2048 Add comment explaining the overlap situation involving Mongo 3.x and 4.x
  dd-java-agent/instrumentation/mongo/driver-4/driver-4.gradle
Labels: no release notes

#2072 Add toHexStringPadded to DDId
  dd-trace-api/src/main/java/datadog/trace/api/DDId.java
  dd-trace-api/src/test/groovy/datadog/trace/api/DDIdTest.groovy
Labels: no release notes

#2074 typed spans
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/NoOpMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/AbstractSampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/AllSampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/ForcePrioritySampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/PrioritySampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/RateSampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedSampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/Sampler.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/SamplingRule.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanData.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/AllSamplerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperRealAgentTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
Labels: no release notes, refactoring

#2080 Wait for aerospike container to start on CI
  dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeBaseTest.groovy
Labels: no release notes

#2088 Exclude ancient 20020423 pre-release from commons-httpclient-2 latest version
  dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle
Labels: no release notes

#2077 metrics format change
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AgentIntegrationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SimpleSpan.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: no release notes

#2091 make field injection smoke test break if CompletableFuture injection breaks
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
Labels: dev/testing, no release notes

#2083 Datanucleus/JDO instrumentation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/OrmClientDecorator.java
  dd-java-agent/instrumentation/datanucleus-4/datanucleus-4.gradle
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/DatanucleusDecorator.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/ExecutionContextInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/JDOConnectionInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/JDOQueryInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/JDOTransactionInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/ParamLoggingStatementInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/test/groovy/DatanucleusTest.groovy
  dd-java-agent/instrumentation/datanucleus-4/src/test/java/Value.java
  dd-java-agent/instrumentation/datanucleus-4/src/test/resources/META-INF/persistence.xml
  dd-trace-api/src/main/java/datadog/trace/api/DDSpanTypes.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InternalSpanTypes.java
  settings.gradle
Labels: integrations

#2098 remove analytics sample rate rule
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ClientDecoratorTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DBTypeProcessingDatabaseClientDecoratorTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecoratorTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ServerDecoratorTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/AnalyticsSampleRateRule.java
Labels: no release notes

#2097 Use agent scheduler for profiling
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
  dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
  internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
  internal-api/src/test/groovy/datadog/trace/util/AgentTaskSchedulerTest.groovy
  internal-api/src/test/groovy/datadog/trace/util/PeriodicSchedulingTest.groovy
Labels: no release notes

#2099 Don't override user-provided service name with servlet.context
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ServletContextTagInterceptor.java
  dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/CapturedEnvironmentConfigSource.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/SystemPropertiesConfigSource.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: bug

#2108 Support using AgentTaskScheduler as a simple Executor
  internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
  internal-api/src/test/groovy/datadog/trace/util/AgentTaskSchedulerTest.groovy
Labels: no release notes

#2110 Some cleanup and logging of which LogContextScopeListener gets added
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
  dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/Log4j1MDCInstrumentation.java
  dd-java-agent/instrumentation/log4j1/src/test/groovy/Log4j1MDCTest.groovy
  dd-java-agent/instrumentation/log4j2/src/main/java/datadog/trace/instrumentation/log4j2/ThreadContextInstrumentation.java
  dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextTest.groovy
  dd-java-agent/instrumentation/slf4j-mdc/src/main/java/datadog/trace/instrumentation/slf4j/mdc/MDCInjectionInstrumentation.java
  dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/ClassLoaderTestHelper.java
  dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/Slf4jMDCClassLoaderTest.groovy
  dd-java-agent/instrumentation/slf4j-mdc/src/test/groovy/Slf4jMDCTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy
  dd-smoke-tests/slf4j-mdc/slf4j-mdc.gradle
  dd-smoke-tests/slf4j-mdc/src/main/java/datadog/smoketest/slf4jmdc/Slf4jMDCApp.java
  dd-smoke-tests/slf4j-mdc/src/main/java/org/slf4j/impl/StaticMDCBinder.java
  dd-smoke-tests/slf4j-mdc/src/test/groovy/datadog/smoketest/Slf4jMDCSmokeTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  settings.gradle
Labels: no release notes

#2112 treat comparable runnables specially
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ComparableRunnable.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/NewTaskFor.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/java/ComparableAsyncChild.java
Labels: bug

#2114 Only consider external dependencies when deciding transitive dependencies to list in the 'dd-trace-ot' pom.
  dd-trace-ot/dd-trace-ot.gradle
Labels: dev/tooling, no release notes

#2044 Replace Guava caches
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakCache.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/CLHMWeakCache.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/CaffeineWeakCache.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/GuavaWeakCache.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
  dd-java-agent/agent-tooling/src/patch/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakCacheTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-3/datastax-cassandra-3.gradle
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
Labels: remove guava

#2118 exclude errorprone and checker-qual
  dd-java-agent/agent-tooling/agent-tooling.gradle
Labels: no release notes

#2107 add latency metrics
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/Writable.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MsgPackWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/protobuf/ProtobufWriter.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AgentIntegrationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsAggregatorFactoryTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
  dd-trace-ot/dd-trace-ot.gradle
  internal-api/src/main/java/datadog/trace/api/Config.java
  settings.gradle
  utils/histograms/histograms.gradle
  utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
  utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogramFactory.java
  utils/histograms/src/main/java/datadog/trace/core/histogram/Histogram.java
  utils/histograms/src/main/java/datadog/trace/core/histogram/HistogramFactory.java
  utils/histograms/src/main/java/datadog/trace/core/histogram/Histograms.java
  utils/histograms/src/main/java/datadog/trace/core/histogram/StubHistogram.java
  utils/histograms/src/test/groovy/HistogramsTest.groovy
Labels: no release notes

#2121 log at debug level in AgentTaskScheduler
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
Labels: no release notes

#2122 use ConcurrentHashMap instead of synchronized HashMap for class load callbacks
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
Labels: no release notes

#2120 Fix NPE on skipTrace method for JUnit4 instrumentation.
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Decorator.java
  dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4DecoratorTest.groovy
  dd-java-agent/instrumentation/junit-4.10/src/test/java/org/example/TestDisableTestTrace.java
  gradle/java.gradle
Labels: no release notes

#2124 Fix check in SystemAccessTest to handle 1.8 JVMs without JFR
  dd-trace-core/src/test/groovy/datadog/trace/core/util/SystemAccessTest.groovy
Labels: dev/testing, no release notes

#2131 Support putting null contexts when falling back to weak-map
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy
Labels: no release notes

#2130 remove unnecessary String.replaceAll
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreUtils.java
Labels: efficiency, no release notes

#2134 Wait for reader in AggregateMetricsTest to finish
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
Labels: no release notes

#2126 bump JCTools version
  dd-trace-core/dd-trace-core.gradle
Labels: dependencies

#2133 Simplify context store read check
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreReadsRewritingVisitor.java
Labels: no release notes

#2113 simplify tag interceptors
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecoratorTest.groovy
  dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientDecorator.java
  dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-4/src/main/java/datadog/trace/instrumentation/mongo4/Mongo4ClientDecorator.java
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/ExclusiveSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/DBStatementRule.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/ResourceNameRule.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/AbstractTagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ForceManualDropTagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ForceManualKeepTagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/PeerServiceTagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ServiceNameTagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/ServletContextTagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptorsFactory.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
Labels: no release notes, refactoring

#2136 Fix metrics aggregation
  dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
Labels: no release notes
