Repository DataDog/dd-trace-java, pull requests merged in 2020-07, with the labels that each got.

#1652 ignore micronaut tracing classes
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
Labels: bug

#1653 Move the StatsDClient into CoreTracer
  .palantir/revapi.yml
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/Writer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Monitor.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
Labels: breaking-change

#1661 Strict mode and health metrics for scope close failures
  dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelTracer.java
  dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
  dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTScopeManager.java
  dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTTracer.java
  dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
  dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTScopeManager.java
  dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java
  dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/OTScopeManager.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/OpenTracingAPITest.groovy
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScopeManager.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeSource.java
Labels: no release notes

#1659 replace msgpack-java
  .palantir/revapi.yml
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/LoggingWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DispatchingDisruptor.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/Monitor.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/MsgPackStatefulSerializer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/StatefulSerializer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceBuffer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java
  dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/JsonFormatWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/MsgpackFormatWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/ByteBufferConsumer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Codec.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/EncodingCache.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/EncodingCachingStrategies.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Mapper.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MessageFormatter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Packer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Writable.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/Writer.java
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/serialization/JsonFormatWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/serialization/MsgPackFormatWriterTest.groovy
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/IntPackingTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/PackerTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/SmokeTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/StringWritingTest.java
  dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
Labels: performance

#1675 Config class should be loaded on the bootstrap for instrumentation tests.
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/TextMapExtractAdapterTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
Labels: no release notes

#1669 Add classloader matcher to validate scala/akka presence
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AkkaExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ScalaExecutorInstrumentation.java
Labels: performance

#1694 Simplify Config runtime id handling
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/ConfigUtils.groovy
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  utils/test-utils/src/main/groovy/datadog/trace/util/test/DDSpecification.groovy
Labels: no release notes

#1699 Small webflux optimization
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/WebClientTracingFilter.java
Labels: no release notes

#1706 Fix finatra tests for latest dependencies
  dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
  dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/groovy/FinatraServer270Test.groovy
  dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/scala/FinatraController.scala
  dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/scala/FinatraServer.scala
  dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/scala/ResponseSettingExceptionMapper.scala
Labels: no release notes

#1719 UnsafeUtils::setStaticFieldViaUnsafe should use putBooleanVolatile
  dd-java-agent/instrumentation/log4j2/src/test/groovy/Log4jThreadContextWithEnableThreadLocalsTest.groovy
  dd-java-agent/testing/src/main/java/datadog/trace/agent/test/utils/UnsafeUtils.java
Labels: dev/testing, no release notes

#1721 Don't double count baggage overridden by tag
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapper.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
Labels: bug

#1703 Check for error condition before setting ERROR_MSG
  dd-java-agent/instrumentation/opentracing/src/main/java/datadog/trace/instrumentation/opentracing/DefaultLogHandler.java
  dd-trace-ot/src/main/java/datadog/opentracing/DefaultLogHandler.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/DefaultLogHandlerTest.groovy
Labels: community

#1726 Remove specific configuration properties for JUnit integration.
  dd-java-agent/instrumentation/junit-4.10/junit-4.10.gradle
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Labels: no release notes
