Repository DataDog/dd-trace-java, pull requests merged in 2020-05, with the labels that each got.

#1424 [Breaking change for dd-trace-api] Deprecate scope finishOnClose and continuation close
  dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContextualScopeManager.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/DDScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: breaking-change

#1448 Adding an option to manually disable Kafka headers
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/Config.java
Labels: community

#1450 Rename java packages for lettuce 4 and 5 to not have collisions
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsInstrumentation.java
  dd-java-agent/instrumentation/lettuce-4/src/main/java/datadog/trace/instrumentation/lettuce4/LettuceClientInstrumentation.java
  dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/InstrumentationPoints.java
  dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/LettuceAsyncCommandsAdvice.java
  dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/LettuceClientDecorator.java
  dd-java-agent/instrumentation/lettuce-4/src/main/java8/datadog/trace/instrumentation/lettuce4/RedisConnectionAdvice.java
  dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4AsyncClientTest.groovy
  dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4SyncClientTest.groovy
  dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsInstrumentation.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceClientInstrumentation.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java/datadog/trace/instrumentation/lettuce5/LettuceReactiveCommandsInstrumentation.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/ConnectionFutureAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceAsyncBiFunction.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceAsyncCommandsAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceClientDecorator.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/LettuceInstrumentationUtil.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceFluxCreationAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceFluxTerminationRunnable.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceMonoCreationAdvice.java
  dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce5/rx/LettuceMonoDualConsumer.java
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5AsyncClientTest.groovy
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5SyncClientTest.groovy
Labels: bug

#1449 Escape backticks and add labels to release notes
  .github/workflows/draft-release-notes-on-tag.yaml
Labels: no release notes

#1457 Save circle cache with name matching restore patterns
  .circleci/config.yml
Labels: no release notes

#1465 Reformat the revapi file
  .palantir/revapi.yml
Labels: dev/tooling, no release notes

#1454 move batching to trace processor to ease memory buffer reuse
  .palantir/revapi.yml
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/AbstractDisruptor.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/BatchWritingDisruptor.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DispatchingDisruptor.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DisruptorEvent.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DisruptorUtils.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/MsgPackStatefulSerializer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/StatefulSerializer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceBuffer.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingDisruptor.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
Labels: performance

#1470 Fix NPE in HTTP Rule when span type is not set
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/HttpStatusErrorRule.java
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy
Labels: bug

#1475 Unblock pending builds with allow_failure=true
  .gitlab-ci.yml
Labels: no release notes

#1468 JMX implementation of Profiling Session
  dd-java-agent/agent-profiling/profiling-controller/profiling-controller.gradle
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/JFRStackTraceSink.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/JMXSampler.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/JMXSession.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/JMXSessionFactory.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/SamplerWriter.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/mlt/StackTraceSink.java
  dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/mlt/JMXSamplerTest.java
  dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/mlt/JMXSessionTest.java
  dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
  internal-api/src/main/java/datadog/trace/profiling/Profiler.java
  internal-api/src/main/java/datadog/trace/profiling/SessionFactory.java
Labels: do-not-merge/WIP

#1501 Cache UTF-8 encoding of even more constants
  dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/FormatWriter.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/CommonTagValues.java
Labels: no release notes

#1494 Use Retry.Mode.SETUP_FEATURE_CLEANUP to improve Elasticsearch test flakiness
  dd-java-agent/instrumentation/elasticsearch/rest-5/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/rest-5/src/test/groovy/Elasticsearch5RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/latestDepTest/groovy/Elasticsearch6RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/rest-6.4/src/test/groovy/Elasticsearch6RestClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
  gradle/java.gradle
Labels: no release notes
