Repository DataDog/dd-trace-java, pull requests merged in 2020-12, with the labels that each got.

#2139 Remove unused GenericRunnable
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/GenericRunnable.java
Labels: no release notes, refactoring

#2137 improve string handling
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
  dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientDecorator.java
Labels: no release notes

#2143 avoid excessive thread creation when trace agent is down
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
Labels: bug

#2144 remove excessive debug logging in ContinuableScopeManager
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
Labels: no release notes

#2147 Fix CassandraClientTest flakiness
  dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
Labels: no release notes

#2148 remove busyspin backoff logic in flaky DDAgentWriterCombinedTest
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
Labels: dev/testing, no release notes

#2142 Select low and high version in every range for Muzzle
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  buildSrc/src/main/groovy/VersionSet.groovy
  buildSrc/src/test/groovy/VersionSetTest.groovy
Labels: dev/testing, no release notes

#2149 remove superseded non-LTS OpenJDK test jobs
  .circleci/config.yml
Labels: dev/testing, no release notes

#2150 increase relative accuracy
  utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
Labels: no release notes

#2132 remove entry from context store in servlet instrumentation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
  dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletResponseTest.groovy
Labels: bug, efficiency

#2152 [CIAPP] Remove ci.job.url from Jenkins CI information.
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/JenkinsInfo.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/JenkinsInfoTest.groovy
Labels: no release notes

#2158 Limit muzzle for jax-rs annotation for Jersey
  dd-java-agent/instrumentation/jax-rs-annotations-2/filter-jersey/filter-jersey.gradle
Labels: dev/testing, no release notes

#2156 Datastax Cassandra 4 instrumentation
  dd-java-agent/instrumentation/datastax-cassandra-4/datastax-cassandra-4.gradle
  dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java/datadog/trace/instrumentation/datastax/cassandra4/CassandraClientInstrumentation.java
  dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java8/datadog/trace/instrumentation/datastax/cassandra4/CassandraClientAdvice.java
  dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java8/datadog/trace/instrumentation/datastax/cassandra4/CassandraClientDecorator.java
  dd-java-agent/instrumentation/datastax-cassandra-4/src/main/java8/datadog/trace/instrumentation/datastax/cassandra4/TracingSession.java
  dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy
  settings.gradle
Labels: integrations

#2160 Cleanup muzzle (bytebuddy) plugin
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
Labels: no release notes

#2163 Add some more java agent logging tests and information in StatusLogger
  dd-java-agent/agent-logging/agent-logging.gradle
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/LoggerHelperFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/DDLoggerFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/ddlogger/SwitchableLogLevelFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatFactory.java
  dd-java-agent/agent-logging/src/main/java/datadog/trace/logging/simplelogger/SLCompatSettings.java
  dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/ddlogger/DDLoggerTest.groovy
  dd-java-agent/agent-logging/src/test/groovy/datadog/trace/logging/simplelogger/SLCompatHelperTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/logging/LoggingSettingsDescription.java
Labels: no release notes

#2167 Remove unused analyticsSampleRate in CoreSpanBuilder
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
Labels: no release notes

#2175 Muzzle updates to reflect recent servlet 5 releases
  dd-java-agent/instrumentation/jetty-8/jetty-8.gradle
  dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle
  dd-java-agent/instrumentation/vertx-web-3.4/vertx-web-3.4.gradle
Labels: dev/testing, no release notes

#2176 Don't check total count of request handlers in AmazonWebServiceClient
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy
Labels: no release notes

#2184 remove protobuf writer
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/core/serialization/protobuf/ProtobufWriter.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/protobuf/CompactRepeatedFieldHelper.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/protobuf/IntPackingTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/protobuf/ProtobufWriterTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/protobuf/SmokeTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/protobuf/StringWritingTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/protobuf/VerifyThatProtobufFormatterDoesNotThrowInvalidMarkException.java
Labels: no release notes

#2180 Audit and cleanup ScopeManagerTest
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Labels: no release notes

#2181 Remove unnecessary field and nesting in PendingTrace
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Labels: no release notes

#2189 Set -XX:ErrorFile everywhere for JVM crashes
  .circleci/config.yml
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
  dd-smoke-tests/slf4j-mdc/src/test/groovy/datadog/smoketest/Slf4jMDCSmokeTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
Labels: no release notes

#2190 Fix Jacoco test coverage verification failing because of cache
  gradle/jacoco.gradle
Labels: no release notes

#2202 Fix NoClassDefFoundError with DDSpecification
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/CallDepthThreadLocalMapTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/ExcludeFilterTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakCacheTest.groovy
  dd-java-agent/testing/src/test/groovy/utils/ThreadUtilsTest.groovy
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ExcludedVersionsTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/MultiWriterTest.groovy
  utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
Labels: no release notes

#2206 Remove `HttpServletResponse` InstrumentationContext
  dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
  dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Instrumentation.java
  dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
  dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Instrumentation.java
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletResponseInstrumentation.java
Labels: no release notes

#2214 remove some intrusive tests
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
Labels: dev/testing, no release notes

#2211 Remove HttpServerTestAdvice.ServerEntryAdvice
  dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpTestInstrumentation.java
  dd-java-agent/instrumentation/dropwizard/src/test/groovy/DropwizardAsyncTest.groovy
  dd-java-agent/instrumentation/dropwizard/src/test/groovy/JettyTestInstrumentation.java
  dd-java-agent/instrumentation/finatra-2.9/src/latestDepTest/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/finatra-2.9/src/test/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/glassfish/src/test/groovy/GrizzlyTestInstrumentation.java
  dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyAsyncTest.groovy
  dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyTestInstrumentation.java
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyAsyncTest.groovy
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyFilterchainServerTest.groovy
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyFilterchainServerTestInstrumentation.java
  dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/groovy/JettyTestInstrumentation.java
  dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyContinuationHandlerTest.groovy
  dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
  dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyTestInstrumentation.java
  dd-java-agent/instrumentation/netty-3.8/src/latestDepTest/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/netty-3.8/src/test/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/netty-4.0/src/test/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/netty-4.1/src/test/groovy/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/play-2.3/src/test/groovy/server/PlayServerTest.groovy
  dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayServerTest.groovy
  dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackAsyncHttpServerTest.groovy
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackForkedHttpServerTest.groovy
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackHttpServerTest.groovy
  dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/ServletTestInstrumentation.java
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServletHandlerTest.groovy
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/ServletTestInstrumentation.java
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
  dd-java-agent/instrumentation/spring-cloud-zuul-2/src/test/groovy/ServletTestInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/ServletTestInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/NettyServerTestInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTestAdvice.java
Labels: dev/testing, no release notes

#2224 Skip muzzle for broken OpenTelemetry 0.13.0 release
  dd-java-agent/instrumentation/opentelemetry/opentelemetry.gradle
Labels: no release notes

#2232 Allow disabling Status404Rule leaving URLAsResourceNameRule enabled
  dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/URLAsResourceNameRule.java
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy
Labels: community

#2235 AgentTestRunner refactor and cleanup
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RecursiveThreadPoolPropagationTest.groovy
  dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/groovy/JaxRsAnnotations1InstrumentationTest.groovy
  dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/JaxRsAnnotations2InstrumentationTest.groovy
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationForwardTests.groovy
  dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPTestBase.groovy
  dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
  dd-java-agent/instrumentation/scala-concurrent/src/latestDepTest/scala/ScalaConcurrentTests.scala
  dd-java-agent/instrumentation/scala-concurrent/src/slickTest/groovy/SlickTest.groovy
  dd-java-agent/instrumentation/scala-concurrent/src/slickTest/scala/SlickUtils.scala
  dd-java-agent/instrumentation/scala-concurrent/src/test/scala/ScalaConcurrentTests.scala
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/WithHttpServer.groovy
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
  dd-java-agent/testing/src/test/groovy/TraceCorrelationTest.groovy
  dd-java-agent/testing/src/test/groovy/context/FieldBackedProviderTest.groovy
  dd-java-agent/testing/src/test/groovy/locator/ClassInjectingLoadClassDisabledForkedTest.groovy
  dd-java-agent/testing/src/test/groovy/utils/ThreadUtilsTest.groovy
  dd-java-agent/testing/testing.gradle
  dd-trace-api/src/main/java/datadog/trace/api/GlobalTracer.java
  internal-api/src/main/java/datadog/trace/api/WithGlobalTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: dev/testing, no release notes
