Repository DataDog/dd-trace-java, pull requests merged in 2020-10, with the labels that each got.

#1942 Add file size limit to agent jar
  dd-java-agent/dd-java-agent.gradle
Labels: no release notes

#1940 Added CI/Git information to test spans for CI providers
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/AppVeyorInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/AzurePipelinesInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/BitBucketInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/BuildkiteInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/CIProviderInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/CircleCIInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/GitLabInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/GithubActionsInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/JenkinsInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/NoopCIInfo.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/TravisInfo.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/AppVeyorInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/AzurePipelinesInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/BitBucketInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/BuildkiteInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/CIProviderInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/CircleCIInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/GitLabInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/GithubActionsInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/JenkinsInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/NoopCIInfoTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/TravisInfoTest.groovy
  dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
  dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
  dd-java-agent/instrumentation/testng-6.4/src/test/groovy/TestNGTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Labels: no release notes

#1954 Exclude otel 0.9.0 that started failing muzzle
  dd-java-agent/instrumentation/opentelemetry/opentelemetry.gradle
Labels: no release notes

#1949 Test published dependencies
  .circleci/config.yml
  CONTRIBUTING.md
  dd-trace-java.gradle
  gradle/java.gradle
  gradle/publish.gradle
  gradle/scm.gradle
  gradle/spotless.gradle
  gradle/util.gradle
  gradle/version.gradle
  test-published-dependencies/.gitignore
  test-published-dependencies/build.gradle
  test-published-dependencies/settings.gradle
  test-published-dependencies/src/main/java/test/published/dependencies/App.java
Labels: dev/testing, no release notes

#1938 Add workflow for Update Gradle Wrapper Action.
  .github/workflows/update-gradle-wrapper.yml
Labels: community, no release notes

#1953 Ci-App: Fix Azure Pipelines information for ci.pipeline.number
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/ci/AzurePipelinesInfo.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/ci/AzurePipelinesInfoTest.groovy
Labels: no release notes

#1924 Play 2.5 smoke tests with filters and actions
  dd-smoke-tests/play-2.5/app/Filters.java
  dd-smoke-tests/play-2.5/app/actions/AbstractAction.java
  dd-smoke-tests/play-2.5/app/actions/Action1.java
  dd-smoke-tests/play-2.5/app/actions/Action2.java
  dd-smoke-tests/play-2.5/app/controllers/HomeController.java
  dd-smoke-tests/play-2.5/app/filters/AbstractFilter.java
  dd-smoke-tests/play-2.5/app/filters/Filter1.java
  dd-smoke-tests/play-2.5/app/filters/Filter2.java
  dd-smoke-tests/play-2.5/app/filters/Filter3.java
  dd-smoke-tests/play-2.5/app/filters/Filter4.java
  dd-smoke-tests/play-2.5/conf/application.conf
  dd-smoke-tests/play-2.5/conf/logback.xml
  dd-smoke-tests/play-2.5/conf/routes
  dd-smoke-tests/play-2.5/play-2.5.gradle
  dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/app/controllers/HomeController.scala
  dd-smoke-tests/play-2.6/conf/application.conf
  dd-smoke-tests/play-2.6/conf/logback.xml
  dd-smoke-tests/play-2.6/conf/routes
  dd-smoke-tests/play-2.6/play-2.6.gradle
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlayAkkaSmokeTest.groovy
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncAnnotationTest.groovy
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncConcurrentTest.groovy
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcAsyncTest.groovy
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcCompletableFutureTest.groovy
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootGrpcSyncTest.groovy
  dd-smoke-tests/springboot-grpc/src/test/groovy/datadog/smoketest/SpringBootWithGRPCTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractServerSmokeTest.groovy
  dd-trace-core/src/main/java/datadog/trace/common/writer/TraceStructureWriter.java
  settings.gradle
Labels: no release notes

#1955 Write out a trace as soon as possible
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
Labels: no release notes

#1960 refactor FieldBackedProvider
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreImplementationTemplate.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreImplementationVisitor.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreReadsRewritingVisitor.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ContextStoreUtils.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldInjectionVisitor.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/SafeToInjectFieldsMatcher.java
Labels: no release notes

#1966 Remove verify defaults test
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: no release notes

#1963 Add a play client request to the play 2.5 smoke test
  dd-smoke-tests/play-2.5/app/controllers/HomeController.java
  dd-smoke-tests/play-2.5/play-2.5.gradle
  dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
  dd-trace-core/src/main/java/datadog/trace/common/writer/MultiWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/MultiWriterTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/WriterConstants.java
Labels: no release notes

#1969 test that flush will return when queue is full and worker is stopped
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceProcessingWorkerTest.groovy
Labels: dev/testing, no release notes

#1964 disable trace agent v0.5 by default
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
Labels: no release notes

#1971 Set missing async propagation on some java/scala/akka scopes
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/scala-concurrent/src/latestDepTest/groovy/ScalaInstrumentationTest.groovy
  dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
  dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
Labels: no release notes

#1979 Fix flaky netty executor instrumentation test
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/NettyExecutorInstrumentationTest.groovy
Labels: no release notes

#1982 Make sure FutureTask gets field injected
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
Labels: no release notes

#1974 Expanding smoke tests for Play 2.6
  dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/app/Filters.java
  dd-smoke-tests/play-2.6/app/actions/AbstractAction.java
  dd-smoke-tests/play-2.6/app/actions/Action1.java
  dd-smoke-tests/play-2.6/app/actions/Action2.java
  dd-smoke-tests/play-2.6/app/controllers/HomeController.java
  dd-smoke-tests/play-2.6/app/controllers/HomeController.scala
  dd-smoke-tests/play-2.6/app/filters/AbstractFilter.java
  dd-smoke-tests/play-2.6/app/filters/Filter1.java
  dd-smoke-tests/play-2.6/app/filters/Filter2.java
  dd-smoke-tests/play-2.6/app/filters/Filter3.java
  dd-smoke-tests/play-2.6/app/filters/Filter4.java
  dd-smoke-tests/play-2.6/conf/routes
  dd-smoke-tests/play-2.6/play-2.6.gradle
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlayAkkaSmokeTest.groovy
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
Labels: dev/testing, no release notes

#1988 don't double instrument RunnableFutures
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy
Labels: no release notes

#1986 Remove unnecessary and confusing isEnabled method on ExcludeFilterProvider
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExcludeFilterProvider.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/CompletableFutureUniCompletionInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
  dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
  dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterProviderTestInstrumentation.java
Labels: no release notes

#1984 Move kotlin testing outside java-concurrent
  dd-java-agent/instrumentation/kotlin-coroutines/kotlin-coroutines.gradle
  dd-java-agent/instrumentation/kotlin-coroutines/src/test/groovy/KotlinCoroutineInstrumentationTest.groovy
  dd-java-agent/instrumentation/kotlin-coroutines/src/test/kotlin/KotlinCoroutineTests.kt
  settings.gradle
Labels: no release notes

#1977 Instrument akka dispatchers without relying on Executor/Runnable instrumentations
  dd-java-agent/instrumentation/akka-concurrent/akka-concurrent.gradle
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinExecutorTaskInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinPoolInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/test/groovy/AkkaExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
Labels: no release notes

#1990 RejectedExecutionHandlerInstrumentation tests and fixes
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/java/ExecutingRejectedExecutionHandler.java
Labels: no release notes

#1993 Ensure ForkJoinTask is field-injected, add smoke test for field injection
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
  dd-smoke-tests/field-injection/field-injection.gradle
  dd-smoke-tests/field-injection/src/main/java/datadog/smoketest/fieldinjection/FieldInjectionApp.java
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
  settings.gradle
Labels: bug, dev/testing, efficiency

#1995 Add missing equals and hashCode method into datadog.trace.instrumentation.opentracing32.OTSpan
  dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
  dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
Labels: community

#1978 CI Provider info selector logic to internal-api
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/TestDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/TestDecoratorTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/AppVeyorInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/AzurePipelinesInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/BitBucketInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/BuildkiteInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/CIProviderInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/CircleCIInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/GitLabInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/GithubActionsInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/JenkinsInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/NoopCIInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/TravisInfo.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/AppVeyorInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/AzurePipelinesInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/BitBucketInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/BuildkiteInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/CIProviderInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/CircleCIInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/GitLabInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/GithubActionsInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/JenkinsInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/NoopCIInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/TravisInfoTest.groovy
Labels: no release notes

#1996 small improvements in play 2.6 instrumentation
  dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayHeaders.java
  dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java
Labels: efficiency

#2001 Ci-App: Remove /-/ in Gitlab Pipeline URL for tests
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/GitLabInfo.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/GitLabInfoTest.groovy
Labels: no release notes

#2002 more executor tests
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RejectedExecutionHandlerInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/CrossedContextTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/NettyExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RecursiveThreadPoolPropagationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/RejectedExecutionTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/java/Descendant.java
  dd-java-agent/instrumentation/java-concurrent/src/test/java/SwallowingRejectedExecutionHandler.java
Labels: dev/testing, no release notes

#2004 Reduce field injection footprint
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExcludeFilterProvider.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/CompletableFutureUniCompletionInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
  dd-java-agent/instrumentation/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/promise/CallbackRunnableInstrumentation.java
  dd-java-agent/instrumentation/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
  dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterProviderTestInstrumentation.java
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
Labels: efficiency

#2005 Rename agent thread group to 'dd-trace-java'
  internal-api/src/main/java/datadog/trace/util/DaemonThreadFactory.java
Labels: no release notes

#2006 Add failure handling for completableFuture in test
  dd-java-agent/instrumentation/apache-httpasyncclient-4/src/test/groovy/ApacheHttpAsyncClientCallbackTest.groovy
  dd-java-agent/instrumentation/vertx/src/test/groovy/client/VertxHttpClientTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
Labels: no release notes

#2003 Add Play 2.8 smoke test via sbt build
  .circleci/config.yml
  .gitignore
  dd-smoke-tests/play-2.8/application/app/Filters.java
  dd-smoke-tests/play-2.8/application/app/actions/AbstractAction.java
  dd-smoke-tests/play-2.8/application/app/actions/Action1.java
  dd-smoke-tests/play-2.8/application/app/actions/Action2.java
  dd-smoke-tests/play-2.8/application/app/actions/SAction.scala
  dd-smoke-tests/play-2.8/application/app/controllers/JController.java
  dd-smoke-tests/play-2.8/application/app/controllers/SController.scala
  dd-smoke-tests/play-2.8/application/app/filters/AbstractFilter.java
  dd-smoke-tests/play-2.8/application/app/filters/Filter1.java
  dd-smoke-tests/play-2.8/application/app/filters/Filter2.java
  dd-smoke-tests/play-2.8/application/app/filters/Filter3.java
  dd-smoke-tests/play-2.8/application/app/filters/Filter4.java
  dd-smoke-tests/play-2.8/application/build.sbt
  dd-smoke-tests/play-2.8/application/conf/application.conf
  dd-smoke-tests/play-2.8/application/conf/logback.xml
  dd-smoke-tests/play-2.8/application/conf/routes
  dd-smoke-tests/play-2.8/application/project/build.properties
  dd-smoke-tests/play-2.8/application/project/plugins.sbt
  dd-smoke-tests/play-2.8/application/sbt
  dd-smoke-tests/play-2.8/play-2.8.gradle
  dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/PlayAkkaSmokeTest.groovy
  dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
  settings.gradle
  tooling/sbt
Labels: dev/testing, no release notes

#2016 Add Play 2.7 smoke test via sbt build
  dd-smoke-tests/play-2.7/application/app/Filters.java
  dd-smoke-tests/play-2.7/application/app/actions/AbstractAction.java
  dd-smoke-tests/play-2.7/application/app/actions/Action1.java
  dd-smoke-tests/play-2.7/application/app/actions/Action2.java
  dd-smoke-tests/play-2.7/application/app/actions/SAction.scala
  dd-smoke-tests/play-2.7/application/app/controllers/JController.java
  dd-smoke-tests/play-2.7/application/app/controllers/SController.scala
  dd-smoke-tests/play-2.7/application/app/filters/AbstractFilter.java
  dd-smoke-tests/play-2.7/application/app/filters/Filter1.java
  dd-smoke-tests/play-2.7/application/app/filters/Filter2.java
  dd-smoke-tests/play-2.7/application/app/filters/Filter3.java
  dd-smoke-tests/play-2.7/application/app/filters/Filter4.java
  dd-smoke-tests/play-2.7/application/build.sbt
  dd-smoke-tests/play-2.7/application/conf/application.conf
  dd-smoke-tests/play-2.7/application/conf/logback.xml
  dd-smoke-tests/play-2.7/application/conf/routes
  dd-smoke-tests/play-2.7/application/project/build.properties
  dd-smoke-tests/play-2.7/application/project/plugins.sbt
  dd-smoke-tests/play-2.7/application/sbt
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/PlayAkkaSmokeTest.groovy
  dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/PlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/PlaySmokeTest.groovy
  settings.gradle
Labels: dev/testing, no release notes

#2014 Miscellaneous agent thread cleanup
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/util/ProfilingThreadFactory.java
  dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/util/ProfilingThreadFactoryTest.java
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
  dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
  dd-java-agent/instrumentation/datastax-cassandra-3/src/main/java/datadog/trace/instrumentation/datastax/cassandra/TracingSession.java
  dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
  internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
  internal-api/src/main/java/datadog/trace/util/DaemonThreadFactory.java
Labels: no release notes

#2020 Update Play root span only if there is one
  dd-java-agent/instrumentation/play-2.3/src/main/java8/datadog/trace/instrumentation/play23/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayAdvice.java
Labels: no release notes

#2026 Disable sbt based Play smoke tests since artifact download is flaky in CI
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.8/play-2.8.gradle
Labels: dev/testing, no release notes

#2023 Add internal testing option to exit JVM on advice failure
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ExceptionHandlers.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/BaseExceptionHandlerTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/DefaultInstrumenterForkedTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerExitOnFailureForkedTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ExceptionHandlerForkedTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  gradle/java.gradle
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: dev/testing, no release notes

#2013 Enable the normal build cache for muzzle on CI as a starting point
  .circleci/config.yml
Labels: dev/testing, no release notes

#2017 remove revapi
  .palantir/revapi.yml
  dd-trace-ot/dd-trace-ot.gradle
Labels: dev/tooling, no release notes

#2028 CI-App: Add test.arguments in Tags
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Labels: no release notes

#2029 Enable and change concurrent downloads on sbt based Play tests
  dd-smoke-tests/play-2.7/application/build.sbt
  dd-smoke-tests/play-2.7/application/project/build.properties
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.8/application/build.sbt
  dd-smoke-tests/play-2.8/application/project/build.properties
  dd-smoke-tests/play-2.8/play-2.8.gradle
Labels: dev/testing, no release notes

#2030 Update CircleCI caching
  .circleci/config.yml
  .gitignore
  dd-smoke-tests/play-2.7/application/build.sbt
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.8/application/build.sbt
  dd-smoke-tests/play-2.8/play-2.8.gradle
  settings.gradle
Labels: dev/testing, no release notes

#2034 Stage gradle based Play smoke tests during compilation
  dd-smoke-tests/play-2.4/play-2.4.gradle
  dd-smoke-tests/play-2.5/play-2.5.gradle
  dd-smoke-tests/play-2.6/play-2.6.gradle
Labels: dev/testing, no release notes

#2038 rework setting _dd.measured
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpClientInstrumentation.java
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java
  dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpAsyncClientInstrumentation.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
  dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientInstrumentation.java
  dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/TracingClientInterceptor.java
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
  dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
  dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java
  dd-java-agent/instrumentation/jax-rs-client-1.1/src/main/java/datadog/trace/instrumentation/jaxrs/v1/JaxRsClientV1Instrumentation.java
  dd-java-agent/instrumentation/jax-rs-client-2.0/src/main/java/datadog/trace/instrumentation/jaxrs/ClientTracingFilter.java
  dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
  dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/client/HttpClientRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/HttpServerRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/client/HttpClientRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client/HttpClientRequestTracingHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerRequestTracingHandler.java
  dd-java-agent/instrumentation/okhttp-2/src/main/java/datadog/trace/instrumentation/okhttp2/TracingInterceptor.java
  dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracingInterceptor.java
  dd-java-agent/instrumentation/play-2.3/src/main/java8/datadog/trace/instrumentation/play23/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.4/src/main/java8/datadog/trace/instrumentation/play24/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.6/src/main/java8/datadog/trace/instrumentation/play26/PlayAdvice.java
  dd-java-agent/instrumentation/play-ws-1/src/main/java/datadog/trace/instrumentation/playws1/PlayWSClientInstrumentation.java
  dd-java-agent/instrumentation/play-ws-2.1/src/main/java/datadog/trace/instrumentation/playws21/PlayWSClientInstrumentation.java
  dd-java-agent/instrumentation/play-ws-2/src/main/java/datadog/trace/instrumentation/playws2/PlayWSClientInstrumentation.java
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/TracedDelegatingConsumer.java
  dd-java-agent/instrumentation/ratpack-1.5/src/main/java8/datadog/trace/instrumentation/ratpack/TracingHandler.java
  dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
  dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/DispatcherHandlerAdvice.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/MetricsAssert.groovy
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanData.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/TraceProcessor.java
  dd-trace-core/src/main/java/datadog/trace/core/processor/rule/MarkSpanForMetricCalculationRule.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java
Labels: no release notes

#2033 Fail-fast on DDTracer.build when writer is null or DDAgentWriter
  dd-smoke-tests/opentracing/src/main/java/datadog/smoketest/opentracing/CorrectSetupWithAgentAndWriterApplication.java
  dd-smoke-tests/opentracing/src/test/groovy/datadog/smoketest/CorrectSetupWithAgentAndWriterTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
Labels: no release notes

#2039 Update test containers version
  gradle/dependencies.gradle
Labels: no release notes

#2042 Hibernate instrumentation no longer works with latest spring JPA
  dd-java-agent/instrumentation/hibernate/core-4.3/core-4.3.gradle
Labels: no release notes

#2031 Consistently use '[,]' to denote 'all versions' in muzzle…
  dd-java-agent/instrumentation/apache-httpclient-4/apache-httpclient-4.gradle
  dd-java-agent/instrumentation/couchbase-2.0/couchbase-2.0.gradle
  dd-java-agent/instrumentation/couchbase-2.6/couchbase-2.6.gradle
  dd-java-agent/instrumentation/dropwizard/dropwizard-views/dropwizard-views.gradle
  dd-java-agent/instrumentation/elasticsearch/rest-6.4/rest-6.4.gradle
  dd-java-agent/instrumentation/jms/jms.gradle
  dd-java-agent/instrumentation/log4j1/log4j1.gradle
  dd-java-agent/instrumentation/log4j2/log4j2.gradle
  dd-java-agent/instrumentation/servlet/request-3/request-3.gradle
  dd-java-agent/instrumentation/servlet/servlet.gradle
  dd-java-agent/instrumentation/slf4j-mdc/slf4j-mdc.gradle
Labels: dev/testing, no release notes

#2036 Drop mlt-support module
  settings.gradle
  utils/mlt-support/mlt-support.gradle
  utils/mlt-support/src/main/java/com/datadog/mlt/io/AbstractLEB128Writer.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/ConstantPool.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/FrameElement.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/FrameSequence.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/IMLTChunk.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128ByteArrayReader.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128ByteBufferWriter.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/LEB128Writer.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunk.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTChunkCollector.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTConstants.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTReader.java
  utils/mlt-support/src/main/java/com/datadog/mlt/io/MLTWriter.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/AbstractLEB128WriterTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/ConstantPoolTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameElementTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameSequenceBuilder.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/FrameSequenceTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/IMLTChunkTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/LEB128ByteArrayReaderTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/MLTChunkBuilder.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/MLTChunkTest.java
  utils/mlt-support/src/test/java/com/datadog/mlt/io/MLTSerializationTest.java
Labels: no release notes
