Repository DataDog/dd-trace-java, pull requests merged in 2021-05, with the labels that each got.

#2679 Lock Aerospike container since latest moved to version that doesn't start
  .circleci/config.yml
Labels: no release notes

#2673 Invert control when defining transformers
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVisitor.java
  dd-java-agent/instrumentation/rxjava-2/src/main/java/datadog/trace/instrumentation/rxjava2/ObservableInstrumentation.java
Labels: no release notes

#2672 Resolve port collisions for synapse-3 testing
  dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseServerTest.groovy
  dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/TestPassThroughHttpListener.groovy
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/repository/conf/axis2.xml
Labels: dev/testing, no release notes

#2681 match implementation class for some postgres drivers
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
Labels: bug, jdbc

#2658 Hazelcast Instrumentation
  dd-java-agent/instrumentation/hazelcast-3.6/hazelcast-3.6.gradle
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/DistributedObjectDecorator.java
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/DistributedObjectInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/HazelcastConstants.java
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/SpanFinishingExecutionCallback.java
  dd-java-agent/instrumentation/hazelcast-3.6/src/test/groovy/test/hazelcast/v3/AbstractHazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-3.6/src/test/groovy/test/hazelcast/v3/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-3.9/hazelcast-3.9.gradle
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientInvocationDecorator.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientMessageInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/HazelcastConstants.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/SpanFinishingExecutionCallback.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/test/groovy/test/hazelcast/v39/AbstractHazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-3.9/src/test/groovy/test/hazelcast/v39/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-4.0/hazelcast-4.0.gradle
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/ClientListenerInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java8/datadog/trace/instrumentation/hazelcast4/HazelcastConstants.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java8/datadog/trace/instrumentation/hazelcast4/HazelcastDecorator.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java8/datadog/trace/instrumentation/hazelcast4/InvocationAdvice.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java8/datadog/trace/instrumentation/hazelcast4/SpanFinishingExecutionCallback.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/AbstractHazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/SumTask.groovy
  dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java
  settings.gradle
Labels: community, integrations

#2683 Disable PeerServiceTagInterceptor by default
  dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/RuleFlags.java
  dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: breaking-change

#2684 Fix build from refactor/merge conflict
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/DistributedObjectInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientMessageInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/ClientListenerInstrumentation.java
Labels: no release notes

#2655 Use MethodHandles to access AWS Request metadata
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/OnErrorDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestAccess.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/test/groovy/AWS1ClientTest.groovy
Labels: aws-sdk, integrations

#2666 Onboarding improvements
  dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDClientManager.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/LoggingStatsDClient.java
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/Platform.java
  internal-api/src/main/java/datadog/trace/api/StatsDClientManager.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
Labels: enhancement

#2686 Discover StatsD port from trace agent /info endpoint
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDClientManager.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
Labels: enhancement

#2689 Add test for disabling route based naming
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/RouteHandlerDecoratorTest.groovy
Labels: no release notes

#2688 Don't create noop scopes for akka messaging unless necessary
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaActorCellInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaMailboxInstrumentation.java
Labels: performance

#2671 Fix assertion
  dd-java-agent/instrumentation/jetty-7.0/src/test/groovy/Jetty70Test.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Labels: dev/testing, no release notes

#2687 implement checkpoint API for profiler integration
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointEvent.java
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  internal-api/src/main/java/datadog/trace/api/Checkpointer.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/SamplingCheckpointer.java
  internal-api/src/main/java/datadog/trace/api/SpanCheckpointer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/test/groovy/datadog/trace/api/SamplingCheckpointerTest.groovy
Labels: profiling

#2695 make sure JFRCheckpointer does not load on JDKs which do not support JFR
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/SafeToLoadJFRCheckpointerTest.groovy
Labels: no release notes

#2694 add test + fix for old postgres driver
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractPreparedStatementInstrumentation.java
Labels: bug, jdbc

#2697 Log full stacktrace on transformation errors...
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
Labels: diagnostics, no release notes

#2698 CPU time improvements
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointEvent.java
  dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemAccessProvider.java
  dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
  internal-api/src/main/java/datadog/trace/api/Checkpointer.java
Labels: no release notes

#2702 Force the old version of postgres and run the tests
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
Labels: dev/testing, no release notes

#2701 Use IoLogger to log StatsD client errors
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
Labels: no release notes

#2706 disable recording CPU time on checkpoint events by default
  dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: no release notes

#2708 Remove sleep from HealthMetricsTest
  dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
Labels: dev/testing, flaky-test, no release notes

#2716 Disable some unnecessary tasks, make lazy, and optimize dependencies
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle
  dd-java-agent/agent-profiling/profiling-controller-oracle/profiling-controller-oracle.gradle
  dd-java-agent/benchmark/benchmark.gradle
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/akka-concurrent/akka-concurrent.gradle
  dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle
  dd-java-agent/instrumentation/datanucleus-4/datanucleus-4.gradle
  dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/jax-rs-annotations-2/jax-rs-annotations-2.gradle
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle
  dd-java-agent/instrumentation/liberty-20/liberty-20.gradle
  dd-java-agent/instrumentation/mongo/mongo.gradle
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-java-agent/instrumentation/netty-promise-4/netty-promise-4.gradle
  dd-java-agent/instrumentation/rmi/rmi.gradle
  dd-java-agent/instrumentation/scala-concurrent/scala-concurrent.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/scala-promise-2.10.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/scala-promise-2.13.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise.gradle
  dd-java-agent/instrumentation/slick/slick.gradle
  dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
  dd-java-agent/load-generator/load-generator.gradle
  dd-smoke-tests/cli/cli.gradle
  dd-smoke-tests/dd-smoke-tests.gradle
  dd-smoke-tests/field-injection/field-injection.gradle
  dd-smoke-tests/java9-modules/java9-modules.gradle
  dd-smoke-tests/log-injection/log-injection.gradle
  dd-smoke-tests/opentracing/opentracing.gradle
  dd-smoke-tests/osgi/osgi.gradle
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.8/play-2.8.gradle
  dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
  dd-smoke-tests/quarkus/quarkus.gradle
  dd-smoke-tests/spring-boot-2.4-webflux/spring-boot-2.4-webflux.gradle
  dd-smoke-tests/spring-boot-2.5-webflux/spring-boot-2.5-webflux.gradle
  dd-smoke-tests/springboot-grpc/springboot-grpc.gradle
  dd-smoke-tests/springboot-mongo/springboot-mongo.gradle
  dd-smoke-tests/springboot-openliberty/springboot-openliberty.gradle
  dd-smoke-tests/springboot/springboot.gradle
  dd-smoke-tests/wildfly/wildfly.gradle
  dd-trace-core/jfr-openjdk/jfr-openjdk.gradle
  dd-trace-java.gradle
  dd-trace-ot/dd-trace-ot.gradle
  gradle/dependencies.gradle
  gradle/jacoco.gradle
  gradle/java.gradle
  gradle/publish.gradle
  gradle/spotless.gradle
  gradle/test-with-kotlin.gradle
  gradle/test-with-scala.gradle
  gradle/version.gradle
Labels: dev/tooling, no release notes

#2720 Only save CircleCI cache once and use key prefix matching
  .circleci/config.yml
Labels: dev/testing, no release notes

#2710 Optimize circleci resource_class and run instrumentation tests as a separate task
  .circleci/config.yml
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-smoke-tests/dd-smoke-tests.gradle
  dd-smoke-tests/play-2.4/play-2.4.gradle
  dd-smoke-tests/play-2.5/play-2.5.gradle
  dd-smoke-tests/play-2.6/play-2.6.gradle
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.8/play-2.8.gradle
  dd-smoke-tests/quarkus/quarkus.gradle
  dd-smoke-tests/springboot-openliberty/springboot-openliberty.gradle
  dd-trace-java.gradle
Labels: dev/testing, no release notes

#2721 Add CI_PIPELINE_ID to Gitlab trigger
  .gitlab-ci.yml
Labels: dev/tooling, no release notes

#2723 Merge master into appsec
  .circleci/config.yml
  .gitlab-ci.yml
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle
  dd-java-agent/agent-profiling/profiling-controller-oracle/profiling-controller-oracle.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
  dd-java-agent/benchmark/benchmark.gradle
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/akka-concurrent/akka-concurrent.gradle
  dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle
  dd-java-agent/instrumentation/datanucleus-4/datanucleus-4.gradle
  dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/instrumentation/jax-rs-annotations-2/jax-rs-annotations-2.gradle
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle
  dd-java-agent/instrumentation/liberty-20/liberty-20.gradle
  dd-java-agent/instrumentation/mongo/mongo.gradle
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-java-agent/instrumentation/netty-promise-4/netty-promise-4.gradle
  dd-java-agent/instrumentation/rmi/rmi.gradle
  dd-java-agent/instrumentation/scala-concurrent/scala-concurrent.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/scala-promise-2.10.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/scala-promise-2.13.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise.gradle
  dd-java-agent/instrumentation/slick/slick.gradle
  dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
  dd-java-agent/load-generator/load-generator.gradle
  dd-smoke-tests/cli/cli.gradle
  dd-smoke-tests/dd-smoke-tests.gradle
  dd-smoke-tests/field-injection/field-injection.gradle
  dd-smoke-tests/java9-modules/java9-modules.gradle
  dd-smoke-tests/log-injection/log-injection.gradle
  dd-smoke-tests/opentracing/opentracing.gradle
  dd-smoke-tests/osgi/osgi.gradle
  dd-smoke-tests/play-2.4/play-2.4.gradle
  dd-smoke-tests/play-2.5/play-2.5.gradle
  dd-smoke-tests/play-2.6/play-2.6.gradle
  dd-smoke-tests/play-2.7/play-2.7.gradle
  dd-smoke-tests/play-2.8/play-2.8.gradle
  dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
  dd-smoke-tests/quarkus/quarkus.gradle
  dd-smoke-tests/spring-boot-2.4-webflux/spring-boot-2.4-webflux.gradle
  dd-smoke-tests/spring-boot-2.5-webflux/spring-boot-2.5-webflux.gradle
  dd-smoke-tests/springboot-grpc/springboot-grpc.gradle
  dd-smoke-tests/springboot-mongo/springboot-mongo.gradle
  dd-smoke-tests/springboot-openliberty/springboot-openliberty.gradle
  dd-smoke-tests/springboot/springboot.gradle
  dd-smoke-tests/wildfly/wildfly.gradle
  dd-trace-core/jfr-openjdk/jfr-openjdk.gradle
  dd-trace-java.gradle
  dd-trace-ot/dd-trace-ot.gradle
  gradle/dependencies.gradle
  gradle/jacoco.gradle
  gradle/java.gradle
  gradle/publish.gradle
  gradle/test-with-kotlin.gradle
  gradle/test-with-scala.gradle
  gradle/version.gradle
Labels: no release notes

#2726 spotless gradle plugin 5.12.5
  dd-smoke-tests/quarkus/application/build.gradle
  dd-trace-java.gradle
  gradle/spotless.gradle
  test-published-dependencies/build.gradle
Labels: dev/tooling, no release notes

#2553 Early filtering of transformation and re-transformation requests
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDClassFileTransformer.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDRediscoveryStrategy.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
  dd-java-agent/agent-tooling/src/main/java11/datadog/trace/agent/tooling/bytebuddy/DDJava9ClassFileTransformer.java
Labels: efficiency

#2728 Change settings for weekly CI build job
  .circleci/config.yml
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  dd-java-agent/instrumentation/netty-3.8/netty-3.8.gradle
  dd-java-agent/instrumentation/netty-4.0/netty-4.0.gradle
  dd-java-agent/instrumentation/netty-4.1/netty-4.1.gradle
Labels: dev/testing, no release notes

#2732 Remove spotlessXml since it keeps processing build artifacts
  gradle/spotless.gradle
Labels: dev/testing, no release notes

#2733 Create appsec subproject
  dd-java-agent/appsec/appsec.gradle
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
  settings.gradle
Labels: appsec, no release notes

#2730 Use simple job to do fan-in in on CircleCI
  .circleci/config.yml
Labels: dev/testing, no release notes

#2717 Make JMS listener and consumer instrumentation consistent, don't trace idle consumer polls
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy
  dd-java-agent/instrumentation/jms/jms.gradle
  dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/JMS2Test.groovy
  dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/SpringListenerJMS2Test.groovy
  dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/SpringTemplateJMS2Test.groovy
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/DatadogMessageListener.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageListenerInstrumentation.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInstrumentation.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java
  dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
  dd-java-agent/instrumentation/jms/src/test/groovy/SpringListenerJMS1Test.groovy
  dd-java-agent/instrumentation/jms/src/test/groovy/SpringTemplateJMS1Test.groovy
  dd-java-agent/instrumentation/spring-jms-3.1/src/main/java/datadog/trace/instrumentation/springjms/SpringSessionAwareMessageListener.java
  dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/SpringSAListenerTest.groovy
Labels: breaking-change

#2743 use NonBlockingHashMap in ConflatingMetricsAggregator
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
Labels: no release notes

#2747 Add CI step to upload junit xml results to Datadog
  .circleci/config.yml
Labels: no release notes

#2748 [AppSec] merge master into project/appsec
  .circleci/config.yml
  .github/CODEOWNERS
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/SessionState.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/jms/SessionStateTest.groovy
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/OpenJdkControllerTest.java
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilingSystem.java
  dd-java-agent/agent-profiling/profiling-controller/src/test/java/com/datadog/profiling/controller/ProfilingSystemTest.java
  dd-java-agent/instrumentation/jms/jms.gradle
  dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/JMS2Test.groovy
  dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/SpringListenerJMS2Test.groovy
  dd-java-agent/instrumentation/jms/src/latestDepTest/groovy/SpringTemplateJMS2Test.groovy
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/DatadogMessageListener.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageListenerInstrumentation.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInstrumentation.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/SessionInstrumentation.java
  dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
  dd-java-agent/instrumentation/jms/src/test/groovy/SpringListenerJMS1Test.groovy
  dd-java-agent/instrumentation/jms/src/test/groovy/SpringTemplateJMS1Test.groovy
  dd-java-agent/instrumentation/spring-jms-3.1/src/main/java/datadog/trace/instrumentation/springjms/SpringSessionAwareMessageListener.java
  dd-java-agent/instrumentation/spring-jms-3.1/src/test/groovy/SpringSAListenerTest.groovy
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/RouteEvent.java
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  internal-api/src/main/java/datadog/trace/api/Checkpointer.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/SamplingCheckpointer.java
  internal-api/src/main/java/datadog/trace/api/SpanCheckpointer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/util/CollectionUtils.java
  internal-api/src/test/groovy/datadog/trace/api/SamplingCheckpointerTest.groovy
  internal-api/src/test/groovy/datadog/trace/util/CollectionUtilsTest.groovy
Labels: no release notes

#2752 try to find unwrapped connection info in wrapped delegates
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/test/WrappedConnection.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/test/WrappedStatement.groovy
Labels: jdbc

#2755 Fix latestDepTest for SpringAmqpTest
  .circleci/config.yml
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/AbstractMessageListenerContainerInstrumentation.java
Labels: dev/testing, no release notes

#2762 Enable build failure on forbidden api usage
  dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/JfrMBeanHelper.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/axway-api/src/main/java/datadog/trace/instrumentation/axway/AxwayHTTPPluginDecorator.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/RouteOnSuccessOrError.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/MultiWriter.java
  gradle/forbiddenapis.gradle
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/GitUtils.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/LocalFSGitInfoExtractor.java
Labels: dev/testing, no release notes

#2764 Minimal Instrumentation Gateway API and test
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/api/function/BiConsumer.java
  internal-api/src/main/java/datadog/trace/api/function/BiFunction.java
  internal-api/src/main/java/datadog/trace/api/function/Supplier.java
  internal-api/src/main/java/datadog/trace/api/function/TriConsumer.java
  internal-api/src/main/java/datadog/trace/api/gateway/CallbackProvider.java
  internal-api/src/main/java/datadog/trace/api/gateway/EventType.java
  internal-api/src/main/java/datadog/trace/api/gateway/Events.java
  internal-api/src/main/java/datadog/trace/api/gateway/Flow.java
  internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
  internal-api/src/main/java/datadog/trace/api/gateway/RequestContext.java
  internal-api/src/main/java/datadog/trace/api/gateway/Subscription.java
  internal-api/src/main/java/datadog/trace/api/gateway/SubscriptionService.java
  internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Labels: appsec, no release notes

#2766 [AppSec] Merge master into project/appsec
  .circleci/config.yml
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
  dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/JfrMBeanHelper.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/axway-api/src/main/java/datadog/trace/instrumentation/axway/AxwayHTTPPluginDecorator.java
  dd-java-agent/instrumentation/glassfish/glassfish.gradle
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/test/WrappedConnection.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/test/WrappedStatement.groovy
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/AbstractMessageListenerContainerInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/RouteOnSuccessOrError.java
  dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatServerInstrumentation.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/MultiWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscoveryTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  gradle/forbiddenapis.gradle
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/GitUtils.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/LocalFSGitInfoExtractor.java
Labels: appsec, no release notes

#2768 Don't wrap runnables in ScheduledThreadPoolExecutor.execute
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/ThreadPoolExecutorInstrumentation.java
Labels: no release notes
