Repository DataDog/dd-trace-java, pull requests merged in 2021-02, with the labels that each got.

#2351 Make strict trace writing the default for core and instrumentation tests
  dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
  dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringRepositoryTest.groovy
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-3/src/test/groovy/CassandraClientTest.groovy
  dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy
  dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/ProcedureCallTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
  dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/groovy/CompletableFutureTest.groovy
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ReactiveClientTest.groovy
  dd-java-agent/instrumentation/netty-4.1/src/test/groovy/ReactorNettyTest.groovy
  dd-java-agent/instrumentation/okhttp-2/src/test/groovy/OkHttp2AsyncTest.groovy
  dd-java-agent/instrumentation/okhttp-2/src/test/groovy/OkHttp2Test.groovy
  dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3AsyncTest.groovy
  dd-java-agent/instrumentation/okhttp-3/src/test/groovy/OkHttp3Test.groovy
  dd-java-agent/instrumentation/reactor-core-3.1/src/test/groovy/ReactorCoreTest.groovy
  dd-java-agent/instrumentation/rxjava-2/src/test/groovy/RxJava2Test.groovy
  dd-java-agent/instrumentation/scala-concurrent/src/latestDepTest/groovy/ScalaInstrumentationTest.groovy
  dd-java-agent/instrumentation/scala-concurrent/src/test/groovy/ScalaInstrumentationTest.groovy
  dd-java-agent/instrumentation/scala-promise/src/test/groovy/ScalaUnitPromiseTestBase.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/dd/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientBase.groovy
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/dynamic/DynamicRoutingTest.groovy
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/filter/ServletFilterTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/AbstractPromiseTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceStrictWriteTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy
Labels: dev/testing, no release notes

#2358 Limit yields during pending trace flush in test
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
Labels: dev/testing, no release notes

#2356 Avoid span.isError() boxing
  dd-java-agent/instrumentation/opentelemetry/src/main/java/datadog/trace/instrumentation/opentelemetry/OtelSpan.java
  dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTSpan.java
  dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTSpan.java
  dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-ot/src/main/java/datadog/opentracing/OTSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: breaking-change

#2360 Limit heap and concurrency for the generated forkedTest tasks
  gradle/java.gradle
Labels: dev/testing, no release notes

#2359 add jdbc tests for mysql and postgresql
  .circleci/config.yml
  dd-java-agent/instrumentation/jdbc/jdbc.gradle
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
Labels: dev/testing, no release notes

#2365 Allocate fewer transient objects in StreamingSamplerTest
  dd-java-agent/instrumentation/exception-profiling/src/test/java/com/datadog/profiling/exceptions/StreamingSamplerTest.java
Labels: dev/testing, no release notes

#2367 Use exclude filter for tasks to benefit from caching
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java
  dd-java-agent/instrumentation/aerospike-4/src/main/java/datadog/trace/instrumentation/aerospike4/NioEventLoopInstrumentation.java
Labels: performance

#2373 update byte-buddy to 1.10.20
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
  gradle/dependencies.gradle
Labels: no release notes

#2371 Make test socket timeouts longer
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Labels: dev/testing, no release notes

#2370 Remove stale reference to CallableWrapper which was removed in #1973
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
Labels: no release notes

#2377 Try to fix a flaky test
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
Labels: flaky-test, no release notes

#2379 remove THREAD_PREFIX id generation strategy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
  dd-trace-api/src/main/java/datadog/trace/api/IdGenerationStrategy.java
Labels: dev/testing, no release notes

#2368 Add smoke tests for log injection
  dd-smoke-tests/log-injection/log-injection.gradle
  dd-smoke-tests/log-injection/src/logging/resources/log4j.xml
  dd-smoke-tests/log-injection/src/logging/resources/log4j2.xml
  dd-smoke-tests/log-injection/src/logging/resources/logback.xml
  dd-smoke-tests/log-injection/src/logging/resources/logging.properties
  dd-smoke-tests/log-injection/src/logging/resources/simplelogger.properties
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/BaseApplication.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/FloggerInterface.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/JBossInterface.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/JCLInterface.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/JULInterface.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/Log4j1Interface.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/Log4j2Interface.java
  dd-smoke-tests/log-injection/src/main/java/datadog/smoketest/loginjection/Slf4jInterface.java
  dd-smoke-tests/log-injection/src/test/groovy/datadog/smoketest/LogInjectionSmokeTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
  settings.gradle
Labels: dev/testing, no release notes

#2382 Remove unused JMX methods
  dd-trace-core/src/main/java/datadog/trace/core/util/JmxSystemAccessProvider.java
  dd-trace-core/src/main/java/datadog/trace/core/util/NoneSystemAccessProvider.java
  dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccess.java
  dd-trace-core/src/main/java/datadog/trace/core/util/SystemAccessProvider.java
  dd-trace-core/src/test/groovy/datadog/trace/core/util/SystemAccessTest.groovy
Labels: no release notes

#2381 Prefer static imports instead of copying the constant
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecoratorTest.groovy
  dd-java-agent/instrumentation/exception-profiling/src/test/java/com/datadog/profiling/exceptions/ExceptionHistogramTest.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: breaking-change

#2378 Move exception-profiling helper classes to agent-bootstrap
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionCountEvent.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionHistogram.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionProfiling.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionSampleEvent.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionSampler.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/StreamingSampler.java
  dd-java-agent/instrumentation/exception-profiling/src/main/java/datadog/exceptions/instrumentation/ThrowableInstrumentation.java
  dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java
  dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdviceHelper.java
  dd-java-agent/instrumentation/exception-profiling/src/test/java/datadog/exceptions/instrumentation/ThrowableInstanceAdviceHelperTest.java
  dd-java-agent/instrumentation/exception-profiling/src/test/java/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionHistogramTest.java
  dd-java-agent/instrumentation/exception-profiling/src/test/java/datadog/trace/bootstrap/instrumentation/exceptions/StreamingSamplerTest.java
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
  dd-smoke-tests/agent-isolation/src/test/groovy/datadog/smoketest/AgentIsolationSmokeTest.groovy
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionLegacySmokeTest.groovy
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
Labels: no release notes

#2385 Update Gradle to 6.8.2
  gradle/wrapper/gradle-wrapper.properties
Labels: gradle-wrapper, no release notes

#2387 remove test which targets a blocked port at google.com
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Labels: no release notes

#2386 Avoid concurrent modification exception in tests
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/ListWriterAssert.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TraceAssert.groovy
Labels: dev/testing, no release notes

#2390 Don't spin wait for test FinatraServer to start
  dd-java-agent/instrumentation/finatra-2.9/src/test/groovy/FinatraServerTest.groovy
  dd-java-agent/instrumentation/finatra-2.9/src/test/scala/FinatraServer.scala
Labels: dev/testing, flaky-test, no release notes

#2393 do not transform CHM internal fork join tasks
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/JavaForkJoinTaskInstrumentation.java
Labels: no release notes

#2396 remove StringTables
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_4.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceMapperV0_5.java
  dd-trace-core/src/main/java/datadog/trace/core/StringTables.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/Codec.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/EncodingCachingStrategies.java
  dd-trace-core/src/test/groovy/datadog/trace/core/StringTablesTest.groovy
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/IntPackingTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/MsgPackWriterTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/SmokeTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/StringWritingTest.java
Labels: no release notes

#2400 exclude elasticsearch 7.11.0 as it has unpublished dependencies
  dd-java-agent/instrumentation/elasticsearch/rest-5/rest-5.gradle
  dd-java-agent/instrumentation/elasticsearch/rest-6.4/rest-6.4.gradle
  dd-java-agent/instrumentation/elasticsearch/rest-7/rest-7.gradle
  dd-java-agent/instrumentation/elasticsearch/transport-2/transport-2.gradle
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/transport-5.3.gradle
  dd-java-agent/instrumentation/elasticsearch/transport-5/transport-5.gradle
  dd-java-agent/instrumentation/elasticsearch/transport-6/transport-6.gradle
  dd-java-agent/instrumentation/elasticsearch/transport-7.3/transport-7.3.gradle
Labels: no release notes

#2406 Update JMXFetchTest to test a real process rather than use flaky reflection hacks
  dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/src/test/java/jvmbootstraptest/JmxStartedChecker.java
Labels: no release notes

#2410 jdbc tweaks
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
  internal-api/src/main/java/datadog/trace/api/normalize/SQLNormalizer.java
Labels: no release notes

#2409 Fix potential timing issue involving CustomLogManagerTest
  dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
Labels: no release notes

#2417 Apply SpotBugs settings to all the test sets
  gradle/spotbugs.gradle
Labels: dev/testing, no release notes

#2420 Fix milestone workflow
  .github/workflows/add-milestone-to-pull-requests.yaml
Labels: no release notes

#2423 fix bug in SQL string replacement
  internal-api/src/main/java/datadog/trace/api/normalize/SQLNormalizer.java
  internal-api/src/test/groovy/datadog/trace/api/normalize/SQLNormalizerTest.groovy
Labels: bug

#2424 aggregator bugs
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/GrowableBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/GrowableBufferTest.java
Labels: no release notes

#2426 ensure disabling metrics also disables dropping
  dd-trace-core/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscovery.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/DDAgentFeaturesDiscoveryTest.groovy
  dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
  dd-trace-core/src/traceAgentTest/groovy/TraceMapperRealAgentTest.groovy
Labels: no release notes

#2427 upgrade DDSketch
  utils/histograms/histograms.gradle
  utils/histograms/src/test/groovy/DDSketchHistogramTest.groovy
Labels: dependencies

#2428 update bytebuddy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
  gradle/dependencies.gradle
Labels: dependencies

#2430 disable netty-promise instrumentation because webflux tests fail in strict mode when it is active
  dd-java-agent/instrumentation/netty-promise-4/src/main/java/datadog/trace/instrumentation/netty4/promise/NettyPromiseInstrumentation.java
  dd-java-agent/instrumentation/netty-promise-4/src/test/groovy/NettyProgressivePromiseTest.groovy
  dd-java-agent/instrumentation/netty-promise-4/src/test/groovy/NettyPromiseTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
Labels: bug

#2350 Axis2 + Synapse Instrumentation
  dd-java-agent/instrumentation/axis-2/axis-2.gradle
  dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/AxisEngineInstrumentation.java
  dd-java-agent/instrumentation/axis-2/src/main/java/datadog/trace/instrumentation/axis2/AxisMessageDecorator.java
  dd-java-agent/instrumentation/axis-2/src/test/groovy/datadog/trace/instrumentation/axis2/AxisEngineTest.groovy
  dd-java-agent/instrumentation/axis-2/src/test/java/datadog/trace/instrumentation/axis2/TestService.java
  dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerDecorator.java
  dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerInstrumentation.java
  dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseServerTest.groovy
  dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/TestPassThroughHttpListener.groovy
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/repository/conf/axis2.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/repository/conf/synapse.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/repository/services/SimpleStockQuoteService.aar
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/.gitignore
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/build.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/conf/services.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/src/samples/services/GetQuoteResponse.java
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/src/samples/services/SimpleStockQuoteService.java
  dd-java-agent/instrumentation/synapse-3/synapse-3.gradle
  dd-trace-api/src/main/java/datadog/trace/api/DDSpanTypes.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InternalSpanTypes.java
  settings.gradle
Labels: integrations

#2433 Fix bug where serialisation fails after trace too large to serialise
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/FlushingBuffer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/GrowableBuffer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/StreamingBuffer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MsgPackWriter.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV05PayloadTest.groovy
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/MsgPackWriterTest.java
Labels: bug

#2436 Change upgraded github actions from old API
  .github/workflows/draft-release-notes-on-tag.yaml
  .github/workflows/increment-milestones-on-tag.yaml
  .github/workflows/update-issues-on-release.yaml
Labels: no release notes

#2439 Add manual trigger to update issues on release action
  .github/workflows/update-issues-on-release.yaml
Labels: no release notes

#2443 When building with Java 9+ lazily set compiler `--release` flag to match target
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle
  dd-java-agent/instrumentation/rmi/rmi.gradle
  dd-java-agent/testing/testing.gradle
  dd-trace-core/jfr-openjdk/jfr-openjdk.gradle
  gradle/java.gradle
Labels: dev/tooling, no release notes

#2444 Output clear error when building profiling code without setting JAVA_11_HOME first
  dd-java-agent/agent-bootstrap/agent-bootstrap.gradle
  dd-java-agent/agent-profiling/profiling-controller-openjdk/profiling-controller-openjdk.gradle
  dd-java-agent/instrumentation/exception-profiling/exception-profiling.gradle
  dd-trace-core/jfr-openjdk/jfr-openjdk.gradle
Labels: dev/tooling, no release notes

#2448 emit debug log message when traces don't fit in the serialisation buffer
  dd-trace-core/src/main/java/datadog/trace/core/serialization/FlushingBuffer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/GrowableBuffer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/StreamingBuffer.java
  dd-trace-core/src/main/java/datadog/trace/core/serialization/msgpack/MsgPackWriter.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/FlushingBufferTest.java
  dd-trace-core/src/test/java/datadog/trace/core/serialization/msgpack/GrowableBufferTest.java
Labels: diagnostics, no release notes

#2447 Change github actions to use correct paginate syntax and new names
  .github/workflows/draft-release-notes-on-tag.yaml
  .github/workflows/increment-milestones-on-tag.yaml
  .github/workflows/update-issues-on-release.yaml
Labels: no release notes
