Repository DataDog/dd-trace-java, pull requests merged in 2021-01, with the labels that each got.

#2237 Small test changes to make tests more robust
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy
  dd-java-agent/testing/testing.gradle
  internal-api/src/test/groovy/datadog/trace/util/AgentTaskSchedulerTest.groovy
Labels: dev/testing, no release notes

#2242 Fix spotless execution for scala-promise 2.10 and 2.13
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/scala-promise-2.10.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/scala-promise-2.13.gradle
Labels: no release notes

#2243 Ensure visibility of test counter writes on another thread
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
Labels: dev/testing, no release notes

#2260 Move nested helper classes to top level, add smoke test for ApacheHttpClient classloader isolation
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogServerRequestResponseFlowWrapper.java
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogWrapperHelper.java
  dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/ApacheHttpAsyncClientInstrumentation.java
  dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/DelegatingRequestProducer.java
  dd-java-agent/instrumentation/apache-httpasyncclient-4/src/main/java/datadog/trace/instrumentation/apachehttpasyncclient/TraceContinuedFutureCallback.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/ApacheHttpClientInstrumentation.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/HelperMethods.java
  dd-java-agent/instrumentation/apache-httpclient-4/src/main/java/datadog/trace/instrumentation/apachehttpclient/WrappingStatusSettingResponseHandler.java
  dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraInstrumentation.java
  dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/Listener.java
  dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
  dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/SpanClosingListener.java
  dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/AbstractRequestContextInstrumentation.java
  dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/RequestFilterHelper.java
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/ChannelPipelineAdviceUtil.java
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/NettyChannelPipelineInstrumentation.java
  dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/OnCompleteHandler.java
  dd-java-agent/instrumentation/rediscala-1.8.0/src/main/java/datadog/trace/instrumentation/rediscala/RediscalaInstrumentation.java
  dd-java-agent/instrumentation/spring-data-1.8/src/main/java/datadog/trace/instrumentation/springdata/InterceptingRepositoryProxyPostProcessor.java
  dd-java-agent/instrumentation/spring-data-1.8/src/main/java/datadog/trace/instrumentation/springdata/RepositoryInterceptor.java
  dd-java-agent/instrumentation/spring-data-1.8/src/main/java/datadog/trace/instrumentation/springdata/SpringRepositoryInstrumentation.java
  dd-smoke-tests/agent-isolation/agent-isolation.gradle
  dd-smoke-tests/agent-isolation/src/main/java/datadog/smoketest/agentisolation/Agent.java
  dd-smoke-tests/agent-isolation/src/main/java/datadog/smoketest/agentisolation/App.java
  dd-smoke-tests/agent-isolation/src/test/groovy/datadog/smoketest/AgentIsolationSmokeTest.groovy
  settings.gradle
Labels: bug, core, integrations

#2262 Update CI Specs
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/AzurePipelinesInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/BitriseInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/CIProviderInfo.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/BitriseInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/CIProviderInfoTest.groovy
  internal-api/src/test/resources/ci/appveyor.json
  internal-api/src/test/resources/ci/azurepipelines.json
  internal-api/src/test/resources/ci/bitbucket.json
  internal-api/src/test/resources/ci/bitrise.json
  internal-api/src/test/resources/ci/buildkite.json
  internal-api/src/test/resources/ci/circleci.json
  internal-api/src/test/resources/ci/github.json
  internal-api/src/test/resources/ci/jenkins.json
  internal-api/src/test/resources/ci/travisci.json
Labels: no release notes

#2265 metrics performance
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AgentIntegrationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/UTF8BytesString.java
  utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
  utils/histograms/src/test/groovy/DDSketchHistogramTest.groovy
Labels: no release notes

#2267 validate metrics are deserializable and accurate after a round trip
  utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
  utils/histograms/src/test/groovy/DDSketchHistogramTest.groovy
Labels: no release notes

#2272 Ci-App: Clear all envvars before execute CIProviderInfo tests
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/api/ci/CIProviderInfoTest.groovy
Labels: no release notes

#2277 remove shared mutable state in RateLimitedLoggerTest
  internal-api/src/test/groovy/datadog/trace/api/RateLimitedLoggerTest.groovy
Labels: dev/testing, no release notes

#2280 Fix ddagentwriter combined test, fewer threads in PendingTraceTest
  dd-smoke-tests/profiling-integration-tests/src/test/groovy/datadog/smoketest/ProfilingIntegrationShutdownTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
  internal-api/src/test/groovy/datadog/trace/api/RateLimitedLoggerTest.groovy
Labels: dev/testing, no release notes

#2273 metrics performance
  dd-trace-core/src/main/java/datadog/trace/common/metrics/AggregateMetric.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricKey.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/AggregateMetricTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
Labels: no release notes

#2288 Avoid 5s pause for creation of unresolvable InetSocketAddress
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/BaseDecoratorTest.groovy
Labels: dev/testing, no release notes

#2287 Upgrade sbt and limit heap memory
  dd-smoke-tests/play-2.7/application/.sbtxopts
  dd-smoke-tests/play-2.7/application/project/build.properties
  dd-smoke-tests/play-2.7/application/sbt
  dd-smoke-tests/play-2.8/application/.sbtxopts
  dd-smoke-tests/play-2.8/application/project/build.properties
  tooling/.sbtxopts
  tooling/sbt
Labels: dev/testing, no release notes

#2286 shorten sleeps in servlet tests
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TestServlet3.groovy
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
Labels: dev/testing, no release notes

#2289 reduce time spent in cassandra 4 client test by reusing the (readonly) database prerequisites
  dd-java-agent/instrumentation/datastax-cassandra-4/src/test/groovy/CassandraClientTest.groovy
Labels: dev/testing, no release notes

#2213 Cleanup threads and call CoreTracer.close() in all tests
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/TraceProcessingWorker.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/ForcePrioritySamplerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RateByServiceSamplerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RuleBasedSamplingTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceMapperTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/SpanFactory.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/TraceCorrelationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/URLAsResourceNameRuleTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
  dd-trace-core/src/traceAgentTest/groovy/DDApiIntegrationTest.groovy
  dd-trace-ot/src/ot31CompatabilityTest/groovy/OT31ApiTest.groovy
  dd-trace-ot/src/ot33CompatabilityTest/groovy/OT33ApiTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDTracerAPITest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DDTracerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/DefaultLogHandlerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/SpanBuilderTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/resolver/DDTracerResolverTest.groovy
  internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
  utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
Labels: dev/testing, no release notes

#2275 update scala versions so we can build on JDK11
  dd-java-agent/instrumentation/scala-concurrent/scala-concurrent.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/scala-promise-2.10.gradle
Labels: no release notes

#2290 fix bug where first call to timesource produced negative timestamp and forbade logging
  internal-api/src/main/java/datadog/trace/api/RatelimitedLogger.java
  internal-api/src/test/groovy/datadog/trace/api/RateLimitedLoggerTest.groovy
Labels: bug

#2285 Add another gradle worker but use less memory
  .circleci/config.yml
  utils/test-utils/src/main/java/datadog/trace/test/util/ForkedTestUtils.java
Labels: no release notes

#2292 remove heavy debug logging
  dd-java-agent/instrumentation/jax-rs-client-2.0/src/main/java/datadog/trace/instrumentation/jaxrs/ClientTracingFeature.java
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
Labels: no release notes

#2294 Restrict maven groups from certain repositories
  gradle/repositories.gradle
Labels: no release notes

#2295 Don't fail JaxMultithreadedClientTest on ConnectException
  dd-java-agent/instrumentation/jax-rs-client-2.0/src/test/groovy/JaxMultithreadedClientTest.groovy
Labels: no release notes

#2282 CiApp: Remove deprecated CI tags
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ci/CIProviderInfo.java
  internal-api/src/test/resources/ci/appveyor.json
  internal-api/src/test/resources/ci/azurepipelines.json
  internal-api/src/test/resources/ci/bitbucket.json
  internal-api/src/test/resources/ci/bitrise.json
  internal-api/src/test/resources/ci/buildkite.json
  internal-api/src/test/resources/ci/circleci.json
  internal-api/src/test/resources/ci/github.json
  internal-api/src/test/resources/ci/gitlab.json
  internal-api/src/test/resources/ci/jenkins.json
  internal-api/src/test/resources/ci/travisci.json
Labels: no release notes

#2298 Add tests for akka-http 10.2 ServerBuilder
  dd-java-agent/instrumentation/akka-http-10.0/akka-http-10.0.gradle
  dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
  dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/scala/AkkaHttpTestWebServer.scala
  dd-java-agent/instrumentation/akka-http-10.0/src/latestDepTest/groovy/AkkaHttp102ServerInstrumentationTests.groovy
  dd-java-agent/instrumentation/akka-http-10.0/src/latestDepTest/scala/AkkaHttp102TestWebServer.scala
Labels: no release notes

#2266 Update misleading logging in ClassLoaderMatcher
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
Labels: no release notes

#2302 Make sure process is alive before all smoke tests
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
Labels: dev/testing, no release notes

#2305 Move RMI helper classes to agent-bootstrap
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ContextDispatcher.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ContextPayload.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/ContextPropagator.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/RmiClientDecorator.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/rmi/RmiServerDecorator.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/client/RmiClientInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/client/RmiClientContextInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/context/server/RmiServerContextInstrumentation.java
  dd-java-agent/instrumentation/rmi/src/main/java/datadog/trace/instrumentation/rmi/server/RmiServerInstrumentation.java
Labels: no release notes

#2307 PendingTrace strict writing mode for tests
  dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/test/groovy/CompletableFutureTest.groovy
  dd-java-agent/instrumentation/scala-promise/src/test/groovy/ScalaPromiseTestBase.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/AbstractPromiseTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceStrictWriteTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: dev/testing, no release notes

#2318 metrics tweaks
  dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
Labels: no release notes

#2319 Add support for Akka routers
  dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
  dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/scala/AkkaActors.scala
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaRoutedActorCellInstrumentation.java
Labels: no release notes

#2320 Block propagation in akka-http to Future that completes on shutdown
  dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpClientInstrumentationTest.groovy
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaPoolMasterActorInstrumentation.java
Labels: no release notes

#2322 revert to paginated store for DDSketch
  utils/histograms/src/main/java/datadog/trace/core/histogram/DDSketchHistogram.java
Labels: no release notes

#2323 DRYing initialization code in Mongo4ReactiveClientTest
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy
Labels: dev/testing, no release notes

#2324 expunge aggregates not updated within a reporting cycle
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Batch.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/NoOpMetricsAggregator.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
Labels: no release notes

#2331 Use NoOpStatsDClient when possible to speed up tests
  dd-trace-core/jfr-openjdk/src/test/groovy/datadog/trace/core/jfr/openjdk/ScopeEventTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/ForcePrioritySamplerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RateByServiceSamplerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RuleBasedSamplingTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/TraceMapperTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceStrictWriteTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceTestBase.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/TraceCorrelationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/TraceProcessorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/processor/URLAsResourceNameRuleTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerDepthTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/taginterceptor/TagInterceptorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/test/DDCoreSpecification.groovy
Labels: dev/testing, no release notes

#2329 Move PendingTraceBuffer flush to consumer thread and remove sleep
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Labels: no release notes

#2340 Revert "Move PendingTraceBuffer flush to consumer thread and remove sleep"
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Labels: no release notes

#2333 Update printing writer to output a Map<String, List<List<Span>>>>
  dd-trace-core/src/main/java/datadog/trace/common/writer/PrintingWriter.java
  dd-trace-core/src/test/groovy/datadog/trace/api/writer/PrintingWriterTest.groovy
Labels: bug, in-progress

#2341 Move PendingTraceBuffer flush to consumer thread
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Labels: dev/testing, no release notes

#2284 Add vertx path param test
  dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/server/VertxRxCircuitBreakerHttpServerTest.groovy
  dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/server/VertxRxHttpServerTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/VertxHttpServerTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxChainingTestServer.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/java/server/VertxTestServer.java
Labels: dev/testing, no release notes

#2343 Fix ordering issue in Scala promise test
  dd-java-agent/instrumentation/scala-promise/src/test/groovy/ScalaUnitPromiseTestBase.groovy
Labels: dev/testing, no release notes

#2346 close aggregator in FootprintTest
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
Labels: dev/testing, no release notes

#2347 Limit the number of concurrent smoke tests to 1
  dd-smoke-tests/dd-smoke-tests.gradle
Labels: dev/testing, no release notes

#2348 assert database and cache spans are top level when expected to be
  dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeBaseTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/test/groovy/Elasticsearch73NodeClientTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-7.3/src/test/groovy/Elasticsearch73TransportClientTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/CriteriaTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/QueryTest.groovy
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/groovy/SessionTest.groovy
  dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/CriteriaTest.groovy
  dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/QueryTest.groovy
  dd-java-agent/instrumentation/hibernate/core-4.0/src/test/groovy/SessionTest.groovy
  dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/ProcedureCallTest.groovy
  dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
  dd-java-agent/instrumentation/jedis-3.0/src/test/groovy/Jedis30ClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-4/src/test/groovy/Mongo4ReactiveClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
  dd-java-agent/instrumentation/rediscala-1.8.0/src/test/groovy/RediscalaClientTest.groovy
  dd-java-agent/instrumentation/spymemcached-2.12/src/test/groovy/datadog/trace/instrumentation/spymemcached/SpymemcachedTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/SpanAssert.groovy
Labels: dev/testing, no release notes

#2349 Ensure code coverage of ConflatingMetricsAggregator.ReportTask
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
Labels: dev/testing, no release notes

#2352 Limit heap and concurrency for the forkedTest task
  gradle/java.gradle
Labels: dev/testing, no release notes
