Repository DataDog/dd-trace-java, pull requests merged in 2021-11, with the labels that each got.

#3181 Enable tracing of SAP's HANA in-memory DB
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
Labels: integrations, jdbc

#3184 Enable instrumentation of synthetic methods
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/testing/src/test/groovy/synthetic/SyntheticForkedTest.groovy
  dd-java-agent/testing/src/test/java/synthetic/SyntheticTestInstrumentation.java
Labels: no release notes

#3186 Stop using regex in TraceConfig to avoid stack overflow
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy
Labels: bug

#3185 byte-buddy 1.12.0
  buildSrc/build.gradle.kts
  buildSrc/src/test/groovy/InstrumentPluginTest.groovy
  gradle/dependencies.gradle
Labels: dependencies

#3191 Update gitlab heap settings to match circleci
  .gitlab-ci.yml
Labels: dev/tooling, no release notes

#3192 Fork Java11 compiler for profiling-auxiliary-async
  dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
Labels: dev/tooling, no release notes

#3162 Allow gRPC users to ignore specific inbound RPC calls
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/server/TracingServerInterceptor.java
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/test/proto/helloworld.proto
  dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: enhancement, community, grpc

#3198 Clean up Scala promise instrumentation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/AdviceUtils.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ContinuationClaim.java
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/concurrent/CallbackRunnableInstrumentation.java
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseObjectInstrumentation210.java
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseObjectInstrumentation213.java
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/src/main/java/datadog/trace/instrumentation/scala/concurrent/PromiseTransformationInstrumentation.java
  dd-java-agent/instrumentation/scala-promise/src/main/java/datadog/trace/instrumentation/scala/PromiseHelper.java
  dd-java-agent/instrumentation/scala-promise/src/test/groovy/ScalaUnitPromiseTestBase.groovy
  dd-java-agent/instrumentation/scala-promise/src/test/scala/PromiseUtils.scala
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: no release notes

#3209 Limit spring-kafka version used in latestDepTest to 2.7.x
  dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
Labels: no release notes

#3215 Make axis-2 project stop complaining about pom relocation
  dd-java-agent/instrumentation/axis-2/axis-2.gradle
Labels: no release notes

#3205 [CIAPP] Agent configuration preset when CI Visibility is enabled
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
Labels: ciapp

#3199 [CIAPP] CI Visibility Mode v1
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
  dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
  dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGInstrumentation.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: ciapp

#3217 Reduce size of scope on stack when there's no continuation
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
Labels: performance

#3218 Store current scope separate to previous scope history
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
Labels: performance

#3220 Always send 64 bit floats due to decoding issue in Datadog agent
  communication/src/main/java/datadog/communication/serialization/msgpack/MsgPackWriter.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
  dd-trace-core/src/traceAgentTest/groovy/TraceGenerator.groovy
Labels: bug

#3221 Don't log that Oracle JDK 8 was found and try to start Profiler on JDK 7
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  internal-api/src/main/java/datadog/trace/api/Platform.java
  internal-api/src/test/groovy/datadog/trace/api/PlatformTest.groovy
Labels: no release notes

#3222 [CIAPP] Ensure both the tracer and instrumentations are installed if `dd.civisibility.enabled` is `true`
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
Labels: no release notes

#3223 [CIAPP] Avoid sending non-CIVisibility traces if `CIVisibility` mode is enabled.
  dd-trace-core/src/main/java/datadog/trace/civisibility/CiVisibilityTraceInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/test/groovy/datadog/trace/civisibility/CiVisibilityTraceInterceptorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
  dd-trace-core/src/test/java/datadog/trace/TestInterceptor.java
Labels: ciapp

#3224 [CIAPP] Remove CI App feature tracking JSON file
  .dd-ci/README.txt
  .dd-ci/ci-app-spec.json
Labels: no release notes, ciapp

#3225 [AppSec] Merge master into project/appsec-inband-poc
  .dd-ci/README.txt
  .dd-ci/ci-app-spec.json
  communication/src/main/java/datadog/communication/serialization/msgpack/MsgPackWriter.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
  dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/TracerInstaller.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/report/EventEnrichment.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/report/EventEnrichmentSpecification.groovy
  dd-java-agent/instrumentation/axis-2/axis-2.gradle
  dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4Instrumentation.java
  dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
  dd-java-agent/instrumentation/testng-6.4/src/main/java/datadog/trace/instrumentation/testng/TestNGInstrumentation.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/CiVisibilityConfig.java
  dd-trace-core/src/main/java/datadog/trace/civisibility/CiVisibilityTraceInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/civisibility/CiVisibilityTraceInterceptorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceGenerator.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/ddagent/TraceMapperV04PayloadTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/TraceInterceptorTest.groovy
  dd-trace-core/src/test/java/datadog/trace/TestInterceptor.java
  dd-trace-core/src/traceAgentTest/groovy/TraceGenerator.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/Platform.java
  internal-api/src/test/groovy/datadog/trace/api/PlatformTest.groovy
Labels: no release notes
