Repository DataDog/dd-trace-java, pull requests merged in 2021-12, with the labels that each got.

#3228 [AppSec] Check that all IG callbacks are called
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyDecorator.java
  dd-java-agent/instrumentation/jetty-7.0/src/main/java/datadog/trace/instrumentation/jetty70/JettyServerInstrumentation.java
  dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHelper.scala
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy
Labels: dev/testing, no release notes, appsec

#3233 Add span null check in GrizzlyDecorator
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyDecorator.java
Labels: no release notes

#3210 Add instrumentation for jakarta3
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/jakarta-rs-annotations-3.gradle
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/AbstractRequestContextInstrumentation.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/ContainerRequestFilterInstrumentation.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/DefaultRequestContextInstrumentation.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/JakartaRsAnnotationsDecorator.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/JakartaRsAnnotationsInstrumentation.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/JakartaRsAsyncResponseInstrumentation.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/RequestFilterHelper.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/test/groovy/JakartaRsAnnotations3InstrumentationTest.groovy
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/test/groovy/JakartaRsFilterTest.groovy
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/test/groovy/JavaInterfaces.java
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/test/java/Resource.java
  settings.gradle
Labels: integrations, community

#3194 Implement 'closePrevious' and 'activateNext' to help track potentially open-ended iterations
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/IterationSpansForkedTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
  dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java
  dd-trace-ot/src/test/groovy/datadog/opentracing/CustomScopeManagerTest.groovy
  dd-trace-ot/src/test/groovy/datadog/opentracing/IterationSpansForkedTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScope.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentScopeManager.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ScopeSource.java
Labels: enhancement, core

#3237 Fix 'Forwarded' header extraction
  dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
Labels: context-propagation

#3239 Reduce extracted cost when no forwarded data
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyByteBodyInstrumentationTest.groovy
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/test/groovy/GrizzlyCharBodyInstrumentationTest.groovy
  dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
  dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
  dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ForwardedExtractedContext.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ForwardedTagContext.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Labels: efficiency

#3242 Use AtomicLongFieldUpdater in DDSpan
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
Labels: efficiency

#3241 Remove unused 'samplingPriorityLocked' flag from ExtractedContext
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
Labels: no release notes

#3211 Add instrumentation for jetty 11
  dd-java-agent/instrumentation/jetty-11/jetty-11.gradle
  dd-java-agent/instrumentation/jetty-11/src/main/java/datadog/trace/instrumentation/jetty11/JettyServerInstrumentation.java
  dd-java-agent/instrumentation/jetty-11/src/main/java/datadog/trace/instrumentation/jetty11/RequestInstrumentation.java
  dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/JettyDecorator.java
  dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/JettyServerAdvice.java
  dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/RequestExtractAdapter.java
  dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/RequestURIDataAdapter.java
  dd-java-agent/instrumentation/jetty-11/src/main/java11/datadog/trace/instrumentation/jetty11/SetContextPathAdvice.java
  dd-java-agent/instrumentation/jetty-11/src/test/groovy/Jetty11Test.groovy
  gradle.properties
  settings.gradle
Labels: integrations

#3245 Don't instrument Runnables internal to ConcurrentLinkedHashMap
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
Labels: no release notes

#3247 Reduce size of emittingCheckpoints field from 4 bytes to 1 byte
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
Labels: no release notes, efficiency

#3253 Add PR template
  .github/pull_request_template.md
Labels: no release notes

#3254 Save space by only storing the start-time in DDSpan once and converting it as appropriate
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
Labels: performance, efficiency

#3268 Add v0.5 trace span decoder for testing
  dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy
  dd-smoke-tests/dd-smoke-tests.gradle
  dd-smoke-tests/opentracing/src/test/groovy/datadog/smoketest/OpenTracingSmokeTest.groovy
  dd-smoke-tests/spring-boot-2.4-webflux/src/test/groovy/datadog/smoketest/SpringBootWebfluxIntegrationTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
  gradle/java.gradle
  gradle/java_deps.gradle
  gradle/java_no_deps.gradle
  settings.gradle
  utils/test-agent-utils/decoder/decoder.gradle
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedMessage.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedSpan.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedTrace.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/Decoder.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/DictionaryV05.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/MessageV05.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/SpanV05.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/TraceV05.java
  utils/test-agent-utils/decoder/src/test/java/datadog/trace/test/agent/decoder/DecoderTest.java
  utils/test-agent-utils/decoder/src/test/resources/greeting.msgpack
Labels: dev/testing, no release notes

#3269 Upgrade gradle to 6.9.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dev/tooling, no release notes

#3270 [AppSec] Merge master into project/appsec-inband-poc
  .github/pull_request_template.md
  CONTRIBUTING.md
  dd-smoke-tests/cli/src/test/groovy/datadog/smoketest/CliApplicationSmokeTest.groovy
  dd-smoke-tests/dd-smoke-tests.gradle
  dd-smoke-tests/opentracing/src/test/groovy/datadog/smoketest/OpenTracingSmokeTest.groovy
  dd-smoke-tests/spring-boot-2.4-webflux/src/test/groovy/datadog/smoketest/SpringBootWebfluxIntegrationTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointSamplerConfigEvent.java
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/CheckpointSummaryEvent.java
  dd-trace-core/jfr-openjdk/src/main/java/datadog/trace/core/jfr/openjdk/JFRCheckpointer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  gradle/java.gradle
  gradle/java_deps.gradle
  gradle/java_no_deps.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  utils/test-agent-utils/decoder/decoder.gradle
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedMessage.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedSpan.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/DecodedTrace.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/Decoder.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/DictionaryV05.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/MessageV05.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/SpanV05.java
  utils/test-agent-utils/decoder/src/main/java/datadog/trace/test/agent/decoder/v05/raw/TraceV05.java
  utils/test-agent-utils/decoder/src/test/java/datadog/trace/test/agent/decoder/DecoderTest.java
  utils/test-agent-utils/decoder/src/test/resources/greeting.msgpack
Labels: no release notes

#3276 Upgrade JMXFetch to 0.44.5 even though we exclude log4j
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
Labels: bug

#3279 log4j1/LoggingEventInstrumentation: Inject correct value for dd.span_id
  dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
Labels: bug

#3280 [AppSec] Report multiple events per request
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
Labels: appsec

#3281 [AppSec] Report multiple events per request (legacy)
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
Labels: appsec

#3264 Memcached result tag: fixing typo
  dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/CompletionListener.java
Labels: bug, community

#3261 Replace end-to-end baggage implementation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
  dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
  dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
  dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ForwardedExtractedContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpInjectorTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: integrations, rabbitmq, kafka

#3284 [AppSec] Merge master into project/appsec-inband-poc
  .githooks/pre-commit
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-profiling/profiling-auxiliary-async/src/test/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfilerTest.java
  dd-java-agent/appsec/appsec.gradle
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfig.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
  dd-java-agent/appsec/src/main/resources/default_config.json
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/test/StubAppSecConfigService.groovy
  dd-java-agent/appsec/src/test/resources/test_multi_config.json
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AsyncPropagatingDisableInstrumentation.java
  dd-java-agent/instrumentation/junit-5.3/src/main/java/datadog/trace/instrumentation/junit5/JUnit5Instrumentation.java
  dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java
  dd-java-agent/instrumentation/mongo/driver-4.0/driver-4.0.gradle
  dd-java-agent/instrumentation/mongo/driver-4.0/readme.md
  dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/Arg0Advice.java
  dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/Arg1Advice.java
  dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/BaseClusterInstrumentation.java
  dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/CallbackWrapper.java
  dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/DefaultConnectionPoolInstrumentation.java
  dd-java-agent/instrumentation/mongo/driver-4.0/src/main/java/datadog/trace/instrumentation/mongo/InternalStreamConnectionInstrumentation.java
  dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/Mongo4ClientTest.groovy
  dd-java-agent/instrumentation/mongo/driver-4.0/src/test/groovy/MongoReactiveClientTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
  dd-trace-core/src/main/java/datadog/trace/common/sampling/RuleBasedSampler.java
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/RuleBasedSamplingTest.groovy
  gradle/codenarc.gradle
  settings.gradle
Labels: no release notes

#3285 [AppSec] Merge master into project/appsec-inband-poc
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
  dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
  dd-java-agent/instrumentation/opentelemetry/src/test/groovy/OpenTelemetryTest.groovy
  dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
  dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
  dd-java-agent/instrumentation/spymemcached-2.12/src/main/java/datadog/trace/instrumentation/spymemcached/CompletionListener.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ForwardedExtractedContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/XRayHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpInjectorTest.groovy
  dd-trace-ot/src/main/java/datadog/opentracing/CustomScopeManagerWrapper.java
  gradle/dependencies.gradle
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: no release notes

#3287 Use AgentSpan iteration API when consuming Kafka records.
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingListIterator.java
Labels: integrations, kafka

#3291 Close last record scope when iterator indicates there are no more records
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterator.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingListIterator.java
Labels: integrations, kafka
