Repository DataDog/dd-trace-java, pull requests merged in 2021-03, with the labels that each got.

#2452 Limit latest scalikejdbc_2.13 dependency to 3.+
  dd-java-agent/instrumentation/jdbc/scalikejdbc/scalikejdbc.gradle
Labels: no release notes

#2453 Widen catch block when attempting to install JFR ScopeEventFactory
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
Labels: no release notes

#2145 change JMS producers to use $ as replacement for -
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageExtractAdapter.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/MessageInjectAdapter.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: breaking-change

#2459 webflux client cleanup
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/SpringWebfluxHttpClientDecorator.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/TraceWebClientSubscriber.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/client/WebClientTracingFilter.java
Labels: no release notes

#2457 remove indirection in QualifiedClassNameCache
  internal-api/src/main/java/datadog/trace/api/cache/QualifiedClassNameCache.java
Labels: no release notes

#2221 Add failing tests for webflux based on spring-boot 2.4
  dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/SingleThreadedSpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/SpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/dd/trace/instrumentation/springwebflux/server/EchoHandler.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/dd/trace/instrumentation/springwebflux/server/EchoHandlerFunction.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/dd/trace/instrumentation/springwebflux/server/FooModel.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/dd/trace/instrumentation/springwebflux/server/SpringWebFluxTestApplication.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/groovy/dd/trace/instrumentation/springwebflux/server/TestController.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot20Test/java/dd/trace/instrumentation/springwebflux/server/RedirectComponent.java
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SingleThreadedSpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/SpringWebfluxTest.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/dd/trace/instrumentation/springwebflux/server/EchoHandler.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/dd/trace/instrumentation/springwebflux/server/EchoHandlerFunction.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/dd/trace/instrumentation/springwebflux/server/FooModel.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/dd/trace/instrumentation/springwebflux/server/SpringWebFluxTestApplication.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/groovy/dd/trace/instrumentation/springwebflux/server/TestController.groovy
  dd-java-agent/instrumentation/spring-webflux-5/src/boot24Test/java/dd/trace/instrumentation/springwebflux/server/RedirectComponent.java
Labels: no release notes

#2465 bump JCTools dependency
  dd-trace-core/dd-trace-core.gradle
Labels: dependencies

#2462 cache some strings and misc cleanup in webflux-server
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java/datadog/trace/instrumentation/springwebflux/server/AbstractWebfluxInstrumentation.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/AdviceUtils.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/DispatcherHandlerAdvice.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/HandlerAdapterAdvice.java
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/SpringWebfluxHttpServerDecorator.java
Labels: no release notes

#2471 Disable Spotbugs and ForbiddenAPIs for all test tasks
  gradle/forbiddenapis.gradle
  gradle/spotbugs.gradle
Labels: dev/testing, no release notes

#2438 Base Mule 4 instrumentation with HTTP Server Test
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-java-agent/instrumentation/mule-4/mule-application/.gitignore
  dd-java-agent/instrumentation/mule-4/mule-application/README.md
  dd-java-agent/instrumentation/mule-4/mule-application/mule-artifact.json
  dd-java-agent/instrumentation/mule-4/mule-application/pom.xml
  dd-java-agent/instrumentation/mule-4/mule-application/src/main/java/mule4/HttpServerTestHandler.java
  dd-java-agent/instrumentation/mule-4/mule-application/src/main/mule/mule-http-test-server.xml
  dd-java-agent/instrumentation/mule-4/mule-application/src/main/resources/application-types.xml
  dd-java-agent/instrumentation/mule-4/src/main/java/datadog/trace/instrumentation/mule4/EventContextInstrumentation.java
  dd-java-agent/instrumentation/mule-4/src/main/java/datadog/trace/instrumentation/mule4/PrivilegedEventInstrumentation.java
  dd-java-agent/instrumentation/mule-4/src/main/java8/datadog/trace/instrumentation/mule4/CurrentEventHelper.java
  dd-java-agent/instrumentation/mule-4/src/main/java8/datadog/trace/instrumentation/mule4/EventContextCreationAdvice.java
  dd-java-agent/instrumentation/mule-4/src/main/java8/datadog/trace/instrumentation/mule4/PrivilegedEventSetCurrentAdvice.java
  dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/HttpServerTestHandlerAdvice.java
  dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleHttpServerTest.groovy
  dd-java-agent/instrumentation/mule-4/src/test/groovy/org/mule/runtime/api/util/HttpServerTestBridge.groovy
  dd-java-agent/instrumentation/mule-4/src/test/java/mule4/HttpServerTestHandlerInstrumentation.java
  dd-java-agent/instrumentation/mule-4/src/test/java/mule4/MuleTestContainer.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  gradle/enforcement/spotless-xml.properties
  settings.gradle
Labels: integrations

#2476 Upgrade spotless and format xml files
  buildSrc/build.gradle.kts
  dd-java-agent/benchmark-integration/play-perftest/conf/logback.xml
  dd-java-agent/instrumentation/datanucleus-4/src/test/resources/META-INF/persistence.xml
  dd-java-agent/instrumentation/glassfish/src/test/resources/WEB-INF/web.xml
  dd-java-agent/instrumentation/hibernate/core-3.3/src/test/resources/hibernate.cfg.xml
  dd-java-agent/instrumentation/hibernate/core-4.0/src/test/resources/hibernate.cfg.xml
  dd-java-agent/instrumentation/hibernate/core-4.3/src/test/resources/hibernate.cfg.xml
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-java-agent/instrumentation/mule-4/src/main/java/datadog/trace/instrumentation/mule4/EventContextInstrumentation.java
  dd-java-agent/instrumentation/mule-4/src/main/java/datadog/trace/instrumentation/mule4/PrivilegedEventInstrumentation.java
  dd-java-agent/instrumentation/mule-4/src/main/java8/datadog/trace/instrumentation/mule4/CurrentEventHelper.java
  dd-java-agent/instrumentation/mule-4/src/test/java/mule4/HttpServerTestHandlerInstrumentation.java
  dd-java-agent/instrumentation/mule-4/src/test/java/mule4/MuleTestContainer.java
  dd-java-agent/instrumentation/quartz-2/src/test/resources/testConfig.xml
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.10/scala-promise-2.10.gradle
  dd-java-agent/instrumentation/scala-promise/scala-promise-2.13/scala-promise-2.13.gradle
  dd-java-agent/instrumentation/spring-webflux-5/src/test/resources/logback.xml
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/resources/logback.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/repository/conf/axis2.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/build.xml
  dd-java-agent/instrumentation/synapse-3/src/test/resources/synapse/samples/SimpleStockQuoteService/conf/services.xml
  dd-java-agent/src/test/resources/logback.xml
  dd-smoke-tests/log-injection/src/logging/resources/log4j.xml
  dd-smoke-tests/log-injection/src/logging/resources/log4j2.xml
  dd-smoke-tests/log-injection/src/logging/resources/logback.xml
  dd-smoke-tests/play-2.4/conf/logback.xml
  dd-smoke-tests/play-2.5/conf/logback.xml
  dd-smoke-tests/play-2.6/conf/logback.xml
  dd-smoke-tests/play-2.7/application/conf/logback.xml
  dd-smoke-tests/play-2.8/application/conf/logback.xml
  dd-smoke-tests/quarkus/application/build.gradle
  dd-trace-core/src/test/resources/logback.xml
  dd-trace-java.gradle
  gradle/spotbugFilters/exclude.xml
  gradle/spotless.gradle
  test-published-dependencies/build.gradle
Labels: no release notes

#2482 Allow gRPC users to ignore specific outbound RPC calls
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/TracingClientInterceptor.java
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/test/proto/helloworld.proto
  dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: grpc, integrations

#2483 Upgrade bytebuddy to 1.10.22
  gradle/dependencies.gradle
Labels: dependencies

#2478 Propagate context to Spring MessageListenerAdapter
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/AdditionalLibraryIgnoresMatcher.java
  dd-java-agent/instrumentation/spring-rabbit/spring-rabbit.gradle
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/AbstractMessageListenerContainerInstrumentation.java
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/BlockingQueueConsumerInstrumentation.java
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/DeliveryInstrumentation.java
  dd-java-agent/instrumentation/spring-rabbit/src/test/groovy/SpringAmqpTest.groovy
  dd-java-agent/instrumentation/spring-rabbit/src/test/java/rabbit/MessagingRabbitMQApplication.java
  dd-java-agent/instrumentation/spring-rabbit/src/test/java/rabbit/Receiver.java
  dd-java-agent/instrumentation/spring-rabbit/src/test/java/rabbit/Sender.java
  settings.gradle
Labels: context-propagation, integrations, rabbitmq, spring

#2484 Some small build cleanups
  .circleci/config.yml
  dd-java-agent/benchmark/benchmark.gradle
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/mule-4/application/.gitignore
  dd-java-agent/instrumentation/mule-4/application/README.md
  dd-java-agent/instrumentation/mule-4/application/mule-artifact.json
  dd-java-agent/instrumentation/mule-4/application/pom.xml
  dd-java-agent/instrumentation/mule-4/application/src/main/java/mule4/HttpServerTestHandler.java
  dd-java-agent/instrumentation/mule-4/application/src/main/mule/mule-http-test-server.xml
  dd-java-agent/instrumentation/mule-4/application/src/main/resources/application-types.xml
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-smoke-tests/agent-isolation/agent-isolation.gradle
  dd-smoke-tests/cli/cli.gradle
  dd-smoke-tests/field-injection/field-injection.gradle
  dd-smoke-tests/log-injection/log-injection.gradle
  dd-smoke-tests/opentracing/opentracing.gradle
  dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
  dd-smoke-tests/slf4j-mdc/slf4j-mdc.gradle
  dd-smoke-tests/springboot-grpc/springboot-grpc.gradle
  dd-smoke-tests/springboot-mongo/springboot-mongo.gradle
  dd-smoke-tests/springboot/springboot.gradle
  dd-trace-core/dd-trace-core.gradle
  dd-trace-java.gradle
  dd-trace-ot/dd-trace-ot.gradle
  gradle/spotbugs.gradle
  gradle/spotless.gradle
Labels: no release notes

#2486 DRYing forwarded for handling
  dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HaystackHttpCodec.java
Labels: no release notes

#2487 replace WeakMap with ClassValue
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java
Labels: no release notes

#2496 Use groovy map syntax in HTTP codec tests…
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
Labels: no release notes

#2501 Synchronize classloads at class not package granularity
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InternalJarURLHandlerTest.groovy
Labels: bug

#2488 Remove weak map default
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakMap.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/WeakMapTest.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentTooling.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMapSuppliers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakConcurrentSupplierTest.groovy
Labels: no release notes

#2505 Add Mule 4 http client and parallel for each tests
  dd-java-agent/instrumentation/mule-4/application/pom.xml
  dd-java-agent/instrumentation/mule-4/application/src/main/java/mule4/HttpServerTestHandler.java
  dd-java-agent/instrumentation/mule-4/application/src/main/mule/mule-http-test-server.xml
  dd-java-agent/instrumentation/mule-4/application/src/main/mule/mule-test-application.xml
  dd-java-agent/instrumentation/mule-4/mule-4.gradle
  dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleForkedTest.groovy
  dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleHttpServerForkedTest.groovy
  dd-java-agent/instrumentation/mule-4/src/test/groovy/mule4/MuleTestApplicationConstants.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/server/http/TestHttpServer.groovy
Labels: no release notes

#2494 Remove Hystrix test retry and timeout
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
Labels: no release notes

#2507 Disable GitLab CI
  .gitlab-ci.yml.disabled
Labels: no release notes

#2510 Revert "Disable GitLab CI"
  .gitlab-ci.yml
Labels: no release notes

#2511 Add support for redshift JDBC
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
Labels: integrations

#2520 Temporarily ignore SpringBootOpenLibertySmokeTest on IBM JDKs
  dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
Labels: no release notes

#2524 Clean up some runtimes in tests
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Config.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Config.groovy
  dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy
  dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxCircuitBreakerWebClientTest.groovy
  dd-java-agent/instrumentation/vertx-rx-3.5/src/test/groovy/client/VertxRxWebClientTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/client/VertxHttpClientTest.groovy
Labels: dev/testing, no release notes

#2532 close metrics aggregator when CoreTracer is closed
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
Labels: no release notes

#2533 Fix milestone fetching in github actions
  .github/workflows/draft-release-notes-on-tag.yaml
  .github/workflows/increment-milestones-on-tag.yaml
Labels: no release notes

#2519 Add a smoketest for spring-boot webflux 2.5 Milestones
  dd-smoke-tests/spring-boot-2.5-webflux/spring-boot-2.5-webflux.gradle
  dd-smoke-tests/spring-boot-2.5-webflux/src/main_java8/java/datadog/smoketest/springboot/SpringbootApplication.java
  dd-smoke-tests/spring-boot-2.5-webflux/src/main_java8/java/datadog/smoketest/springboot/controller/WebController.java
  dd-smoke-tests/spring-boot-2.5-webflux/src/main_java8/resources/application.properties
  dd-smoke-tests/spring-boot-2.5-webflux/src/test/groovy/datadog/smoketest/SpringBootWebfluxIntegrationTest.groovy
  settings.gradle
Labels: dev/testing, no release notes

#2541 fix typo in pull request template
  .github/pull_request_template.md
Labels: no release notes

#2539 Avoid calling `SdkClientBuilder.overrideConfiguration`…
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java8/datadog/trace/instrumentation/aws/v2/TracingExecutionInterceptor.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/test/groovy/Aws2ClientTest.groovy
Labels: integrations

#2540 Fix create_key script and enable publishing to keyserver
  .gitlab-ci.yml
Labels: no release notes

#2544 Avoid potential ClassCastException in AWSv1 integration
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AWSHttpClientInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/AwsSdkClientDecorator.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestInstrumentation.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/RequestMeta.java
  dd-java-agent/instrumentation/aws-java-sdk-1.11.0/src/main/java/datadog/trace/instrumentation/aws/v0/TracingRequestHandler.java
Labels: aws-sdk, integrations

#2425 Publish directly to Sonatype instead of Bintray
  .circleci/config.yml
  .github/workflows/add-assets-to-release.yaml
  .gitlab-ci.yml
  dd-java-agent/dd-java-agent.gradle
  dd-trace-java.gradle
  dd-trace-ot/dd-trace-ot.gradle
  gradle/java.gradle
  gradle/maven-pom.gradle
  gradle/pom.gradle
  gradle/publish.gradle
Labels: no release notes

#2543 Remove GitHub Pull Request template
  .github/pull_request_template.md
Labels: no release notes

#2548 Override the jgit version to the one gradle 6.8.2 expects
  dd-trace-java.gradle
Labels: no release notes

#2549 validate agent is capable of receiving metrics before enabling metrics aggregation
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/OkHttpSink.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Sink.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/OkHttpSinkTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
Labels: bug

#2554 [CIAPP] Update feature tracking JSON
  .dd-ci/ci-app-spec.json
Labels: no release notes

#2555 cancel scheduled reporting task when metrics is disabled
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
Labels: no release notes

#2516 New reliability env deploy
  .gitignore
  .gitlab-ci.yml
  .gitlab/copy_artifact_s3.py
  .gitlab/gitlab.dockerfile
Labels: no release notes
