Repository DataDog/dd-trace-java, pull requests merged in 2021-06, with the labels that each got.

#2776 [AppSec] Wire up InstrumentationGateway for headers and URI
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/utils/TraceUtils.groovy
  dd-trace-core/src/jmh/java/datadog/trace/core/PendingTraceWrite.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/TagContext.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentApiTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanSerializationTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
  internal-api/src/main/java/datadog/trace/api/gateway/Flow.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
Labels: appsec, no release notes

#2782 Try running 2 smoke tests concurrently
  .circleci/config.yml
  dd-smoke-tests/dd-smoke-tests.gradle
Labels: dev/tooling, no release notes

#2787 Ignore exceptions thrown during couchbase cleanup
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
Labels: dev/testing, flaky-test, no release notes

#2789 retry reporting when it fails in FootprintTest
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/MetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/NoOpMetricsAggregator.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/FootprintTest.groovy
Labels: dev/testing, flaky-test, no release notes

#2791 Fix WebFlux flaky tests + cleanup
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/AdviceUtils.java
Labels: no release notes

#2792 [CIAPP] Fix CircleCI spec for CI App
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CircleCIInfo.java
  internal-api/src/test/resources/ci/circleci.json
Labels: no release notes

#2788 OpenLiberty instrumentation incorrectly overwrote the status code on an error
  dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/LibertyDecorator.java
  dd-smoke-tests/springboot-openliberty/snapshots/datadog.smoketest.SpringBootOpenLibertySnapshotTest.exception404.snap
  dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySnapshotTest.groovy
Labels: bug

#2794 Increase timeout rather than ignore
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
  dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java
Labels: dev/testing, flaky-test, no release notes

#2795 run hystrix tests in strict mode
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/DisableAsyncPropagationWithinConstructorInstrumentation.java
Labels: dev/testing, no release notes

#2801 Don't upload test results for forks since it needs credentials
  .circleci/config.yml
Labels: dev/testing, no release notes

#2798 clean up exclude filters
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExcludeFilter.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/ExcludeFilterTest.groovy
  dd-java-agent/instrumentation/java-concurrent/java-completablefuture/src/main/java/datadog/trace/instrumentation/java/completablefuture/CompletableFutureUniCompletionInstrumentation.java
  dd-java-agent/testing/src/test/groovy/excludefilter/ExcludeFilterForkedTest.groovy
  dd-java-agent/testing/src/test/java/excludefilter/ExcludeFilterTestInstrumentation.java
Labels: no release notes

#2803 prevent propagation into ObjectPool scheduler
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableChainTest.groovy
  dd-java-agent/instrumentation/hystrix-1.4/src/test/groovy/HystrixObservableTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/DisableAsyncPropagationWithinConstructorInstrumentation.java
Labels: flaky-test, no release notes

#2800 Upgrade JMH gradle plugin to 0.6.5 to fix issue where it was attempting to unzip a class file
  dd-trace-java.gradle
Labels: dev/tooling, no release notes

#2802 ByteBuddy 1.11.1
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
  gradle/dependencies.gradle
Labels: dependencies

#2807 implement deterministic sampling with floating point arithmetic
  dd-trace-core/src/main/java/datadog/trace/common/sampling/DeterministicSampler.java
  dd-trace-core/src/test/groovy/datadog/trace/common/sampling/DeterministicSamplerTest.groovy
Labels: efficiency

#2813 Verify no bootstrap classes are loaded prematurely
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
Labels: dev/testing, no release notes

#2816 [CIAPP] Add rich commit metadata from envvars to some CI providers
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/AppVeyorInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/AzurePipelinesInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/BitriseInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/BuildkiteInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/GitLabInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/TravisInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/git/PersonInfo.java
  internal-api/src/test/resources/ci/appveyor.json
  internal-api/src/test/resources/ci/azurepipelines.json
  internal-api/src/test/resources/ci/bitrise.json
  internal-api/src/test/resources/ci/buildkite.json
  internal-api/src/test/resources/ci/gitlab.json
  internal-api/src/test/resources/ci/travisci.json
Labels: no release notes

#2790 Fix flaky spring webflux tests
  dd-java-agent/instrumentation/spring-webflux-5/src/main/java8/datadog/trace/instrumentation/springwebflux/server/AdviceUtils.java
Labels: flaky-test, no release notes

#2823 Fix LatestDepTest for Spring Rabbit
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/RunnableFutureInstrumentation.java
Labels: no release notes

#2825 Update Kafka Client latestDepTests
  dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
  dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTest.groovy
  dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/TextMapExtractAdapterTest.groovy
Labels: dev/testing, no release notes

#2821 sample trace app
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
  dd-smoke-tests/sample-trace/sample-trace.gradle
  dd-smoke-tests/sample-trace/src/test/groovy/datadog/smoketest/SampleTraceSmokeTest.groovy
  settings.gradle
Labels: dev/tooling, diagnostics

#2829 Limit assertj to 3.19.+ to avoid breaking API
  dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
  dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
Labels: dev/testing, no release notes

#2828 Better Gitlab cache
  .gitlab-ci.yml
Labels: dev/tooling, no release notes

#2832 Add span sort for Hazelcast async test
  dd-java-agent/instrumentation/hazelcast-3.6/src/test/groovy/test/hazelcast/v3/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-3.9/src/test/groovy/test/hazelcast/v39/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/HazelcastTest.groovy
Labels: dev/testing, flaky-test, no release notes

#2840 Limit micronaut 2 instrumentation to [2,3)
  dd-java-agent/instrumentation/micronaut-http-server-netty-2/micronaut-http-server-netty-2.gradle
Labels: dev/testing, no release notes

#2631 Remove alloc for a single class name
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsClientInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/JDOQueryInstrumentation.java
  dd-java-agent/instrumentation/datanucleus-4/src/main/java/datadog/trace/instrumentation/datanucleus/JDOTransactionInstrumentation.java
  dd-java-agent/instrumentation/google-http-client/src/main/java/datadog/trace/instrumentation/googlehttpclient/GoogleHttpClientInstrumentation.java
  dd-java-agent/instrumentation/log4j-2.7/src/main/java/datadog/trace/instrumentation/log4j27/ContextDataInjectorFactoryInstrumentation.java
Labels: efficiency, no release notes, performance

#2843 Make couchbase async test not strict and remove retry
  dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy
Labels: dev/testing, flaky-test, no release notes

#2844 Log PendingTrace state after span finish
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Labels: no release notes

#2836 Add measured consume span around call to RabbitMQ message listener
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/AbstractMessageListenerContainerInstrumentation.java
  dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/RabbitListenerDecorator.java
  dd-java-agent/instrumentation/spring-rabbit/src/test/groovy/SpringAmqpTest.groovy
Labels: context-propagation, integrations, rabbitmq, spring

#2842 Add test case for ConsumerRecords.forEach
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
Labels: no release notes

#2810 Rework our byte-buddy build integration to work with 1.10.15+
  buildSrc/build.gradle.kts
  buildSrc/src/main/groovy/InstrumentPlugin.groovy
  buildSrc/src/test/groovy/InstrumentPluginTest.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/AgentGradlePlugin.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/NewTaskForGradlePlugin.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGradlePlugin.java
  dd-java-agent/instrumentation/instrumentation.gradle
  gradle/dependencies.gradle
Labels: dev/tooling, no release notes

#2845 Move unix domain socket helper to shared library and re-use it for profile uploading
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-profiling/agent-profiling.gradle
  dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/common/writer/WriterFactory.java
  dd-trace-core/src/main/java/datadog/trace/core/http/OkHttpUtils.java
  dd-trace-ot/dd-trace-ot.gradle
  settings.gradle
  utils/socket-utils/socket-utils.gradle
  utils/socket-utils/src/main/java/datadog/common/socket/SocketUtils.java
  utils/socket-utils/src/main/java/datadog/common/socket/TunnelingUnixSocket.java
  utils/socket-utils/src/main/java/datadog/common/socket/UnixDomainSocketFactory.java
Labels: no release notes

#2850 Don't try and load java.lang.ProcessHandle on Java 8
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/PidHelper.java
Labels: no release notes

#2834 Upgrade to JMXFetch 0.44.1 and DogStatsD 2.13.0
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-trace-core/dd-trace-core.gradle
  dd-trace-core/src/main/java/datadog/trace/core/monitor/DDAgentStatsDConnection.java
  dd-trace-core/src/test/groovy/datadog/trace/core/monitor/DDAgentStatsDClientTest.groovy
  gradle/dependencies.gradle
  internal-api/src/main/java/datadog/trace/api/Platform.java
  internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
Labels: dependencies

#2851 Add tests for OpenTracing ignoreActiveSpan
  dd-java-agent/instrumentation/opentracing/api-0.31/src/test/groovy/OpenTracing31Test.groovy
  dd-java-agent/instrumentation/opentracing/api-0.32/src/test/groovy/OpenTracing32Test.groovy
Labels: dev/testing, no release notes

#2853 Run instrument task before tests as well
  buildSrc/src/main/groovy/InstrumentPlugin.groovy
Labels: dev/testing, no release notes

#2854 Disable async propagation for scheduleAtFixedRate and scheduleWithFixedDelay
  dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/DisableAsyncPropagationForPeriodicScheduleInstrumentation.java
  dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-concurrent/src/test/java/PeriodicTask.java
Labels: context-propagation, integrations

#2855 Sort spans in flaky kafka streams test
  dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
Labels: dev/testing, no release notes

#2860 Fix regression where HTTPS requests don't propagate trace if connect() is called first
  dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
  dd-java-agent/instrumentation/http-url-connection/src/test/groovy/HttpUrlConnectionConnectFirstTest.groovy
Labels: context-propagation, integrations

#2861 emit checkpoints on Envelope construction and invocation
  dd-java-agent/instrumentation/akka-concurrent/src/akka23Test/groovy/AkkaActorTest.groovy
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaActorCellInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaEnvelopeInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinExecutorTaskInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinPoolInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaForkJoinTaskInstrumentation.java
  dd-java-agent/instrumentation/akka-concurrent/src/main/java/datadog/trace/instrumentation/akka/concurrent/AkkaRoutedActorCellInstrumentation.java
  dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinPoolInstrumentation.java
  dd-java-agent/instrumentation/scala-concurrent/src/main/java/datadog/trace/instrumentation/scala/concurrent/ScalaForkJoinTaskInstrumentation.java
Labels: profiling

#2864 Add upper bound to latestDepTest for ignite
  dd-java-agent/instrumentation/ignite-2.0/ignite-2.0.gradle
Labels: dev/testing, no release notes

#2867 Remove final setting from save actions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: no release notes
