Repository DataDog/dd-trace-java, pull requests merged in 2022-03, with the labels that each got.

#3405 Make dd.trace.header.tags apply to both request and response headers
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/TagContextExtractor.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreTracerTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
  internal-api/src/main/java/datadog/trace/util/Strings.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: breaking-change

#3418 Mark PendingTrace as not enqueued when queue is full
  dd-trace-core/src/main/java/datadog/trace/core/PendingTraceBuffer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
Labels: bug, no release notes

#3419 Use correct parameter for report upload script on CI
  .circleci/config.yml
  gradle/java_no_deps.gradle
Labels: no release notes, dev/build

#3420 Don't overwrite the shadow jar with the shared shadow jar
  dd-java-agent/agent-profiling/profiling-auxiliary-async/profiling-auxiliary-async.gradle
  dd-java-agent/dd-java-agent.gradle
Labels: no release notes, dev/build

#3421 Use lazy initialization for HandlerMappingResourceNameFilter
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingResourceNameFilter.java
Labels: integrations, spring

#3424 Adjust Apache/Drill tracing to cover the shared superclass from Apache/Calcite that the Drill class delegates to
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
Labels: integrations, jdbc

#3428 byte-buddy 1.12.8
  buildSrc/build.gradle.kts
  buildSrc/src/test/groovy/InstrumentPluginTest.groovy
  gradle/dependencies.gradle
Labels: dependencies

#3429 Update gradle wrapper validator
  .github/workflows/gradle-wrapper-validation.yaml
Labels: no release notes, dev/build

#3439 [AppSec] Added extra log message for classloader creation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
Labels: appsec

#3438 [AppSec] Updated security rules (v1.2.6)
  dd-java-agent/appsec/src/main/resources/default_config.json
Labels: appsec

#3437 Add smoketest for webmvc when used with spring-boot 2.6
  dd-smoke-tests/spring-boot-2.6-webmvc/spring-boot-2.6-webmvc.gradle
  dd-smoke-tests/spring-boot-2.6-webmvc/src/main_java8/java/datadog/smoketest/springboot/SpringbootApplication.java
  dd-smoke-tests/spring-boot-2.6-webmvc/src/main_java8/java/datadog/smoketest/springboot/controller/WebController.java
  dd-smoke-tests/spring-boot-2.6-webmvc/src/main_java8/resources/application.properties
  dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/SpringBootWebmvcIntegrationTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractServerSmokeTest.groovy
  settings.gradle
Labels: dev/testing, no release notes

#3246 Make it easier to correlate startup debug log lines
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/FieldBackedContextStores.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ClassLoaderMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextProvider.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextRequestRewriter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/Reference.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceMatcher.java
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
  dd-smoke-tests/field-injection/src/test/groovy/datadog/smoketest/FieldInjectionSmokeTest.groovy
  dd-smoke-tests/osgi/src/test/groovy/datadog/smoketest/AbstractOSGiSmokeTest.groovy
Labels: dev/tooling, diagnostics

#3436 Make TraceInterceptor application more robust
  communication/src/main/java/datadog/communication/monitor/DDAgentStatsDConnection.java
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/util/JfrCliHelper.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/util/JfrCliHelperTest.java
  dd-java-agent/dd-java-agent.gradle
  dd-trace-core/src/main/java/datadog/trace/civisibility/CiVisibilityTraceInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  gradle/java_no_deps.gradle
  internal-api/src/main/java/datadog/trace/api/RatelimitedLogger.java
  internal-api/src/main/java/datadog/trace/relocate/api/IOLogger.java
  internal-api/src/main/java/datadog/trace/relocate/api/RatelimitedLogger.java
  internal-api/src/test/groovy/datadog/trace/relocate/api/IOLoggerTest.groovy
  internal-api/src/test/groovy/datadog/trace/relocate/api/RateLimitedLoggerTest.groovy
Labels: core

#3440 Upgrade gradle to 7.4.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dev/build

#3256 Move relative time calculations to tracer instance
  dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/AgentTestRunner.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/ListWriterAssert.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/PendingTraceBufferTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: core, efficiency

#3454 Skip probing agent trace endpoints when info is available
  communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
  communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/ddagent/PayloadDispatcher.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
  internal-api/src/main/java/datadog/trace/util/Strings.java
  internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
Labels: core

#3455 Appsec: Support parsed urlencoded data on undertow 2
  dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/FormDataMap.java
  dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/FormDataParserInstrumentation.java
  dd-java-agent/instrumentation/undertow-2.0/src/test/groovy/UndertowTest.groovy
Labels: appsec

#3459 Fix undertow runnable wrapping to avoid extending RunnableWrapper
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/RunnableWrapper.java
  dd-java-agent/instrumentation/spring-scheduling-3.1/src/main/java/datadog/trace/instrumentation/springscheduling/SpringSchedulingRunnableWrapper.java
  dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowInstrumentation.java
  dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowRunnableWrapper.java
Labels: integrations

#3460 Undertow: fix peerHostIP
  dd-java-agent/instrumentation/undertow-2.0/src/main/java/datadog/trace/instrumentation/undertow/UndertowDecorator.java
Labels: integrations

#3461 Default classloading instrumentation to always on
  dd-java-agent/instrumentation/classloading/src/main/java/datadog/trace/instrumentation/classloading/ClassloadingInstrumentation.java
Labels: integrations

#3462 Initial stub of new agent-installer
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-installer/agent-installer.gradle
  dd-java-agent/agent-installer/src/main/java/datadog/trace/agent/installer/AgentInstaller.java
  dd-java-agent/agent-installer/src/main/java/datadog/trace/agent/installer/DDClassFileTransformer.java
  dd-java-agent/agent-installer/src/main/java11/datadog/trace/agent/installer/DDJava9ClassFileTransformer.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakCaches.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakMaps.java
  dd-java-agent/instrumentation/instrumentation.gradle
  dd-java-agent/testing/testing.gradle
  settings.gradle
Labels: refactoring

#3469 Add simple Tracer creating test of published dependencies
  .circleci/config.yml
  test-published-dependencies/all-deps-exist/build.gradle
  test-published-dependencies/gradle/wrapper/gradle-wrapper.jar
  test-published-dependencies/gradle/wrapper/gradle-wrapper.properties
  test-published-dependencies/gradlew
  test-published-dependencies/gradlew.bat
  test-published-dependencies/ot-pulls-in-api/build.gradle
  test-published-dependencies/ot-pulls-in-api/src/test/java/CreateTracerTest.java
Labels: dev/testing
