Repository DataDog/dd-trace-java, pull requests merged in 2022-08, with the labels that each got.

#3683 Add CODEOWNERS for ci-app-libraries-java
  .github/CODEOWNERS
Labels: no release notes, ciapp

#3688 [CI-APP] Report test as `skipped` when `org.junit.AssumptionViolatedException` is thrown in JUnit5
  dd-java-agent/instrumentation/junit-5.3/src/main/java8/datadog/trace/instrumentation/junit5/JUnit5Decorator.java
  dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
  dd-java-agent/instrumentation/junit-5.3/src/test/java/org/example/TestAssumptionLegacy.java
Labels: ciapp

#3687 StatusLogger should report the 'dd_version' configured for the app/service
  dd-trace-core/src/main/java/datadog/trace/core/StatusLogger.java
Labels: diagnostics

#3693 Move jctools-core to shared dependency
  dd-java-agent/agent-profiling/agent-profiling.gradle
  dd-java-agent/agent-profiling/profiling-context/profiling-context.gradle
  dd-trace-core/dd-trace-core.gradle
  gradle/dependencies.gradle
Labels: no release notes, refactoring

#3690 Improved dependency resolution
  telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyServiceImplSpecification.groovy
  telemetry/src/test/resources/datadog/telemetry/dependencies/agrona-1.7.2.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/asm-util-9.2.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/bson-4.2.0.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/bson4jackson-2.11.0.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/caffeine-2.8.5.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/spring-webmvc.jar
Labels: no release notes, telemetry

#3692 Support exporting and re-importing ClassNameTrie content to an external resource
  internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java
  internal-api/src/test/groovy/datadog/trace/util/ClassNameTrieTest.groovy
Labels: no release notes

#3682 Added exception catches for the OkHTTPClient header vulnerability
  communication/src/main/java/datadog/communication/http/OkHttpUtils.java
  communication/src/main/java/datadog/communication/http/SafeRequestBuilder.java
  communication/src/test/groovy/datadog/communication/http/SafeRequestBuilderTest.groovy
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
  dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
  telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
Labels: bug, dependencies

#3647 Util to get stacktrace for reported vulnerabilities
  .github/workflows/codeql-analysis.yml
  .github/workflows/test-lib-injection.yaml
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
  gradle.properties
  gradle/dependencies.gradle
  internal-api/internal-api-8/internal-api-8.gradle
  internal-api/internal-api-8/src/jmh/java/datadog/trace/util/stacktrace/HotSpotStackWalkerBenchmark.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/AbstractStackWalker.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/HotSpotStackTraceIterator.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/HotSpotStackWalker.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/StackWalker.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/StackWalkerFactory.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/DefaultStackWalkerTest.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/HotSpotStackTraceIteratorTest.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/HotSpotStackWalkerTest.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerFactoryTest.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTestUtil.java
  internal-api/internal-api-9/internal-api-9.gradle
  internal-api/internal-api-9/src/jmh/java/datadog/trace/util/stacktrace/JDK9StackWalkerBenchmark.java
  internal-api/internal-api-9/src/main/java/datadog/trace/util/stacktrace/JDK9StackWalker.java
  internal-api/internal-api-9/src/test/groovy/datadog/trace/util/stacktrace/JDK9StackWalkerTest.groovy
  settings.gradle
  utils/test-utils/src/main/java/external/util/stacktrace/RecursiveRunner.java
Labels: iast

#3707 Per-span context tracking fixes
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LEB128Support.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/ProfilerTracingContextTracker.java
  dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalEncoderTest.java
  dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalParser.java
  dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/LEB128SupportTest.java
Labels: no release notes, profiling

#3646 [CIAPP] Add `_dd.ci.env_vars` span tag for every CI Provider
  dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/BuildkiteInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/CircleCIInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/GitLabInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/GithubActionsInfo.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/ci/JenkinsInfo.java
  internal-api/src/main/java/datadog/trace/util/Strings.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/CIProviderInfoTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/instrumentation/ci/CISpecExtractor.groovy
  internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
  internal-api/src/test/resources/ci/buildkite.json
  internal-api/src/test/resources/ci/circleci.json
  internal-api/src/test/resources/ci/github.json
  internal-api/src/test/resources/ci/gitlab.json
  internal-api/src/test/resources/ci/jenkins.json
Labels: ciapp

#3657 Lightweight streaming JFR chunk parser
  dd-java-agent/agent-profiling/profiling-controller-jfr/profiling-controller-jfr.gradle
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/ChunkHeader.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/ChunkParserListener.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/LongMapping.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/MetadataEvent.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/RecordingStream.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/main/java/com/datadog/profiling/controller/jfr/parser/StreamingChunkParser.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/TestJfrRecorder.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/parser/ParserEvent.java
  dd-java-agent/agent-profiling/profiling-controller-jfr/src/test/java/com/datadog/profiling/controller/jfr/parser/StreamingChunkParserTest.java
Labels: no release notes, profiling

#3713 [alpha][lib-injection] Change name of docker image
  .gitlab-ci.yml
  lib-injection/application/build.gradle.kts
  lib-injection/src/test/shell/functions.sh
Labels: no release notes, dev/build

#3710 Epoch nano calculation can not use epoch millis
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTracker.java
  dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/IntervalEncoderTest.java
Labels: no release notes, profiling

#3715 [alpha][lib-injection] Change admission annotation
  lib-injection/src/test/shell/functions.sh
Labels: no release notes, dev/build

#3684 Using single class-loader for internal agent classes and resources
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/AgentJarIndex.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/BootstrapProxy.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/DatadogClassLoader.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InternalJarURLHandler.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/exception/ExceptionSampling.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/exceptions/ExceptionProfiling.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/DatadogClassLoaderTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/InternalJarURLHandlerTest.groovy
  dd-java-agent/agent-bootstrap/src/test/resources/classloader-test-jar/jar-with-nested-classes-jdk8
  dd-java-agent/agent-bootstrap/src/test/resources/classloader-test-jar/jar-with-nested-classes-jdk8-readme.md
  dd-java-agent/agent-bootstrap/src/test/resources/classloader-test-jar/testjar-jdk8
  dd-java-agent/agent-bootstrap/src/test/resources/classloader-test-jar/testjar-readme.md
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Utils.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/CustomExcludes.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatchersTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/HelperInjectionTest.groovy
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/exception-profiling/src/main/java11/datadog/exceptions/instrumentation/ThrowableInstanceAdvice.java
  dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/UrlInstrumentation.java
  dd-java-agent/instrumentation/http-url-connection/src/test/groovy/UrlConnectionTest.groovy
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ShadowPackageRenamingTest.groovy
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
  internal-api/src/main/java/datadog/trace/util/AgentTaskScheduler.java
  internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java
  internal-api/src/main/java/datadog/trace/util/Strings.java
  internal-api/src/test/groovy/datadog/trace/util/ClassNameTrieTest.groovy
  internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
Labels: refactoring

#3663 Bridge between instrumentation and IAST
  internal-api/src/main/java/datadog/trace/api/iast/IastModule.java
  internal-api/src/main/java/datadog/trace/api/iast/InstrumentationBridge.java
  internal-api/src/test/groovy/datadog/trace/api/iast/InstrumentationBridgeTest.groovy
Labels: iast

#3708 Dependencies resolution distributed in time.
  telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
  telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyPeriodicAction.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolverQueue.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyService.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
  telemetry/src/main/java/datadog/telemetry/dependency/JbossVirtualFileHelper.java
  telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DepSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyPeriodActionSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverQueueSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyServiceImplSpecification.groovy
  telemetry/src/test/java/datadog/telemetry/dependency/DependencyServiceImplTests.java
  telemetry/telemetry.gradle
Labels: telemetry

#3722 Fix JMXFetchTest
  dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/src/test/java/jvmbootstraptest/JmxStartedChecker.java
Labels: dev/testing

#3724 Fix ProcessSupervisorTest flakiness
  internal-api/src/test/groovy/datadog/trace/util/ProcessSupervisorTest.groovy
Labels: dev/testing

#3728 Fix race condition in embedded mongo tests
  dd-java-agent/instrumentation/mongo/mongo.gradle
  dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy
Labels: dev/testing

#3735 Use AgentThreadFactory for upload dispatcher
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/uploader/BatchUploader.java
  internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
Labels: debugger

#3673 IAST vulnerability reporting API
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/iast/iast.gradle
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastRequestContext.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/Reporter.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/Evidence.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/Location.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/Range.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/Source.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/SourceType.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/Vulnerability.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/VulnerabilityBatch.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/AdapterFactory.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/SourceIndex.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/SourceTypeAdapter.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/SourceTypeString.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/model/json/VulnerabilityEncoding.java
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/LocationTest.groovy
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
  dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
  gradle/dependencies.gradle
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/AbstractStackWalker.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/DefaultStackWalkerTest.java
  settings.gradle
  utils/test-utils/src/main/groovy/datadog/trace/test/util/DDSpecification.groovy
Labels: iast

#3733 Fix when filenames are matching partially
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/TransformerDefinitionMatcher.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
Labels: debugger

#3742 Fix custom logger delay on IBM JDKs
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
  dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
Labels: core

#3741 Fix capturing of vertx.route-handler spans
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java8/datadog/trace/instrumentation/vertx_3_4/server/EndHandlerWrapper.java
  dd-java-agent/instrumentation/vertx-web-4.0/src/main/java8/datadog/trace/instrumentation/vertx_4_0/server/EndHandlerWrapper.java
  dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSmokeTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy
Labels: integrations, vertx

#3749 Prevent port conflict in MongoDB tests
  dd-java-agent/instrumentation/mongo/src/test/groovy/MongoBaseTest.groovy
Labels: dev/testing, no release notes

#3750 Add a CircleCI job named required that github can enforce
  .circleci/config.yml
Labels: dev/build

#3625 Couchbase 3 client instrumentation
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/api8/java/concurrent/StatusSettable.java
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/api8/java/concurrent/StatusSettingCompletableFuture.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/couchbase-2.0.gradle
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseBucketInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClientDecorator.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseClusterInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseOnSubscribe.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/CouchbaseAsyncClientTest.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/springdata/CouchbaseConfig.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringRepositoryTest.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/springdata/CouchbaseSpringTemplateTest.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/springdata/Doc.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/springdata/DocRepository.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.0/src/test/groovy/util/AbstractCouchbaseTest.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/couchbase-2.6.gradle
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseCoreInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/main/java/datadog/trace/instrumentation/couchbase/client/CouchbaseNetworkInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/test/groovy/CouchbaseAsyncClient26Test.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/test/groovy/CouchbaseClient26Test.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/test/groovy/CouchbaseSpanUtil.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/test/groovy/springdata/CouchbaseSpringRepository26Test.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-2.6/src/test/groovy/springdata/CouchbaseSpringTemplate26Test.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/couchbase-3.1.gradle
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/BaseRequestInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/CoreEnvironmentBuilderInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java/datadog/trace/instrumentation/couchbase_31/client/DefaultErrorUtilInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java8/datadog/trace/instrumentation/couchbase_31/client/BaseRequestAdvice.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java8/datadog/trace/instrumentation/couchbase_31/client/CoreEnvironmentBuilderAdvice.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java8/datadog/trace/instrumentation/couchbase_31/client/CouchbaseClientDecorator.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java8/datadog/trace/instrumentation/couchbase_31/client/DatadogRequestSpan.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java8/datadog/trace/instrumentation/couchbase_31/client/DatadogRequestTracer.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/main/java8/datadog/trace/instrumentation/couchbase_31/client/DefaultErrorUtilAdvice.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.1/src/test/groovy/CouchbaseClient31Test.groovy
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/couchbase-3.2.gradle
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/BaseRequestInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/CoreEnvironmentBuilderInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java/datadog/trace/instrumentation/couchbase_32/client/DefaultErrorUtilInstrumentation.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java8/datadog/trace/instrumentation/couchbase_32/client/BaseRequestAdvice.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java8/datadog/trace/instrumentation/couchbase_32/client/CoreEnvironmentBuilderAdvice.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java8/datadog/trace/instrumentation/couchbase_32/client/CouchbaseClientDecorator.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java8/datadog/trace/instrumentation/couchbase_32/client/DatadogRequestSpan.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java8/datadog/trace/instrumentation/couchbase_32/client/DatadogRequestTracer.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/main/java8/datadog/trace/instrumentation/couchbase_32/client/DefaultErrorUtilAdvice.java
  dd-java-agent/instrumentation/couchbase/couchbase-3.2/src/test/groovy/CouchbaseClient32Test.groovy
  dd-java-agent/instrumentation/couchbase/couchbase.gradle
  dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
  settings.gradle
Labels: integrations

#3649 Weak hashing detection intrumentation
  dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplTest.groovy
  dd-java-agent/instrumentation/java-security/java-security.gradle
  dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentation.java
  dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakHashInstrumentationTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
  settings.gradle
Labels: iast

#3761 Extract message and kind from native Java crash
  dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
  dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java
Labels: crashtracking

#3743 Deploy `latest` tag to docker registries
  .gitlab-ci.yml
Labels: dev/build, kubernetes

#3747 Switch to `system-tests` for lib injection testing
  .github/workflows/lib-injection.yaml
Labels: dev/testing, no release notes, dev/build, kubernetes

#3767 Limit latestDepTest for slick instrumentation because of incompatible slf4j
  dd-java-agent/instrumentation/slick/slick.gradle
Labels: dev/testing, no release notes

#3766 Set initial capacity for StringBuilder in tests
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TagsHelperTest.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/CompressionTypeTest.java
  dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
  internal-api/src/test/java/datadog/trace/util/TagsHelperTest.java
Labels: dev/testing, no release notes

#3768 Merge master into project/java-8
  .github/workflows/lib-injection.yaml
  .gitlab-ci.yml
  dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
  dd-java-agent/agent-crashtracking/src/test/java/com/datadog/crashtracking/CrashUploaderTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/TagsHelperTest.java
  dd-java-agent/agent-profiling/profiling-auxiliary-async/src/main/java/com/datadog/profiling/auxiliary/async/AuxiliaryAsyncProfiler.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalEncoder.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/IntervalSequencePruner.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/LongSequence.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTracker.java
  dd-java-agent/agent-profiling/profiling-context/src/main/java/com/datadog/profiling/context/PerSpanTracingContextTrackerFactory.java
  dd-java-agent/agent-profiling/profiling-context/src/test/java/com/datadog/profiling/context/PerSpanTracingContextTrackerFactoryTest.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/CompressionTypeTest.java
  dd-java-agent/agent-profiling/src/main/java/com/datadog/profiling/agent/ProfilingAgent.java
  dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastSystem.java
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplTest.groovy
  dd-java-agent/instrumentation/java-security/java-security.gradle
  dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentation.java
  dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakHashInstrumentationTest.groovy
  dd-java-agent/instrumentation/opentracing/api-0.31/src/main/java/datadog/trace/instrumentation/opentracing31/OTTracer.java
  dd-java-agent/instrumentation/opentracing/api-0.32/src/main/java/datadog/trace/instrumentation/opentracing32/OTTracer.java
  dd-java-agent/instrumentation/slick/slick.gradle
  dd-smoke-tests/springboot-openliberty/src/test/groovy/datadog/smoketest/SpringBootOpenLibertySmokeTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
  dd-trace-api/src/main/java/datadog/trace/api/config/ProfilingConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
  internal-api/src/test/java/datadog/trace/util/TagsHelperTest.java
  settings.gradle
Labels: no release notes

#3765 Save heap dump in CI
  .circleci/collect_reports.sh
  .circleci/config.yml
  dd-trace-java.gradle
Labels: dev/testing, no release notes

#3760 Implement weak cipher detection
  dd-java-agent/iast/src/main/java/com/datadog/iast/IastModuleImpl.java
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplCipherTest.groovy
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplHashTest.groovy
  dd-java-agent/iast/src/test/groovy/com/datadog/iast/IastModuleImplTest.groovy
  dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentation.java
  dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakCipherTest.groovy
  dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakHashInstrumentationTest.groovy
  dd-java-agent/instrumentation/java-security/src/test/groovy/test/WeakHashTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/AppSecConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: iast

#3771 Add CODEOWNERS entry for the IAST team
  .github/CODEOWNERS
Labels: dev/tooling, no release notes, iast

#3769 Fix issue in default stack walker implementation
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/AbstractStackWalker.java
  internal-api/internal-api-8/src/main/java/datadog/trace/util/stacktrace/DefaultStackWalker.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/DefaultStackWalkerTest.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/HotSpotStackWalkerTest.java
  internal-api/internal-api-8/src/test/java/datadog/trace/util/stacktrace/StackWalkerTestUtil.java
  internal-api/internal-api-9/src/test/groovy/datadog/trace/util/stacktrace/JDK9StackWalkerTest.groovy
  utils/test-utils/src/main/java/datadog/trace/test/util/AnyStackRunner.java
Labels: bug, no release notes, iast

#3776 Dependency detection for multi-pom fat jars
  telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolver.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyResolverQueue.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverQueueSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyResolverSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyServiceImplSpecification.groovy
  telemetry/src/test/resources/datadog/telemetry/dependencies/README.md
  telemetry/src/test/resources/datadog/telemetry/dependencies/budgetapp.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/budgetappreduced.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/budgetappreducedbadproperties.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/invalidpomproperties.jar
Labels: telemetry

#3772 Fix capture deserialization for snapshot probes
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/SnapshotProbe.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
Labels: debugger

#3751 On demand port forwarding for testcontainers on CI
  .circleci/autoforward.py
  .circleci/config.yml
  dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/rabbitmq-amqp-2.7.gradle
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
  dd-java-agent/instrumentation/vertx-mysql-client-3.9/src/test/java/TestDatabases.java
Labels: dev/testing

#3773 Fixed AppSec NullPointerException for non-web spans.
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
Labels: appsec
