Repository DataDog/dd-trace-java, pull requests merged in 2022-07, with the labels that each got.

#3633 Separate out configured type matching from static constant matching
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenter.java
  dd-java-agent/instrumentation/aws-lambda-handler/src/main/java/datadog/trace/instrumentation/aws/v1/lambda/LambdaHandlerInstrumentation.java
  dd-java-agent/instrumentation/aws-lambda-handler/src/test/groovy/LambdaHandlerInstrumentationTest.groovy
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java
Labels: no release notes, refactoring

#3623 [alpha] Create tracer injection image for kubernetes
  .github/workflows/test-lib-injection.yaml
  .gitignore
  .gitlab-ci.yml
  lib-injection/.dockerignore
  lib-injection/Dockerfile
  lib-injection/README.md
  lib-injection/build.sh
  lib-injection/copy-javaagent.sh
  lib-injection/dd-apm-test-agent-config.yaml
  lib-injection/kind-config.yaml
  lib-injection/run-local.sh
Labels: dev/tooling, no release notes, experimental, dev/build

#3618 Add some simple trace-annotation inheritance tests
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedInterface.java
  dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedSubClass.java
  dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/TracedSuperClass.java
  dd-java-agent/instrumentation/trace-annotation/trace-annotation.gradle
Labels: dev/testing

#3624 Fix NPE when listing integrations with 'java -jar dd-java-agent.jar -li'
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/ListIntegrationsTest.groovy
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
Labels: no release notes

#3634 Miscellaneous ClassNameTrie improvements
  internal-api/src/main/java/datadog/trace/util/ClassNameTrie.java
  internal-api/src/test/groovy/datadog/trace/util/ClassNameTrieTest.groovy
Labels: no release notes, refactoring

#3632 Provide a stable sequence of Instrumenter ids
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-installer/src/main/java/datadog/trace/agent/installer/AgentInstaller.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Instrumenters.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java
Labels: no release notes, refactoring

#3608 Simplify name matcher implementation
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HierarchyMatchers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/NameMatchers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsState.java
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java
Labels: no release notes, refactoring

#3597 Outline type parsing
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentStrategies.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDClassFileTransformer.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDOutlinePoolStrategy.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDOutlineTypeStrategy.java
  dd-java-agent/agent-builder/src/main/java11/datadog/trace/agent/tooling/bytebuddy/DDJava9ClassFileTransformer.java
  dd-java-agent/agent-builder/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategyTest.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/SharedTypePools.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/HierarchyMatchers.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/AnnotationOutline.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/CachingType.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/FieldOutline.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/FullTypeParser.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/MethodOutline.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/OutlineTypeParser.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeOutline.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeParser.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypePoolFacade.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/WithName.java
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
  gradle/forbiddenApiFilters/main.txt
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: performance, refactoring

#3644 [alpha] Add a publish step to tracer injection image for kubernetes
  .github/workflows/test-lib-injection.yaml
  .gitlab-ci.yml
  lib-injection/run-local.sh
Labels: dev/testing, no release notes, experimental, dev/build

#3650 Limit amazon-sqs-java-messaging-lib to 1.x when testing aws-java-sqs-1.0 integration
  dd-java-agent/instrumentation/aws-java-sqs-1.0/aws-java-sqs-1.0.gradle
Labels: dev/testing, no release notes

#3651 Respect explicit setting of 'dd.profiling.async.enabled=false'…
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ControllerFactory.java
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
Labels: dev/testing, no release notes, profiling

#3559 Telemetry; support for reporting dependencies
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentTransformerBuilder.java
  dd-java-agent/appsec/appsec.gradle
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/AppSecSystem.java
  dd-java-agent/dd-java-agent.gradle
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  gradle/dependencies.gradle
  internal-api/internal-api.gradle
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/ConfigCollector.java
  internal-api/src/main/java/datadog/trace/api/IntegrationsCollector.java
  internal-api/src/main/java/datadog/trace/api/Platform.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java
  internal-api/src/main/java/datadog/trace/util/AgentThreadFactory.java
  internal-api/src/test/groovy/datadog/trace/api/TelemetryCollectorsTest.groovy
  settings.gradle
  telemetry/src/main/java/datadog/telemetry/HostInfo.java
  telemetry/src/main/java/datadog/telemetry/PolymorphicAdapterFactory.java
  telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
  telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
  telemetry/src/main/java/datadog/telemetry/TelemetryService.java
  telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
  telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
  telemetry/src/main/java/datadog/telemetry/Uname.java
  telemetry/src/main/java/datadog/telemetry/dependency/Dependency.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyPeriodicAction.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyService.java
  telemetry/src/main/java/datadog/telemetry/dependency/DependencyServiceImpl.java
  telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
  telemetry/src/main/java/datadog/telemetry/integration/IntegrationPeriodicAction.java
  telemetry/src/main/schemas/telemetry-api-v1.yaml
  telemetry/src/main/templates/enumClass.mustache
  telemetry/src/main/templates/enumOuterClass.mustache
  telemetry/src/main/templates/model.mustache
  telemetry/src/main/templates/pojo.mustache
  telemetry/src/test/groovy/datadog/telemetry/PolymorphicAdapterFactorySpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/RequestBuilderSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/TelemetrySystemSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/UnameTest.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyPeriodActionSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/dependency/DependencyServiceImplSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/integration/IntegrationPeriodicActionTest.groovy
  telemetry/src/test/java/datadog/telemetry/dependency/DependencyServiceImplTests.java
  telemetry/src/test/resources/datadog/telemetry/dependencies/README.md
  telemetry/src/test/resources/datadog/telemetry/dependencies/commons-logging-1.2.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/freemarker-2.3.27-incubating.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/groovy-manifest.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/groovy-no-manifest-info.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/hsqldb-2.3.5-jdk6debug.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/junit-4.12.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/junit.zip
  telemetry/src/test/resources/datadog/telemetry/dependencies/multiverse-core-0.7.0.jar
  telemetry/src/test/resources/datadog/telemetry/dependencies/spring-boot-app.jar
  telemetry/src/test/resources/dd-java-agent.version
  telemetry/src/test/resources/telemetry_intake_emu.py
  telemetry/telemetry.gradle
Labels: appsec

#3653 Accept release version strings in DebuggerSinkTest
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/DebuggerSinkTest.java
Labels: dev/testing, no release notes, flaky-test

#3654 Avoid wrapping null JMS MessageListeners
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSMessageConsumerInstrumentation.java
  dd-java-agent/instrumentation/jms/src/test/groovy/JMS1Test.groovy
Labels: integrations, jms

#3661 use a holder array to reduce AgentClassLoading thread-local churn
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/AgentClassLoading.java
Labels: performance, no release notes

#3666 Cleanup exclusion of shared content when creating shadow jars
  dd-cws-tls/dd-cws-tls.gradle
  dd-java-agent/agent-debugger/agent-debugger.gradle
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/agent-profiling/agent-profiling.gradle
  dd-java-agent/agent-tooling/agent-tooling.gradle
  dd-java-agent/appsec/appsec.gradle
  dd-java-agent/dd-java-agent.gradle
  dd-java-agent/instrumentation/instrumentation.gradle
  gradle/dependencies.gradle
  telemetry/telemetry.gradle
Labels: no release notes, dev/build

#3655 Upgrade gradle to 7.5
  buildSrc/build.gradle.kts
  gradle/java_no_deps.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: no release notes, dev/build

#3672 Fix packaging duplicates
  dd-java-agent/agent-crashtracking/agent-crashtracking.gradle
  dd-java-agent/dd-java-agent.gradle
  gradle/dependencies.gradle
Labels: no release notes, dev/build
