Repository DataDog/dd-trace-java, pull requests merged in 2023-03, with the labels that each got.

#4803 naming schema: undertow
  dd-java-agent/instrumentation/undertow/src/main/java/datadog/trace/instrumentation/undertow/UndertowDecorator.java
  dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowDispatcherTest.groovy
  dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4819 Support fixed-sized weak-key caches
  internal-api/build.gradle
  internal-api/src/main/java/datadog/trace/api/cache/DDCaches.java
  internal-api/src/main/java/datadog/trace/api/cache/FixedSizeWeakKeyCache.java
  internal-api/src/test/groovy/datadog/trace/api/cache/FixedSizeCacheTest.groovy
Labels: no release notes

#4804 service naming: akka http server
  dd-java-agent/instrumentation/akka-http-10.0/src/baseTest/groovy/AkkaHttpServerInstrumentationTest.groovy
  dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerDecorator.java
  dd-java-agent/instrumentation/undertow/undertow-2.0/src/test/groovy/UndertowServletTest.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4790 Fix flakiness due to concurrent mod exceptions
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/datastreams/RecordingDatastreamsPayloadWriter.groovy
Labels: dev/testing, no release notes

#4808 naming schema: finatra
  dd-java-agent/instrumentation/finatra-2.9/src/main/java/datadog/trace/instrumentation/finatra/FinatraDecorator.java
  dd-java-agent/instrumentation/finatra-2.9/src/test/groovy/FinatraServerTest.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4809 naming schema: spray
  dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHttpServerDecorator.java
  dd-java-agent/instrumentation/spray-1.3/src/main/scala/datadog/trace/instrumentation/spray/SprayHttpServerRunSealedRouteAdvice.java
  dd-java-agent/instrumentation/spray-1.3/src/test/groovy/SprayServerTest.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4811 naming schema: restlet
  dd-java-agent/instrumentation/restlet-2.2/build.gradle
  dd-java-agent/instrumentation/restlet-2.2/src/baseTest/groovy/RestletTest.groovy
  dd-java-agent/instrumentation/restlet-2.2/src/main/java/datadog/trace/instrumentation/restlet/RestletDecorator.java
  dd-java-agent/instrumentation/restlet-2.2/src/test/groovy/RestletTestBase.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4807 naming schema: openliberty
  dd-java-agent/instrumentation/liberty-20/build.gradle
  dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/LibertyDecorator.java
  dd-java-agent/instrumentation/liberty-20/src/test/groovy/datadog/trace/instrumentation/liberty20/Liberty20Test.groovy
Labels: no release notes

#4812 naming schema: netty server
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/NettyHttpServerDecorator.java
  dd-java-agent/instrumentation/netty-3.8/src/test/groovy/datadog/trace/instrumentation/netty38/Netty38ServerTest.groovy
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/NettyHttpServerDecorator.java
  dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/NettyHttpServerDecorator.java
  dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/naming/NamingConventions.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4817 naming schema: synapse server
  dd-java-agent/instrumentation/synapse-3/src/main/java/datadog/trace/instrumentation/synapse3/SynapseServerDecorator.java
  dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseTest.groovy
  internal-api/src/main/java/datadog/trace/api/naming/v0/ServerNamingV0.java
Labels: no release notes

#4743 HTTP client path mapping
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/AntPatternPathNormalizer.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecorator.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/AntPatternPathNormalizerTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/HttpResourceDecoratorTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/config/TracerConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: feature-request

#4664 Use specialized build caches in CI
  .circleci/config.yml
Labels: dev/testing, no release notes

#4825 Enable Java parametric tests in CircleCI
  .circleci/config.yml
  dd-trace-ot/build.gradle
Labels: dev/testing, no release notes

#4829 Remove unused RequestBuilder from Telemetry
  telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
Labels: no release notes, refactoring, telemetry

#4838 Limit latestDep of amazon-sqs-java-messaging-lib to 2.0.x
  dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
Labels: no release notes, dependencies

#4830 Update remote docker to latest (default) version
  .circleci/config.yml
Labels: dev/testing, no release notes

#4841 Combine class-loader delegation check with 'hasClass' checks
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/GlobalIgnoresMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/test/ClassLoaderMatchersTest.groovy
Labels: no release notes, refactoring

#4832 Update ASM rules to 1.5.2
  dd-java-agent/appsec/src/main/resources/default_config.json
Labels: asm-waf

#4850 upgrade jplib to 0.21.0
  gradle/dependencies.gradle
Labels: profiling

#4852 Fix failing muzzle classloader tests on CI
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/ReferenceCreator.java
  dd-java-agent/instrumentation/trace-annotation/build.gradle
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
Labels: dev/tooling, no release notes

#4846 Remove map based WeakCache implementation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/WeakCache.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/InstrumenterState.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/WeakCaches.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/ClassFileLocators.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/WeakCacheTest.groovy
  internal-api/src/main/java/datadog/trace/api/cache/FixedSizeCache.java
  internal-api/src/main/java/datadog/trace/api/cache/FixedSizeWeakKeyCache.java
  telemetry/src/main/java/datadog/telemetry/dependency/LocationsCollectingTransformer.java
Labels: no release notes, refactoring, telemetry

#4844 [Serverless] Fix JSON serialization issue
  dd-trace-core/src/main/java/datadog/trace/lambda/LambdaHandler.java
  dd-trace-core/src/main/java/datadog/trace/lambda/SkipAbstractTypeJsonSerializer.java
  dd-trace-core/src/test/groovy/datadog/trace/lambda/LambdaHandlerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/lambda/SkipTypeJsonSerializerTest.groovy
Labels: serverless

#4858 Register that moshi needs reflective access to adapters in TraceSamplingRules/SpanSamplingRules
  dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
  dd-smoke-tests/spring-native/src/test/groovy/SpringNativeWebmvcIntegrationTest.groovy
Labels: integrations, native-image

#4816 W3C trace context extractor/injector
  dd-smoke-tests/springboot-openliberty/snapshots/datadog.smoketest.SpringBootOpenLibertySnapshotTest.nested.snap
  dd-trace-api/src/main/java/datadog/trace/api/DDTraceId.java
  dd-trace-api/src/main/java/datadog/trace/api/TracePropagationStyle.java
  dd-trace-api/src/test/groovy/datadog/trace/api/DDTraceIdTest.groovy
  dd-trace-core/src/jmh/java/datadog/trace/core/propagation/PropagationTagsBenchmark.java
  dd-trace-core/src/main/java/datadog/trace/civisibility/interceptor/CiVisibilityTraceInterceptor.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/DatadogPropagationTagsFactory.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ExtractedContext.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/PropagationTags.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/PropagationTagsFactory.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/W3CHttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/DatadogPTagsCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/PTagsCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/PTagsFactory.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/TagElement.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/TagKey.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/TagValue.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ptags/W3CPTagsCodec.java
  dd-trace-core/src/test/groovy/datadog/trace/core/DDSpanContextPropagationTagsTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogPropagationTagsTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CHttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CPropagationTagsTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/ptags/TagKeyTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/ptags/TagValueTest.groovy
  internal-api/src/main/java/datadog/trace/api/cache/DDPartialKeyCache.java
  internal-api/src/main/java/datadog/trace/api/cache/FixedSizePartialKeyCache.java
  internal-api/src/main/java/datadog/trace/api/sampling/SamplingMechanism.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
  internal-api/src/test/groovy/datadog/trace/api/cache/FixedSizeCacheTest.groovy
  internal-api/src/test/groovy/datadog/trace/api/sampling/SamplingMechanismTest.groovy
Labels: context-propagation

#4859 Upgrade to jplib 0.22.0
  gradle/dependencies.gradle
Labels: profiling

#4862 update profiler smoke test flags
  dd-smoke-tests/src/main/groovy/datadog/smoketest/AbstractSmokeTest.groovy
Labels: dev/testing, no release notes, profiling

#4860 Make sure telemetry responses are always closed
  dd-java-agent/agent-crashtracking/src/main/java/com/datadog/crashtracking/CrashUploader.java
  telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
  telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
Labels: telemetry

#4854 Replace map-based TypeInfoCache with a fixed-sized array approach derived from FixedSizeCache
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/TypeInfoCache.java
Labels: performance, refactoring

#4843 Add software.amazon and com.mongodb to exclusions
  dd-java-agent/instrumentation/iast-instrumenter/src/main/resources/datadog/trace/instrumentation/iastinstrumenter/iast_exclusion.trie
  dd-java-agent/instrumentation/iast-instrumenter/src/test/groovy/IastExclusionTrieTest.groovy
Labels: asm-iast

#4855 Reset vulnerability deduplication every hour
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/ReporterTest.groovy
Labels: asm-iast

#4864 Ignore classes annotated with jakarta.decorator.Decorator
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AbstractTransformerBuilder.java
Labels: integrations

#4729 Blocking: support redirect action
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/blocking/BlockingActionHelper.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/blocking/BlockingServiceImpl.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/blocking/BlockingServiceImplSpecification.groovy
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
  dd-java-agent/appsec/src/test/resources/redirect_actions.json
  dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyBlockingHelper.java
  dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyDecorator.java
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyDecorator.java
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/GrizzlyHttpBlockingHelper.java
  dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty/JettyBlockResponseFunction.java
  dd-java-agent/instrumentation/jetty-common/src/main/java/datadog/trace/instrumentation/jetty/JettyBlockingHelper.java
  dd-java-agent/instrumentation/liberty-20/src/main/java/datadog/trace/instrumentation/liberty20/LibertyDecorator.java
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/BlockingResponseHandler.java
  dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/NettyHttpServerDecorator.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/BlockingResponseHandler.java
  dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/NettyHttpServerDecorator.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/BlockingResponseHandler.java
  dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/NettyHttpServerDecorator.java
  dd-java-agent/instrumentation/servlet-common/src/main/java/datadog/trace/instrumentation/servlet/ServletBlockingHelper.java
  dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatBlockingHelper.java
  dd-java-agent/instrumentation/tomcat-5.5/src/main/java/datadog/trace/instrumentation/tomcat/TomcatDecorator.java
  dd-java-agent/instrumentation/undertow/src/main/java/datadog/trace/instrumentation/undertow/UndertowBlockResponseFunction.java
  dd-java-agent/instrumentation/undertow/src/main/java/datadog/trace/instrumentation/undertow/UndertowBlockingHandler.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-trace-api/src/main/java/datadog/appsec/api/blocking/Blocking.java
  dd-trace-api/src/main/java/datadog/appsec/api/blocking/BlockingContentType.java
  dd-trace-api/src/main/java/datadog/appsec/api/blocking/BlockingDetails.java
  dd-trace-api/src/main/java/datadog/appsec/api/blocking/BlockingService.java
  internal-api/src/main/java/datadog/trace/api/gateway/BlockResponseFunction.java
  internal-api/src/main/java/datadog/trace/api/gateway/Flow.java
  internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Labels: asm-waf

#4873 Fix spring-native smoke tests
  dd-smoke-tests/spring-native/application/build.gradle
  dd-smoke-tests/spring-native/application/settings.gradle
Labels: no release notes

#4874 Update to libsqreen 6.1.1: Improve libc detection
  dd-java-agent/appsec/build.gradle
Labels: asm-waf

#4871 Miscellaneous clean-up of comments/logging
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/bytebuddy/DDCachingPoolStrategy.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/outline/TypeFactory.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextInjector.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsMatcher.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/ShouldInjectFieldsState.java
  internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Labels: no release notes, refactoring

#4880 Add upper bound for kotlinx-coroutines-core
  dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/build.gradle
Labels: dev/testing, integrations, no release notes

#4879 Revert "Upgrade to jplib 0.22.0"
  gradle/dependencies.gradle
Labels: no release notes, profiling

#4881 Archive system-tests logs before uploading
  .circleci/config.yml
Labels: dev/testing, no release notes

#4877 Use per-JDK Docker images
  .circleci/config.yml
  dd-smoke-tests/spring-native/build.gradle
  gradle/java_no_deps.gradle
Labels: dev/testing, no release notes

#4884 Fix Java version parsing for pre-releases
  internal-api/src/main/java/datadog/trace/api/Platform.java
  internal-api/src/test/groovy/datadog/trace/api/PlatformTest.groovy
Labels: core

#4886 upgrade jplib to 0.24.0
  gradle/dependencies.gradle
Labels: profiling

#4885 Call site instrumentation for request#getQueryString()
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
  dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
  dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/TestHttpServletRequestCallSiteSuite.java
  dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
  dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
  dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
  internal-api/src/main/java/datadog/trace/api/iast/model/SourceTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Labels: no release notes, asm-iast

#4872 Telemetry API v1 updated to the latest version
  telemetry/src/main/java/datadog/telemetry/HostInfo.java
  telemetry/src/main/java/datadog/telemetry/RequestBuilder.java
  telemetry/src/main/java/datadog/telemetry/TelemetryService.java
  telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
  telemetry/src/main/java/datadog/telemetry/api/Application.java
  telemetry/src/main/java/datadog/telemetry/api/DistributionSeries.java
  telemetry/src/main/java/datadog/telemetry/api/Distributions.java
  telemetry/src/main/java/datadog/telemetry/api/Host.java
  telemetry/src/main/java/datadog/telemetry/api/LogMessage.java
  telemetry/src/main/java/datadog/telemetry/api/LogMessageLevel.java
  telemetry/src/main/java/datadog/telemetry/api/Logs.java
  telemetry/src/main/java/datadog/telemetry/api/Metric.java
  telemetry/src/main/java/datadog/telemetry/api/Product.java
  telemetry/src/main/java/datadog/telemetry/api/ProductError.java
  telemetry/src/main/java/datadog/telemetry/api/Products.java
  telemetry/src/main/java/datadog/telemetry/api/RequestType.java
  telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
Labels: telemetry

#4842 naming schema: rabbitmq
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitCommandInstrumentation.java
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/test/groovy/RabbitMQTest.groovy
  internal-api/src/main/java/datadog/trace/api/naming/NamingSchema.java
  internal-api/src/main/java/datadog/trace/api/naming/v0/MessagingNamingV0.java
  internal-api/src/main/java/datadog/trace/api/naming/v0/NamingSchemaV0.java
  internal-api/src/main/java/datadog/trace/api/naming/v1/MessagingNamingV1.java
  internal-api/src/main/java/datadog/trace/api/naming/v1/NamingSchemaV1.java
Labels: no release notes

#4853 naming schema: graphql
  dd-java-agent/instrumentation/graphql-java-14.0/src/main/java/datadog/trace/instrumentation/graphqljava/GraphQLDecorator.java
  dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
Labels: no release notes

#4851 naming schema: jms changes
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jms/MessageConsumerState.java
  dd-java-agent/instrumentation/jms/src/main/java/datadog/trace/instrumentation/jms/JMSDecorator.java
  dd-java-agent/instrumentation/jms/src/test/groovy/TimeInQueueForkedTest.groovy
Labels: no release notes

#4849 naming schema: kafka changes
  dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java
  dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTestBase.groovy
  dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsDecorator.java
  dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTestBase.groovy
Labels: no release notes

#4891 Harden config map parsing
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
Labels: bug, core

#4892 Move all code from SourceType to internal-api
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/SourceType.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/VulnerabilityType.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/SourceTypeAdapter.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/TaintedObjectAdapter.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/RangeTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/SourceTypeTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/TaintedObjectEncodingTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/model/json/VulnerabilityEncodingTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/RangesTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintUtils.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/taint/TaintedObjectsLogTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/telemetry/taint/TaintedObjectsWithTelemetryTest.groovy
  dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/IastAgentTestRunner.groovy
  dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/JsonFactoryCallSite.java
  dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/FileCallSite.java
  dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/FileInputStreamCallSite.java
  dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/FileOutputStreamCallSite.java
  dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/PathCallSite.java
  dd-java-agent/instrumentation/java-io/src/main/java/datadog/trace/instrumentation/java/lang/PathsCallSite.java
  dd-java-agent/instrumentation/java-lang/java-lang-11/src/main/java/datadog/trace/instrumentation/java/lang/jdk11/StringCallSite.java
  dd-java-agent/instrumentation/java-lang/java-lang-9/src/main/java/datadog/trace/instrumentation/java/lang/invoke/StringConcatFactoryCallSite.java
  dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/ProcessBuilderCallSite.java
  dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/RuntimeCallSite.java
  dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringBuilderCallSite.java
  dd-java-agent/instrumentation/java-lang/src/main/java/datadog/trace/instrumentation/java/lang/StringCallSite.java
  dd-java-agent/instrumentation/java-net/src/main/java/datadog/trace/instrumentation/java/net/URLDecoderCallSite.java
  dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakCipherInstrumentationCallSite.java
  dd-java-agent/instrumentation/java-security/src/main/java/datadog/trace/instrumentation/java/security/WeakHashInstrumentationCallSite.java
  dd-java-agent/instrumentation/javax-naming/src/main/java/datadog/trace/instrumentation/javax/naming/DirContextCallSite.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/IastConnectionCallSite.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/IastStatementCallSite.java
  dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/callsite/Servlet3RequestCallSite.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/CookieCallSite.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/ServletRequestCallSite.java
  internal-api/src/main/java/datadog/trace/api/iast/PropagationTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/VulnerabilityTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/model/SourceTypes.java
  internal-api/src/test/groovy/datadog/trace/api/iast/SourceTypesTest.groovy
  internal-api/src/test/groovy/datadog/trace/api/iast/telemetry/IastTelemetryCollectorTest.groovy
Labels: no release notes, asm-iast

#4897 Add Play 2.8 OpenTelemetry smoke test
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryContextInstrumentation.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OpenTelemetryInstrumentation.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelContext.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelScope.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpan.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanBuilder.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelSpanContext.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelTracer.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelTracerBuilder.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/main/java/datadog/trace/instrumentation/opentelemetry14/OtelTracerProvider.java
  dd-java-agent/instrumentation/opentelemetry/opentelemetry-1.4/src/test/groovy/OpenTelemetry14Test.groovy
  dd-smoke-tests/play-2.8-otel/app/Filters.java
  dd-smoke-tests/play-2.8-otel/app/actions/AbstractAction.java
  dd-smoke-tests/play-2.8-otel/app/actions/Action1.java
  dd-smoke-tests/play-2.8-otel/app/actions/Action2.java
  dd-smoke-tests/play-2.8-otel/app/actions/SAction.scala
  dd-smoke-tests/play-2.8-otel/app/controllers/JController.java
  dd-smoke-tests/play-2.8-otel/app/controllers/SController.scala
  dd-smoke-tests/play-2.8-otel/app/filters/AbstractFilter.java
  dd-smoke-tests/play-2.8-otel/app/filters/Filter1.java
  dd-smoke-tests/play-2.8-otel/app/filters/Filter2.java
  dd-smoke-tests/play-2.8-otel/app/filters/Filter3.java
  dd-smoke-tests/play-2.8-otel/app/filters/Filter4.java
  dd-smoke-tests/play-2.8-otel/build.gradle
  dd-smoke-tests/play-2.8-otel/conf/application.conf
  dd-smoke-tests/play-2.8-otel/conf/logback.xml
  dd-smoke-tests/play-2.8-otel/conf/routes
  dd-smoke-tests/play-2.8-otel/src/test/groovy/datadog/smoketest/Play28OTelAkkaSmokeTest.groovy
  dd-smoke-tests/play-2.8-otel/src/test/groovy/datadog/smoketest/Play28OTelNettySmokeTest.groovy
  dd-smoke-tests/play-2.8-otel/src/test/groovy/datadog/smoketest/Play28OTelSmokeTest.groovy
  settings.gradle
Labels: dev/testing, no release notes

#4898 Remove not needed cookie call sites
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/CookieCallSite.java
  dd-java-agent/instrumentation/servlet/src/test/groovy/CookieCallSiteTest.groovy
  dd-java-agent/instrumentation/servlet/src/test/java/datadog/smoketest/controller/CookieTestSuite.java
  dd-smoke-tests/spring-boot-2.6-webmvc/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
  dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
  dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
  internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
  internal-api/src/test/groovy/datadog/trace/api/iast/SourceTypesTest.groovy
Labels: no release notes, asm-iast

#4878 Update client ip resolver
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolver.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecoratorTest.groovy
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/decorator/http/ClientIpAddressResolverSpecification.groovy
  dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/SpringBootSmokeTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/propagation/ContextInterpreter.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/DatadogHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HaystackHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/W3CHttpExtractorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/XRayHttpExtractorTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Labels: asm-waf

#4893 Create Taintable interface for non bootstrap classes
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/Source.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/model/json/EvidenceAdapter.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
  dd-java-agent/agent-tooling/build.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/iast/TaintableVisitor.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/bytebuddy/iast/TaintableVisitorTest.groovy
  dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/JsonFactoryCallSite.java
  dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/JsonFactoryInstrumentation.java
  dd-java-agent/instrumentation/jackson-core/src/main/java/datadog/trace/instrumentation/jackson/core/JsonParserInstrumentation.java
  dd-java-agent/instrumentation/jackson-core/src/test/groovy/JsonFactoryCallSiteTest.groovy
  dd-java-agent/instrumentation/jackson-core/src/test/groovy/JsonFactoryInstrumentationTest.groovy
  dd-java-agent/instrumentation/jackson-core/src/test/java/foo/bar/JsonFactoryTestSuite.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/CookieCallSite.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/CookieInstrumentation.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/HttpServletRequestCallSite.java
  dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/request/ServletRequestCallSite.java
  dd-java-agent/instrumentation/servlet/src/test/groovy/CookieInstrumentationTest.groovy
  dd-java-agent/instrumentation/servlet/src/test/groovy/HttpServletRequestCallSiteTest.groovy
  dd-java-agent/instrumentation/servlet/src/test/groovy/ServletRequestCallSiteTest.groovy
  internal-api/src/main/java/datadog/trace/api/iast/PropagationTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/Taintable.java
  internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java
  internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Labels: performance, no release notes, asm-iast

#4902 add service name and resource name to profiling context
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/test/groovy/datadog/trace/core/scopemanager/ScopeManagerTest.groovy
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilerContext.java
Labels: profiling

#4907 reduce the number of noisy log statements
  dd-java-agent/agent-profiling/profiling-auxiliary-ddprof/src/main/java/com/datadog/profiling/auxiliary/ddprof/AuxiliaryDatadogProfiler.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkOngoingRecording.java
  dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/JfrMBeanHelper.java
  dd-java-agent/agent-profiling/profiling-controller-oracle/src/main/java/com/datadog/profiling/controller/oracle/OracleJdkOngoingRecording.java
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/ProfileUploader.java
Labels: no release notes

#4909 add _dd.trace prefix to built in tracing based profiling attributes
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
  dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/CodeHotspotsTest.java
  dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
Labels: profiling

#4911 Upgrade jmxfetch to 0.47.5 to fix CVE-2022-1471
  dd-java-agent/agent-jmxfetch/build.gradle
  dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
  dd-java-agent/instrumentation/kotlin-coroutines/coroutines-1.5/build.gradle
Labels: security

#4908 Fix merge of rule data provided in the config file
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/CurrentAppSecConfig.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/MergedAsmData.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
  dd-java-agent/appsec/src/test/resources/rules_with_data_config.json
Labels: asm-waf

#4912 Upgrade jmxfetch to 0.47.5 to fix CVE-2022-1471
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
  dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
  dd-java-agent/instrumentation/aws-java-sqs-1.0/aws-java-sqs-1.0.gradle
  dd-java-agent/instrumentation/rabbitmq-amqp-2.7/rabbitmq-amqp-2.7.gradle
  dd-java-agent/instrumentation/spring-data-1.8/spring-data-1.8.gradle
  dd-java-agent/instrumentation/spring-jms-3.1/spring-jms-3.1.gradle
  dd-java-agent/instrumentation/spring-rabbit/spring-rabbit.gradle
  dd-java-agent/instrumentation/spring-scheduling-3.1/spring-scheduling-3.1.gradle
  dd-java-agent/instrumentation/spring-webflux-5/spring-webflux-5.gradle
  dd-java-agent/instrumentation/spring-webmvc-3.1/spring-webmvc-3.1.gradle
Labels: security

#4915 remove gRPC queueing time instrumentation
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/SynchronizationContextInstrumentation.java
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/TimedRunnable.java
Labels: no release notes

#4917 bump jplib to 0.26.0
  gradle/dependencies.gradle
Labels: profiling

#4924 Support using the Java tracer with both -javaagent and -jar at the same time
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/AgentCLI.java
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentJar.java
Labels: dev/tooling

#4920 Include JDK system classes in muzzle build-time checks
  buildSrc/src/main/groovy/MuzzlePlugin.groovy
Labels: dev/tooling, no release notes

#4921 Avoid ClassNotFoundException when resteasy-spring attempts to process tracer-related beans
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/BeanDefinitionRepairer.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/SpringBeanProcessorInstrumentation.java
Labels: integrations, spring

#4888 Allow using Java agent arguments to provide config properties
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/AgentArgsInjector.java
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigConverter.java
  internal-api/src/main/java/datadog/trace/util/Strings.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/AgentArgsInjectorTest.groovy
  internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
  internal-api/src/test/groovy/datadog/trace/util/StringsTest.groovy
Labels: core

#4919 Build-time instrumenting toolchain support
  buildSrc/src/main/groovy/InstrumentPlugin.groovy
  buildSrc/src/main/groovy/InstrumentingPlugin.groovy
  buildSrc/src/test/groovy/InstrumentPluginTest.groovy
  dd-java-agent/agent-tooling/build.gradle
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleGenerator.java
  dd-java-agent/instrumentation/build.gradle
Labels: dev/tooling, no release notes

#4930 Allow unknown sampling priorities from external sources
  internal-api/src/main/java/datadog/trace/api/sampling/SamplingMechanism.java
  internal-api/src/test/groovy/datadog/trace/api/sampling/SamplingMechanismTest.groovy
Labels: core, no release notes

#4900 Adding RequestContext slot for CI Visibility
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpanContext.java
  dd-trace-core/src/test/groovy/datadog/trace/core/CoreSpanBuilderTest.groovy
  internal-api/src/main/java/datadog/trace/api/gateway/RequestContextSlot.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/TagContext.java
Labels: ci-visibility

#4943 Setup python 3.9 for system tests
  .circleci/config.yml
Labels: dev/testing, no release notes

#4901 Taint spring path and matrix variables
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/source/WebModuleImpl.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/source/WebModuleTest.groovy
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/TemplateAndMatrixVariablesInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/TemplateVariablesUrlHandlerInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/urlhandlermapping/UrlHandlerMappingTest.groovy
  dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/TemplateAndMatrixVariablesInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java/datadog/trace/instrumentation/springweb6/TemplateVariablesUrlHandlerInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/HandleMatchAdvice.java
  dd-java-agent/instrumentation/spring-webmvc-6.0/src/main/java17/datadog/trace/instrumentation/springweb6/InterceptorPreHandleAdvice.java
  dd-java-agent/instrumentation/spring-webmvc-6.0/src/test/groovy/datadog/trace/instrumentation/springweb6/boot/SpringBootBasedTest.groovy
  dd-java-agent/instrumentation/spring-webmvc-6.0/src/test/groovy/datadog/trace/instrumentation/springweb6/urlhandlermapping/UrlHandlerMappingTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-smoke-tests/custom-systemloader/src/test/groovy/datadog/smoketest/CustomSystemLoaderSmokeTest.groovy
  dd-smoke-tests/jboss-modules/src/test/groovy/datadog/smoketest/AbstractModulesSmokeTest.groovy
  dd-smoke-tests/osgi/src/test/groovy/datadog/smoketest/AbstractOSGiSmokeTest.groovy
  dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSmokeTest.groovy
  dd-smoke-tests/resteasy/src/test/groovy/smoketest/ResteasySmokeTest.groovy
  dd-smoke-tests/spring-boot-2.6-webmvc/src/test/groovy/IastSpringBootSmokeTest.groovy
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/SpringbootApplication.java
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/IastWebController.java
  dd-smoke-tests/springboot/src/main/java/datadog/smoketest/springboot/controller/SimpleIastController.java
  dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastSpringBootSmokeTest.groovy
  dd-smoke-tests/src/main/groovy/datadog/smoketest/ProcessManager.groovy
  gradle/java_no_deps.gradle
  internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/source/WebModule.java
Labels: asm-iast

#4914 rework profiling context API
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfiler.java
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilerContextSetter.java
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingIntegration.java
  dd-java-agent/agent-profiling/profiling-ddprof/src/main/java/com/datadog/profiling/ddprof/DatadogProfilingScope.java
  dd-java-agent/agent-profiling/profiling-ddprof/src/test/java/com/datadog/profiling/ddprof/DatadogProfilerTest.java
  dd-java-agent/testing/build.gradle
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/TestProfilingContextIntegration.groovy
  dd-smoke-tests/profiling-integration-tests/src/main/java/datadog/smoketest/profiling/ProfilingTestApplication.java
  dd-trace-api/build.gradle
  dd-trace-api/src/main/java/datadog/trace/api/experimental/Profiling.java
  dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingContext.java
  dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingContextSetter.java
  dd-trace-api/src/main/java/datadog/trace/api/experimental/ProfilingScope.java
  dd-trace-api/src/main/java/datadog/trace/api/internal/InternalTracer.java
  dd-trace-api/src/test/groovy/datadog/trace/api/EventTrackerTest.groovy
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/ProfilingContextIntegration.java
Labels: profiling

#4670 Jersey instrumentation for IAST
  dd-java-agent/instrumentation/jersey/build.gradle
  dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderAdvice.java
  dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/AbstractStringReaderInstrumentation.java
  dd-java-agent/instrumentation/jersey/src/main/java/datadog/trace/instrumentation/jersey/HttpHeadersInstrumentation.java
  dd-java-agent/instrumentation/jersey/src/test/groovy/datadog/trace/instrumentation/jersey/AbstractStringReaderTest.groovy
  dd-java-agent/instrumentation/jersey/src/test/java/foo/bar/TestSuite.java
  dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/WithHttpServer.groovy
  dd-smoke-tests/jersey-2/build.gradle
  dd-smoke-tests/jersey-2/src/main/java/com/restserver/DB.java
  dd-smoke-tests/jersey-2/src/main/java/com/restserver/Main.java
  dd-smoke-tests/jersey-2/src/main/java/com/restserver/Resource.java
  dd-smoke-tests/jersey-2/src/main/webapp/WEB-INF/web.xml
  dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2SmokeTest.groovy
  dd-smoke-tests/jersey-3/build.gradle
  dd-smoke-tests/jersey-3/src/main/java/smoketest/DB.java
  dd-smoke-tests/jersey-3/src/main/java/smoketest/MainApp.java
  dd-smoke-tests/jersey-3/src/main/java/smoketest/config/AutoScanFeature.java
  dd-smoke-tests/jersey-3/src/main/java/smoketest/resource/MyResource.java
  dd-smoke-tests/jersey-3/src/test/groovy/datadog/smoketest/Jersey3SmokeTest.groovy
  settings.gradle
Labels: asm-iast

#4945 Add padding to B3 propagation headers
  dd-trace-core/src/jmh/java/datadog/trace/core/propagation/InjectorBenchmark.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/B3HttpInjectorTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/propagation/HttpInjectorTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  utils/test-utils/src/main/groovy/datadog/trace/test/util/StringUtils.groovy
Labels: context-propagation

#4950 Remove additional probes in ProbeDefinition
  dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ClassesToRetransformFinder.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationComparer.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/Instrumentor.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/LogInstrumentor.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/MetricInstrumentor.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/instrumentation/SpanInstrumentor.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationComparerTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerProductChangesListenerTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/TransformerDefinitionMatcherTest.java
Labels: no release notes, refactoring, debugger

#4956 Docker base image on release Fix
  .gitlab-ci.yml
Labels: no release notes, dev/build

#4959 Remove active attribute in probe definitions
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/LogProbe.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/MetricProbe.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/ProbeDefinition.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/SpanProbe.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerTransformerTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/LogProbesInstrumentationTest.java
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ServerDebuggerIntegrationTest.java
Labels: no release notes, refactoring, debugger

#4847 Implement DBM-APM feature for JDBC instrumentation
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/DatabaseClientDecorator.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/jdbc/DBQueryInfo.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/DBQueryInfoTest.groovy
  dd-java-agent/instrumentation/jdbc/build.gradle
  dd-java-agent/instrumentation/jdbc/src/jmh/java/datadog.trace.instrumentation.jdbc/SQLCommenterBenchmark.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/AbstractConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DBMCompatibleConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/DefaultConnectionInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/SQLCommenter.java
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTestBase.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/RemoteJDBCInstrumentationTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/SQLCommenterTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
  dd-trace-core/src/main/java/datadog/trace/core/DDSpan.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentSpan.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/AgentTracer.java
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/InstrumentationTags.java
Labels: jdbc

#4965 Fix test-case spans to always be root spans
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/civisibility/TestEventsHandler.java
  dd-java-agent/instrumentation/junit-4.10/src/test/groovy/JUnit4Test.groovy
  dd-java-agent/instrumentation/junit-5.3/src/test/groovy/JUnit5Test.groovy
  dd-java-agent/instrumentation/testng/src/testFixtures/groovy/datadog/trace/instrumentation/testng/TestNGTest.groovy
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/TestFrameworkTest.groovy
Labels: bug, ci-visibility

#4738 Measured methods config option
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/traceannotation/MeasuredMethodFilter.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/traceannotation/TraceAnnotationConfigParser.java
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
  dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceDecorator.java
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/MeasuredConfigTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationConfigParserTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/Trace.java
  dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
  internal-api/src/main/java/datadog/trace/api/InstrumenterConfig.java
Labels: feature-request

#4631 Added forked test to test new trace annotation operation names
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationNewOpNameForkedTest.groovy
  dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
Labels: dev/testing, no release notes

#4928 Support retrieving context-stores by class name
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/InstrumentationContext.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedContextRequestRewriter.java
  dd-java-agent/testing/src/test/groovy/context/FieldInjectionForkedTest.groovy
  dd-java-agent/testing/src/test/java/context/FieldInjectionTestInstrumentation.java
Labels: dev/tooling, no release notes

#4970 Catch IllegalArgumentException for URLDecoder
  dd-trace-core/src/main/java/datadog/trace/core/propagation/HttpCodec.java
Labels: core

#4976 Update codeowners for appsec
  .github/CODEOWNERS
Labels: no release notes

#4984 Temporarily pin awssdk to 2.20.33 for aws-java-sqs-2.0:latestDepTest
  dd-java-agent/instrumentation/aws-java-sdk-2.2/build.gradle
  dd-java-agent/instrumentation/aws-java-sqs-2.0/build.gradle
Labels: no release notes, dependencies

#4983 Disable flaky tests
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
Labels: dev/testing, no release notes

#4981 bump jplib to 0.28.0
  gradle/dependencies.gradle
Labels: profiling

#4982 Report eval error in case of uncaught exception
  dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/DebuggerContext.java
  dd-java-agent/agent-debugger/debugger-bootstrap/src/main/java/datadog/trace/bootstrap/debugger/Snapshot.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturedSnapshotTest.java
  dd-java-agent/agent-debugger/src/test/resources/CapturedSnapshot05.java
Labels: debugger

#4988 Fix flakiness of serialization timeout tests
  dd-java-agent/agent-debugger/build.gradle
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SnapshotSerializationTest.java
Labels: no release notes, flaky-test, debugger

#4986 Remove env & version tag check for probes
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationUpdater.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/EnvironmentAndVersionChecker.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationUpdaterTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/EnvironmentAndVersionCheckerTest.java
Labels: debugger

#4980 WAF Metrics over Telemetry
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/powerwaf/PowerWAFModule.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/powerwaf/PowerWAFModuleSpecification.groovy
  dd-java-agent/build.gradle
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  internal-api/build.gradle
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/MetricCollector.java
  internal-api/src/test/groovy/datadog/trace/api/TelemetryCollectorsTest.groovy
  telemetry/src/main/java/datadog/telemetry/TelemetryRunnable.java
  telemetry/src/main/java/datadog/telemetry/TelemetryService.java
  telemetry/src/main/java/datadog/telemetry/TelemetryServiceImpl.java
  telemetry/src/main/java/datadog/telemetry/TelemetrySystem.java
  telemetry/src/main/java/datadog/telemetry/metric/MetricPeriodicAction.java
  telemetry/src/test/groovy/datadog/telemetry/TelemetryRunnableSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/TelemetryServiceSpecification.groovy
  telemetry/src/test/groovy/datadog/telemetry/metric/MetricPeriodicActionSpecification.groovy
Labels: asm-waf, metrics, telemetry

#4899 Added health metrics around trace construction
  dd-trace-core/src/main/java/datadog/trace/common/writer/PayloadDispatcher.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/RemoteWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/writer/SpanSamplingWorker.java
  dd-trace-core/src/main/java/datadog/trace/core/PendingTrace.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/HealthMetrics.java
  dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScope.java
  dd-trace-core/src/main/java/datadog/trace/core/scopemanager/ContinuableScopeManager.java
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDAgentWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterCombinedTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/DDIntakeWriterTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/PayloadDispatcherTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/common/writer/SpanSamplingWorkerTest.groovy
  dd-trace-core/src/test/groovy/datadog/trace/core/monitor/HealthMetricsTest.groovy
Labels: core

#4805 Initial version of the vert.x 3.x instrumentation
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/propagation/PropagationModuleImpl.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/propagation/PropagationModuleTest.groovy
  dd-java-agent/instrumentation/netty-buffer-4/build.gradle
  dd-java-agent/instrumentation/netty-buffer-4/src/main/java/datadog/trace/instrumentation/netty40/buffer/ByteBufInputStreamInstrumentation.java
  dd-java-agent/instrumentation/netty-buffer-4/src/main/java/datadog/trace/instrumentation/netty40/buffer/ByteBufInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/build.gradle
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/AbstractHttpServerRequestInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/BufferInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/CaseInsensitiveHeadersInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/HeadersAdaptorInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/Http2ServerRequestInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/core/HttpServerRequestInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/CookieImplInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/IastRoutingContextImplInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/PathParameterPublishingHelper.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/RouteImplInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/main/java/datadog/trace/instrumentation/vertx_3_4/server/VertxVersionMatcher.java
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/core/BufferInstrumentationTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/core/CaseInsensitiveHeadersInstrumentationTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/core/HeadersAdaptorInstrumentationTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/core/HttpServerRequestInstrumentationTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.4/src/test/groovy/server/IastRoutingContextImplInstrumentationTest.groovy
  dd-java-agent/instrumentation/vertx-web-3.5/build.gradle
  dd-java-agent/instrumentation/vertx-web-3.5/src/main/java/datadog/trace/instrumentation/vertx_3_5/core/VertxHttpHeadersInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-3.5/src/test/groovy/core/VertxHttpHeadersInstrumentationTest.groovy
  dd-smoke-tests/iast-util/build.gradle
  dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastServerSmokeTest.groovy
  dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastVertxSmokeTest.groovy
  dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/model/TaintedObject.groovy
  dd-smoke-tests/vertx-3.4/application/.gitignore
  dd-smoke-tests/vertx-3.4/application/build.gradle.kts
  dd-smoke-tests/vertx-3.4/application/gradle/wrapper/gradle-wrapper.jar
  dd-smoke-tests/vertx-3.4/application/gradle/wrapper/gradle-wrapper.properties
  dd-smoke-tests/vertx-3.4/application/gradlew
  dd-smoke-tests/vertx-3.4/application/gradlew.bat
  dd-smoke-tests/vertx-3.4/application/settings.gradle.kts
  dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/smoketest/vertx_3_4/IastHandler.java
  dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/vertx_3_4/IastVerticle.java
  dd-smoke-tests/vertx-3.4/application/src/main/java/datadog/vertx_3_4/MainVerticle.java
  dd-smoke-tests/vertx-3.4/build.gradle
  dd-smoke-tests/vertx-3.4/src/test/groovy/datadog/smoketest/IastVertxSmokeTest.groovy
  dd-smoke-tests/vertx-3.4/src/test/groovy/datadog/smoketest/VertxRouteSmokeTest.groovy
  dd-smoke-tests/vertx-3.4/src/test/groovy/datadog/smoketest/VertxSmokeTest.groovy
  dd-smoke-tests/vertx-3.9/application/src/main/java/datadog/smoketest/vertx_3_9/IastHandler.java
  dd-smoke-tests/vertx-3.9/application/src/main/java/datadog/vertx_3_9/IastVerticle.java
  dd-smoke-tests/vertx-3.9/build.gradle
  dd-smoke-tests/vertx-3.9/src/test/groovy/datadog/smoketest/IastVertxSmokeTest.groovy
  internal-api/src/main/java/datadog/trace/api/iast/SourceTypes.java
  internal-api/src/main/java/datadog/trace/api/iast/propagation/PropagationModule.java
  internal-api/src/test/groovy/datadog/trace/api/iast/SourceTypesTest.groovy
  settings.gradle
Labels: vertx, asm-iast

#5001 Mark GraphQLVxForkedTest as flaky
  dd-java-agent/instrumentation/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
Labels: dev/testing, no release notes, flaky-test

#5002 Mark SynapseVxForkedTest as flaky
  dd-java-agent/instrumentation/synapse-3/src/test/groovy/datadog/trace/instrumentation/synapse3/SynapseTest.groovy
Labels: dev/testing, no release notes, flaky-test

#4848 ZIO 2.0 instrumentation
  dd-java-agent/instrumentation/zio/build.gradle
  dd-java-agent/instrumentation/zio/zio-2.0/build.gradle
  dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/FiberContext.java
  dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/TracingSupervisor.java
  dd-java-agent/instrumentation/zio/zio-2.0/src/main/java/datadog/trace/instrumentation/zio/v2_0/ZioRuntimeInstrumentation.java
  dd-java-agent/instrumentation/zio/zio-2.0/src/test/groovy/ZioRuntimeInstrumentationTest.groovy
  dd-java-agent/instrumentation/zio/zio-2.0/src/test/scala/ZioTestFixtures.scala
  settings.gradle
Labels: integrations, community, scala

#4831 Parallelized test jobs in CI
  .circleci/config.yml
  build.gradle
  gradle/configure_tests.gradle
Labels: dev/testing, no release notes

#5006 Revert "disable datadog profiler by default"
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: no release notes
