Repository DataDog/dd-trace-java, pull requests merged in 2025-09, with the labels that each got.

#9444 Align CSS health metrics
  dd-trace-core/src/main/java/datadog/trace/core/monitor/TracerHealthMetrics.java
Labels: type: enhancement, comp: metrics

#9449 Add reflect config for CSS and graalvm
  dd-java-agent/agent-bootstrap/src/main/resources/META-INF/native-image/com.datadoghq/dd-java-agent/reflect-config.json
Labels: type: bug, comp: metrics

#9459 Error Logs Remediation
  dd-java-agent/agent-profiling/profiling-controller/src/main/java/com/datadog/profiling/controller/ProfilerSettingsSupport.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/HelperInjector.java
  telemetry/src/main/java/datadog/telemetry/log/LogPeriodicAction.java
  telemetry/src/test/groovy/datadog/telemetry/log/LogPeriodicActionTest.groovy
Labels: type: bug, comp: telemetry

#9406 add support debugger/v2/input endpoint
  communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
  communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
  communication/src/test/resources/agent-features/agent-info.json
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
Labels: type: enhancement, comp: debugger

#9471 Added guard for restClient shutdown freeze.
  dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4ClientTestBase.groovy
  dd-java-agent/instrumentation/lettuce-5/src/test/groovy/Lettuce5ClientTestBase.groovy
Labels: comp: testing, tag: no release notes

#9470 Improving TagMap coverage
  internal-api/src/main/java/datadog/trace/api/TagMap.java
  internal-api/src/test/java/datadog/trace/api/TagMapEntryTest.java
  internal-api/src/test/java/datadog/trace/api/TagMapFuzzTest.java
  internal-api/src/test/java/datadog/trace/api/TagMapScenario.java
  internal-api/src/test/java/datadog/trace/api/TagMapTest.java
  internal-api/src/test/java/datadog/trace/api/TagMapType.java
Labels: comp: core, type: refactoring

#9484 group hazelcast in a super module
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/build.gradle
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/gradle.lockfile
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/DistributedObjectDecorator.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/DistributedObjectInstrumentation.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/HazelcastConstants.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/main/java/datadog/trace/instrumentation/hazelcast36/SpanFinishingExecutionCallback.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.6/src/test/groovy/test/hazelcast/v3/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/build.gradle
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/gradle.lockfile
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientInvocationDecorator.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/ClientMessageInstrumentation.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/HazelcastConstants.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/main/java/datadog/trace/instrumentation/hazelcast39/SpanFinishingExecutionCallback.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-3.9/src/test/groovy/test/hazelcast/v39/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/build.gradle
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/gradle.lockfile
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/ClientInvocationInstrumentation.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/ClientListenerInstrumentation.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/HazelcastConstants.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/HazelcastDecorator.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/InvocationAdvice.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/main/java/datadog/trace/instrumentation/hazelcast4/SpanFinishingExecutionCallback.java
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/HazelcastTest.groovy
  dd-java-agent/instrumentation/hazelcast/hazelcast-4.0/src/test/groovy/test/hazelcast/v4/SumTask.groovy
  settings.gradle.kts
Labels: inst: others, tag: no release notes, type: refactoring

#9464 apply the fix from #9128 to the other instance of the test
  dd-java-agent/instrumentation/graphql-java/graphql-java-14.0/src/test/groovy/GraphQLTest.groovy
Labels: comp: testing, tag: no release notes, type: refactoring, inst: graphql

#9465 Use constant instead of magic values for IsTraceRoot
  dd-trace-core/src/main/java/datadog/trace/common/metrics/SerializingMetricWriter.java
  dd-trace-core/src/main/java/datadog/trace/common/metrics/TriState.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/SerializingMetricWriterTest.groovy
Labels: tag: no release notes, comp: metrics

#9482 Added `ikeycmd` and `ikeyman` utilities from `IBM SDK, Java Technology Edition` to exclusion list.
  metadata/denied-arguments.tsv
  metadata/requirements.json
Labels: type: enhancement, comp: library injection

#9498 Revert "Avoid race conditions between contributing and writing to a stat aggregate"
  dd-trace-core/src/main/java/datadog/trace/common/metrics/Aggregator.java
Labels: type: bug, tag: no release notes, comp: metrics

#9481 Add Java 25 support to Maven smoke tests
  dd-java-agent/instrumentation/jacoco/src/main/java/datadog/trace/instrumentation/jacoco/ClassInstrumenterInstrumentation.java
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit_platform_runner/pom.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_jacoco_and_argline/pom.xml
  internal-api/build.gradle.kts
  internal-api/src/main/java/datadog/trace/api/civisibility/coverage/CoveragePerTestBridge.java
Labels: type: enhancement, tag: no release notes, comp: tooling

#9493 add waiting hook in HttpServerTest to try to solve Pekko's flakiness
  dd-java-agent/instrumentation-testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-java-agent/instrumentation/pekko-http-1.0/src/baseTest/groovy/PekkoHttpServerInstrumentationTest.groovy
Labels: comp: testing, tag: no release notes, type: refactoring

#9131 Add new features for trace tagging rules
  dd-java-agent/appsec/build.gradle
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/config/AppSecConfigServiceImpl.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplJsonAdapterTest.groovy
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/config/AppSecConfigServiceImplSpecification.groovy
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/ddwaf/WAFModuleSpecification.groovy
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/AppSecRequestContextSpecification.groovy
  dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/TraceTaggingSmokeTest.groovy
Labels: type: enhancement, comp: asm waf

#9496 Properly handle user provided crash/oome script paths
  dd-java-agent/agent-crashtracking/src/main/java/datadog/crashtracking/Initializer.java
  dd-java-agent/agent-crashtracking/src/test/java/datadog/crashtracking/ScriptInitializerTest.java
Labels: type: bug, comp: crash tracking

#9505 Add junit-platform-launcher as a test runtime dependency to all modules
  dd-java-agent/agent-ci-visibility/build.gradle
  dd-java-agent/agent-debugger/build.gradle
  dd-java-agent/agent-llmobs/build.gradle
  gradle/java_deps.gradle
  gradle/libs.versions.toml
Labels: comp: testing, tag: no release notes

#9500 Cleanup usages of JUnit4.
  dd-java-agent/instrumentation/aerospike-4/src/test/groovy/datadog/trace/instrumentation/aerospike4/AerospikeAsyncClientTest.groovy
  dd-java-agent/instrumentation/aws-java/aws-java-dynamodb-2.0/src/test/groovy/DynamoDbUtilTest.groovy
  dd-java-agent/instrumentation/cucumber/src/test/java/org/example/cucumber/calculator/CalculatorSteps.java
  dd-java-agent/instrumentation/jakarta-ws-annotations/src/test/groovy/WebServiceTest.groovy
  dd-java-agent/instrumentation/jax-ws-annotations-1/src/test/groovy/WebServiceTest.groovy
  dd-java-agent/instrumentation/jax-ws-annotations-2/src/test/groovy/WebServiceProviderTest.groovy
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/java/org/example/cucumber/calculator/CalculatorSteps.java
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-attempt-to-fix-disabled-failed/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-attempt-to-fix-failed/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-attempt-to-fix-quarantined-failed/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-no-retry-failed/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-parallel/coverages.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-quarantined-failed-atr/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-quarantined-failed-efd/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-quarantined-failed-known/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-quarantined-failed/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-retry-failed-scenario-outline-5.4.0/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-retry-failed-scenario-outline-latest/events.ftl
  dd-java-agent/instrumentation/junit-5.3/cucumber-junit-5/src/test/resources/test-retry-failed/events.ftl
  dd-java-agent/instrumentation/karate/src/test/java/org/example/Flaky.java
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/AgentDebuggerIntegrationTest.java
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/BaseIntegrationTest.java
  internal-api/src/test/java/datadog/trace/api/TagMapEntryTest.java
  internal-api/src/test/java/datadog/trace/api/TagMapTest.java
Labels: comp: testing, tag: no release notes

#9477 Update ddapm-test-agent to latest 1.33.0.
  .gitlab-ci.yml
Labels: comp: testing, tag: no release notes

#9504 Fix error logged for Bridge methods
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerTransformer.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/probe/Where.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/probe/WhereTest.java
Labels: type: bug, comp: debugger

#9536 Convert eager APIs to lazy APIs
  dd-smoke-tests/appsec/spring-tomcat7/build.gradle
  dd-smoke-tests/appsec/springboot-graphql/build.gradle
  dd-smoke-tests/appsec/springboot-security/build.gradle
  dd-smoke-tests/appsec/springboot/build.gradle
  dd-smoke-tests/datastreams/kafkaschemaregistry/build.gradle
Labels: type: enhancement, tag: no release notes, comp: tooling

#9520 add type to requests sent to intake
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/JsonSnapshotSerializer.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ProbeStatus.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/SymbolSink.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/ProbeStatusSinkTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/sink/SymbolSinkTest.java
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/ExceptionDebuggerIntegrationTest.java
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/LogProbesIntegrationTest.java
Labels: type: enhancement, tag: no release notes, comp: debugger

#9534 Retries the version range resolution in MuzzlePlugin
  buildSrc/src/main/kotlin/datadog/gradle/plugin/muzzle/MuzzleMavenRepoUtils.kt
Labels: tag: no release notes, comp: tooling

#9546 Correct the mixup in compression algorithms on Oracle JDK 8
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/CompressingRequestBody.java
  dd-java-agent/agent-profiling/profiling-uploader/src/main/java/com/datadog/profiling/uploader/CompressionType.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/CompressingRequestBodyTest.java
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
  dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
Labels: type: bug, tag: no release notes, comp: profiling, run-tests: oracle8

#9552 Unified timeout of 15 minutes. Improved logic of taking thread and heap dumps.
  dd-java-agent/agent-ci-visibility/build.gradle
  dd-java-agent/instrumentation/aws-java/aws-java-sqs-1.0/build.gradle
  dd-java-agent/instrumentation/aws-java/aws-java-sqs-2.0/build.gradle
  dd-java-agent/instrumentation/kafka/kafka-clients-0.11/build.gradle
  dd-java-agent/instrumentation/vertx/vertx-rx-3.5/build.gradle
  dd-smoke-tests/gradle/build.gradle
  dd-smoke-tests/maven/build.gradle
  gradle/configure_tests.gradle
  gradle/dump_hanging_test.gradle
Labels: type: enhancement, comp: testing, tag: no release notes

#9558 Add system-tests on pushes on master + schedules
  .github/workflows/run-system-tests.yaml
Labels: type: enhancement, comp: testing, tag: no release notes

#9559 Update doc with latest layout, instrumentation tests updated, and exception suppress note
  docs/how_instrumentations_work.md
  docs/how_to_test.md
Labels: type: enhancement, type: documentation, tag: no release notes

#9569 Disable byte-buddy's Nexus mechanism
  dd-java-agent/agent-builder/src/main/java/datadog/trace/agent/tooling/AgentInstaller.java
Labels: type: enhancement, comp: core

#9530 Fixing pekko test: revert previous change and fix test server
  dd-java-agent/instrumentation-testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-java-agent/instrumentation/pekko-http-1.0/src/baseTest/groovy/PekkoHttpServerInstrumentationTest.groovy
  dd-java-agent/instrumentation/pekko-http-1.0/src/baseTest/scala/PekkoHttpTestWebServer.scala
Labels: comp: testing, tag: no release notes, type: refactoring

#9574 Minor code cleanup.
  dd-java-agent/agent-ci-visibility/civisibility-test-fixtures/src/main/groovy/datadog/trace/civisibility/CiVisibilityTestUtils.groovy
  dd-java-agent/agent-profiling/profiling-uploader/src/test/java/com/datadog/profiling/uploader/ProfileUploaderTest.java
  dd-smoke-tests/concurrent/java-25/src/test/groovy/datadog/smoketest/concurrent/AbstractStructuredConcurrencyTest.groovy
  dd-smoke-tests/datastreams/kafkaschemaregistry/src/main/java/datadog/smoketest/datastreams/kafkaschemaregistry/KafkaProducerWithSchemaRegistry.java
  dd-smoke-tests/datastreams/kafkaschemaregistry/src/main/java/datadog/smoketest/datastreams/kafkaschemaregistry/Message.java
  dd-smoke-tests/datastreams/kafkaschemaregistry/src/main/java/datadog/smoketest/datastreams/kafkaschemaregistry/message.proto
Labels: comp: testing, tag: no release notes, type: refactoring

#9575 Fixed git command hangs in case if no remote exists.
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/git/impacted/no_remote/git/config
Labels: type: bug, comp: testing

#9577 Change SLO check notifications channel
  .gitlab/macrobenchmarks.yml
Labels: type: enhancement, tag: no release notes, comp: tooling

#9580 Fix gradle update pipeline
  .github/workflows/update-gradle-dependencies.yaml
Labels: type: enhancement, comp: testing

#9582 Remove proposal doc
  boolean-conversion-proposal.md
Labels: tag: no release notes

#9563 Adding supported-configurations.json file
  metadata/supported-configurations.json
Labels: comp: core, type: documentation, tag: no release notes

#9573 Prevent using v1/input endpoint for snapshots
  communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
  communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
  communication/src/test/resources/agent-features/agent-info-with-telemetry-proxy.json
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentTest.java
  dd-java-agent/instrumentation-testing/src/main/groovy/datadog/trace/agent/test/InstrumentationSpecification.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Labels: type: enhancement, comp: debugger

#9585 Reference to scheduled action should be inside task to avoid race condition.
  gradle/dump_hanging_test.gradle
Labels: type: bug, comp: testing, tag: no release notes

#9510 Enable process tags collection by default
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/test/groovy/datadog/trace/api/ProcessTagsForkedTest.groovy
  remote-config/remote-config-core/src/test/groovy/datadog/remoteconfig/PollerRequestFactoryTest.groovy
Labels: comp: core, type: feature request, mergequeue-status: queued

#9599 Remove extra jersey smoke test module
  settings.gradle.kts
Labels: type: enhancement, tag: no release notes, comp: tooling

#9566 Migrate tests and `ConfigInversionMetricCollector` to `config-utils` module
  dd-java-agent/instrumentation/graal/native-image/src/main/java/datadog/trace/instrumentation/graal/nativeimage/NativeImageGeneratorRunnerInstrumentation.java
  internal-api/build.gradle.kts
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/main/java/datadog/trace/api/telemetry/ConfigInversionMetricCollectorImpl.java
  internal-api/src/test/groovy/datadog/trace/api/telemetry/ConfigInversionMetricCollectorImplTest.groovy
  internal-api/src/test/groovy/datadog/trace/api/telemetry/ConfigInversionMetricCollectorTestHelper.java
  telemetry/src/main/java/datadog/telemetry/metric/ConfigInversionMetricPeriodicAction.java
  utils/config-utils/build.gradle.kts
  utils/config-utils/src/main/java/datadog/trace/api/telemetry/ConfigInversionMetricCollector.java
  utils/config-utils/src/main/java/datadog/trace/api/telemetry/ConfigInversionMetricCollectorProvider.java
  utils/config-utils/src/test/groovy/datadog/trace/api/ConfigSettingTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/api/env/CapturedEnvironmentTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/bootstrap/config/provider/AgentArgsInjectorTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/bootstrap/config/provider/AgentArgsParserTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/bootstrap/config/provider/ConfigConverterTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/bootstrap/config/provider/PropertiesConfigSourceTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/bootstrap/config/provider/StableConfigMappingExceptionTest.groovy
  utils/config-utils/src/test/groovy/datadog/trace/bootstrap/config/provider/StableConfigSourceTest.groovy
Labels: type: enhancement, comp: api

#9614 Ensure no unexpected labels are introduced
  .github/pull_request_template.md
  .github/workflows/README.md
  .github/workflows/check-pull-request-labels.yaml
Labels: type: enhancement, tag: no release notes, comp: tooling

#9616 Update CODEOWNERS (rename apm-sdk-api to apm-sdk-capabilities)
  .github/CODEOWNERS
Labels: tag: no release notes

#9617 Update smoke test tasks to use lazy API
  dd-smoke-tests/appsec/springboot-grpc/build.gradle
  dd-smoke-tests/appsec/springboot-security/build.gradle
  dd-smoke-tests/appsec/springboot/build.gradle
  dd-smoke-tests/cli/build.gradle
  dd-smoke-tests/concurrent/java-21/build.gradle
  dd-smoke-tests/concurrent/java-25/build.gradle
  dd-smoke-tests/crashtracking/build.gradle
  dd-smoke-tests/custom-systemloader/build.gradle
  dd-smoke-tests/datastreams/kafkaschemaregistry/build.gradle
  dd-smoke-tests/debugger-integration-tests/latest-jdk-app/build.gradle
  dd-smoke-tests/field-injection/build.gradle
  dd-smoke-tests/gradle/build.gradle
  dd-smoke-tests/iast-propagation/build.gradle
  dd-smoke-tests/iast-util/iast-util-11/build.gradle
  dd-smoke-tests/iast-util/iast-util-17/build.gradle
  dd-smoke-tests/java9-modules/build.gradle
  dd-smoke-tests/jersey-2/build.gradle
  dd-smoke-tests/jersey-3/build.gradle
  dd-smoke-tests/lib-injection/build.gradle
  dd-smoke-tests/maven/build.gradle
  dd-smoke-tests/osgi/build.gradle
  dd-smoke-tests/profiling-integration-tests/build.gradle
  dd-smoke-tests/quarkus/build.gradle
  dd-smoke-tests/ratpack-1.5/build.gradle
  dd-smoke-tests/resteasy/build.gradle
  dd-smoke-tests/rum/tomcat-10/build.gradle
  dd-smoke-tests/rum/tomcat-11/build.gradle
  dd-smoke-tests/rum/tomcat-9/build.gradle
  dd-smoke-tests/rum/wildfly-15/build.gradle
  dd-smoke-tests/spring-boot-2.3-webmvc-jetty/build.gradle
  dd-smoke-tests/spring-boot-2.4-webflux/build.gradle
  dd-smoke-tests/spring-boot-2.5-webflux/build.gradle
  dd-smoke-tests/spring-boot-2.6-webflux/build.gradle
  dd-smoke-tests/spring-boot-2.6-webmvc/build.gradle
  dd-smoke-tests/spring-boot-2.7-webflux/build.gradle
  dd-smoke-tests/spring-boot-3.0-webflux/build.gradle
  dd-smoke-tests/spring-boot-3.0-webmvc/build.gradle
  dd-smoke-tests/spring-boot-3.3-webmvc/build.gradle
  dd-smoke-tests/spring-boot-rabbit/build.gradle
  dd-smoke-tests/spring-security/build.gradle
  dd-smoke-tests/springboot-grpc/build.gradle
  dd-smoke-tests/springboot-java-11/build.gradle
  dd-smoke-tests/springboot-java-17/build.gradle
  dd-smoke-tests/springboot-mongo/build.gradle
  dd-smoke-tests/springboot-openliberty-23/build.gradle
  dd-smoke-tests/springboot/build.gradle
  dd-smoke-tests/tracer-flare/build.gradle
  dd-smoke-tests/vertx-3.4/build.gradle
  dd-smoke-tests/vertx-3.9-resteasy/build.gradle
  dd-smoke-tests/vertx-3.9/build.gradle
  dd-smoke-tests/vertx-4.2/build.gradle
  dd-smoke-tests/wildfly/build.gradle
Labels: type: enhancement, tag: no release notes, comp: tooling

#9612 Add retries to Gradle wrapper test command in Launcher smoke test
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleLauncherSmokeTest.groovy
Labels: comp: testing, tag: no release notes, comp: ci visibility

#9624 wildfly-9.0 configuration was eager and misplaced
  dd-java-agent/instrumentation/wildfly-9.0/build.gradle
Labels: tag: no release notes, comp: tooling

#9525 Resilience4j 2.x
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/build.gradle
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/gradle.lockfile
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/CircuitBreakerDecorator.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/CircuitBreakerInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/FallbackCallableInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/FallbackCheckedSupplierInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/FallbackCompletionStageInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/FallbackSupplierInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/Resilience4jModule.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/Resilience4jSpan.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/Resilience4jSpanDecorator.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/RetryDecorator.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/RetryInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/WrapperWithContext.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/test/groovy/CircuitBreakerTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/test/groovy/FallbackTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/test/groovy/RetryTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-2.0/src/test/groovy/StackedDecoratorsTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/build.gradle
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/gradle.lockfile
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/CircuitBreakerOperatorInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/FallbackOperatorInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/ReactorHelper.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/Resilience4jReactorModule.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/main/java/datadog/trace/instrumentation/resilience4j/RetryOperatorInstrumentation.java
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/test/groovy/CircuitBreakerTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/test/groovy/FallbackTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/test/groovy/RetryTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/test/groovy/StackedOperatorsTest.groovy
  dd-java-agent/instrumentation/resilience4j/resilience4j-reactor-2.0/src/test/groovy/TraceCapturingTest.groovy
  dd-trace-api/src/main/java/datadog/trace/api/config/TraceInstrumentationConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  settings.gradle.kts
Labels: type: feature request, inst: others

#9499 Revert Java 25-EA kotlin workaround
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/CapturingTestBase.java
Labels: type: enhancement, tag: do not merge, tag: no release notes, comp: tooling

#9631 downgrade akka http 2.6 dependencies for compile
  dd-java-agent/instrumentation/akka/akka-http/akka-http-10.6/build.gradle
  dd-java-agent/instrumentation/akka/akka-http/akka-http-10.6/gradle.lockfile
Labels: comp: testing, tag: no release notes, type: refactoring
