Repository DataDog/dd-trace-java, pull requests merged in 2025-06, with the labels that each got.

#8891 Ignore quarkus jaxrs stubs and cdi wrapper proxies
  dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/proxy_ignored_class_name.trie
Labels: type: bug, inst: others

#8789 Enforce size limit on application_monitoring.yaml files
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/StableConfigParser.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/StableConfigParserTest.groovy
Labels: type: enhancement, comp: api

#8905 Fix for the InitializationTelemetryTest when running on Oracle JDK 8.
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/src/test/java/jvmbootstraptest/CustomSecurityManager.java
  dd-java-agent/src/test/java/jvmbootstraptest/InitializationTelemetryCheck.java
Labels: type: bug, comp: core, tag: no release notes, run-tests: oracle8

#8914 SSI smoke tests should only run as part of nightly
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#8915 Use resolved address for peer.hostname when available without hitting the cache
  dd-java-agent/agent-bootstrap/build.gradle
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/BaseDecorator.java
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/net/HostNameResolver.java
  dd-java-agent/agent-bootstrap/src/test/groovy/datadog/trace/bootstrap/instrumentation/java/net/HostNameResolverForkedTest.groovy
Labels: type: bug, comp: core

#8924 Revert "SSI smoke tests should only run as part of nightly"
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#8936 Update test source file reporting to match codeowners file
  .circleci/collect_results.sh
Labels: type: enhancement, tag: no release notes, comp: tooling

#8943 Allow CI to use unpinned version of docker build image
  .github/workflows/update-docker-build-image.yaml
  .gitlab-ci.yml
Labels: type: bug, tag: no release notes, comp: tooling

#8927 Replace SSI ReadMe content with link to Confluence
  metadata/README.md
Labels: tag: no release notes, comp: tooling

#8953 Remove ubuntu17 from test variants
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#8946 Show cgroup memory and cpu after run
  .gitlab-ci.yml
  .gitlab/cgroup-info.sh
Labels: tag: no release notes, comp: tooling

#8955 Fix flaky Gradle Daemon instrumentation smoke test
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
  dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/coverages.ftl
  dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/events.ftl
  dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/src/test/java/datadog/smoke/HelloPluginFunctionalTest.java
Labels: comp: testing, tag: no release notes, comp: ci visibility

#8957 Disable Debugger tracer smoke tests for j9
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/TracerDebuggerIntegrationTest.java
Labels: type: bug, comp: testing, tag: no release notes, comp: debugger

#8958 Remove appsec_no_iast benchmark scenarios
  benchmark/load/petclinic/benchmark.json
  benchmark/startup/petclinic/benchmark.json
Labels: tag: no release notes, comp: tooling

#8967 Improve stability of InstrumenterUnloadTest
  dd-java-agent/src/test/groovy/datadog/trace/agent/InstrumenterUnloadTest.groovy
  dd-java-agent/src/test/java/jvmbootstraptest/UnloadingChecker.java
Labels: type: enhancement, comp: tooling

#8969 Pin Spring Petclinic in benchmarks
  benchmark/Dockerfile
Labels: tag: no release notes, comp: tooling

#8974 Always call System.gc() and System.runFinalization() at least once in `awaitGC`
  utils/test-utils/src/main/java/datadog/trace/test/util/GCUtils.java
Labels: type: enhancement, comp: tooling

#8976 Update Gradle Daemon smoke tests to use Maven repository proxy when available
  dd-smoke-tests/gradle/build.gradle
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
  dd-smoke-tests/gradle/src/test/resources/test-corrupted-config-legacy-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-corrupted-config-new-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-failed-flaky-retries/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-failed-legacy-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-failed-new-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-skip-legacy-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-skip-new-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-gradle-plugin-test/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-4-class-ordering/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-5/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-legacy-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-forks-legacy-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-forks-new-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-module-legacy-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-multi-module-new-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-new-instrumentation/build.gradleTest
  dd-smoke-tests/gradle/src/test/resources/test-succeed-old-gradle/build.gradleTest
Labels: comp: testing, tag: no release notes, comp: ci visibility

#8979 Update Maven smoke tests to use repository proxy
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
  dd-smoke-tests/gradle/src/test/resources/test-succeed-junit-4-class-ordering/build.gradleTest
  dd-smoke-tests/maven/build.gradle
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
  dd-smoke-tests/maven/src/test/resources/test_failed_maven_run_flaky_retries/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_builtin_coverage/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_child_service_propagation/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_impacted_tests/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit4_class_ordering/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit4_class_ordering_parallel/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit_platform_runner/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_multiple_forks/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_surefire_3_0_0/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_surefire_3_5_0/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_test_management/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_arg_line_property/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_cucumber/settings.xml
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_with_jacoco_and_argline/settings.xml
Labels: comp: testing, tag: no release notes, comp: ci visibility

#8983 additional-maven-proxy-fixes
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling, mergequeue-status: removed

#8981 Add DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED alias for runtime id generation
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  internal-api/src/main/java/datadog/trace/api/Config.java
  internal-api/src/test/groovy/datadog/trace/api/ConfigForkedTest.groovy
Labels: type: enhancement, comp: core

#8511 Enable API Security by default
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Labels: type: enhancement, comp: asm waf

#8989 Replace `System.currentTimeMillis` by `nanoTime`
  dd-trace-core/src/main/java/datadog/trace/common/writer/TraceProcessingWorker.java
Labels: type: enhancement, comp: core, tag: no release notes

#8993 Fix Maven smoke test timeout in CI
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Labels: tag: no release notes, comp: ci visibility

#8992 Simplified ListWriter await logic.
  dd-trace-core/src/main/java/datadog/trace/common/writer/ListWriter.java
Labels: type: bug, comp: testing, tag: no release notes

#8997 Increase again Maven smoke tests timeout
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Labels: tag: no release notes

#8994 Earlier `.gradle` creation to fix `populate_dep_cache`
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#8962 Fix benchmark failures and improve results quality
  .gitlab/benchmarks.yml
  benchmark/benchmarks.sh
  benchmark/load/insecure-bank/benchmark.json
  benchmark/load/insecure-bank/k6.js
  benchmark/load/insecure-bank/start-servers.sh
  benchmark/load/petclinic/benchmark.json
  benchmark/load/petclinic/k6.js
  benchmark/load/petclinic/start-servers.sh
  benchmark/load/run.sh
  benchmark/utils/run-k6-load-test.sh
  benchmark/utils/update-java-version.sh
Labels: tag: no release notes

#9000 Enable test retry in CI
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
  gradle/configure_tests.gradle
Labels: tag: no release notes, comp: tooling

#9007 Add system tests check job to add as PR checks
  .github/workflows/README.md
  .github/workflows/check-ci-pipelines.yml
  .github/workflows/run-system-tests.yaml
Labels: type: enhancement, tag: no release notes, comp: tooling

#9011 Add system test job name to help with PR checks
  .github/workflows/run-system-tests.yaml
Labels: tag: no release notes, comp: tooling

#9010 Cleanup of zstd dependency and jps functionality
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/build.gradle
  dd-smoke-tests/profiling-integration-tests/build.gradle
  dd-smoke-tests/profiling-integration-tests/src/test/java/datadog/smoketest/JFRBasedProfilingIntegrationTest.java
  gradle/dependencies.gradle
  internal-api/internal-api-9/src/main/java/datadog/trace/util/JPMSJPSAccess.java
  internal-api/internal-api-9/src/test/groovy/datadog/trace/util/PidHelperTest.groovy
  internal-api/src/main/java/datadog/trace/util/JPSUtils.java
  internal-api/src/main/java/datadog/trace/util/PidHelper.java
Labels: comp: profiling, type: task

#9003 Skip JAXB generated classes classloader
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/matcher/ClassLoaderMatchers.java
Labels: type: enhancement, comp: core

#8991 Store the http.route tag value inside the appsec request context in Play
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
  dd-java-agent/instrumentation/play-2.3/src/main/java/datadog/trace/instrumentation/play23/PlayHttpServerDecorator.java
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play24/PlayHttpServerDecorator.java
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java
  dd-smoke-tests/play-2.4/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.4/build.gradle
  dd-smoke-tests/play-2.4/conf/routes
  dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/AppSecPlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.5/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.5/build.gradle
  dd-smoke-tests/play-2.5/conf/routes
  dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/AppSecPlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.6/build.gradle
  dd-smoke-tests/play-2.6/conf/routes
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
  dd-smoke-tests/play-2.7/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.7/build.gradle
  dd-smoke-tests/play-2.7/conf/routes
  dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
  dd-smoke-tests/play-2.8/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.8/build.gradle
  dd-smoke-tests/play-2.8/conf/routes
  dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
  internal-api/src/main/java/datadog/trace/api/gateway/Events.java
  internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
  internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Labels: type: enhancement, tag: no release notes, comp: asm waf, inst: play framework

#9023 Cancel GitLab running pipeline on new PR push
  .gitlab-ci.yml
Labels: type: enhancement, comp: tooling

#9016 Propagate grizzly http span in filters if nothing is active
  dd-java-agent/instrumentation/grizzly-http-2.3.20/src/main/java/datadog/trace/instrumentation/grizzlyhttp232/DefaultFilterChainInstrumentation.java
Labels: type: bug, inst: mule

#8937 Default obfuscation regexp update
  dd-java-agent/appsec/build.gradle
Labels: type: enhancement, comp: asm waf

#9025 Set trace_injected in try block
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
Labels: type: bug, comp: database

#8940 Enable Code Origin with Dynamic instrumentation
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
Labels: type: enhancement, comp: debugger

#9001 Extract Vert.x json body response schemas
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/AppSecRequestContext.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/ObjectIntrospectionSpecification.groovy
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/gateway/GatewayBridgeSpecification.groovy
  dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextInstrumentation.java
  dd-java-agent/instrumentation/vertx-web-4.0/src/main/java/datadog/trace/instrumentation/vertx_4_0/server/RoutingContextJsonResponseAdvice.java
  dd-java-agent/instrumentation/vertx-web-4.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
  dd-java-agent/instrumentation/vertx-web-4.0/src/test/java/server/VertxTestServer.java
  dd-java-agent/instrumentation/vertx-web-5.0/src/test/groovy/server/VertxHttpServerForkedTest.groovy
  dd-java-agent/instrumentation/vertx-web-5.0/src/test/java/server/VertxTestServer.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
  dd-smoke-tests/vertx-4.2/application/src/main/java/datadog/vertx_4_2/MainVerticle.java
  dd-smoke-tests/vertx-4.2/src/test/groovy/AppSecVertxSmokeTest.groovy
  internal-api/src/main/java/datadog/trace/api/gateway/Events.java
  internal-api/src/main/java/datadog/trace/api/gateway/InstrumentationGateway.java
  internal-api/src/test/java/datadog/trace/api/gateway/InstrumentationGatewayTest.java
Labels: type: enhancement, comp: asm waf, inst: vertx

#8995 Extract Play json body response schemas
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play25/appsec/ResultsStatusInstrumentation.java
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play25/appsec/StatusHeaderInstrumentation.java
  dd-java-agent/instrumentation/play-2.4/src/main/java_play25/datadog/trace/instrumentation/play25/appsec/BodyParserHelpers.java
  dd-java-agent/instrumentation/play-2.4/src/main/java_play25/datadog/trace/instrumentation/play25/appsec/ResultsStatusApplyAdvice.java
  dd-java-agent/instrumentation/play-2.4/src/main/java_play25/datadog/trace/instrumentation/play25/appsec/StatusHeaderSendJsonAdvice.java
  dd-java-agent/instrumentation/play-2.4/src/test/groovy/datadog/trace/instrumentation/play25/server/PlayRouters.groovy
  dd-java-agent/instrumentation/play-2.4/src/test/groovy/datadog/trace/instrumentation/play25/server/PlayServerTest.groovy
  dd-java-agent/instrumentation/play-2.4/src/test/scala/datadog/trace/instrumentation/play25/PlayController.scala
  dd-java-agent/instrumentation/play-2.4/src/test/scala/datadog/trace/instrumentation/play25/PlayRoutersScala.scala
  dd-java-agent/instrumentation/play-2.6/src/baseTest/groovy/datadog/trace/instrumentation/play26/server/PlayRouters.groovy
  dd-java-agent/instrumentation/play-2.6/src/baseTest/groovy/datadog/trace/instrumentation/play26/server/PlayServerTest.groovy
  dd-java-agent/instrumentation/play-2.6/src/latestDepTest/groovy/datadog/trace/instrumentation/play26/server/latestdep/PlayRouters.groovy
  dd-java-agent/instrumentation/play-2.6/src/latestDepTest/scala/datadog/trace/instrumentation/play26/server/latestdep/PlayController.scala
  dd-java-agent/instrumentation/play-2.6/src/latestDepTest/scala/datadog/trace/instrumentation/play26/server/latestdep/PlayRoutersScala.scala
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/BodyParserHelpers.java
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/ResultsStatusInstrumentation.java
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/StatusHeaderInstrumentation.java
  dd-smoke-tests/play-2.5/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.5/conf/routes
  dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/AppSecPlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.6/conf/routes
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
  dd-smoke-tests/play-2.7/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.7/conf/routes
  dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
  dd-smoke-tests/play-2.8/app/controllers/AppSecController.scala
  dd-smoke-tests/play-2.8/conf/routes
  dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/AppSecPlaySmokeTest.groovy
Labels: type: enhancement, comp: asm waf, inst: play framework

#8743 Convert some build file to kotlin dsl
  remote-config/remote-config-api/build.gradle
  remote-config/remote-config-api/build.gradle.kts
  remote-config/remote-config-core/build.gradle
  remote-config/remote-config-core/build.gradle.kts
  telemetry/build.gradle
  telemetry/build.gradle.kts
  utils/container-utils/build.gradle
  utils/container-utils/build.gradle.kts
  utils/socket-utils/build.gradle
  utils/socket-utils/build.gradle.kts
  utils/test-agent-utils/decoder/build.gradle
  utils/test-agent-utils/decoder/build.gradle.kts
  utils/test-utils/build.gradle
  utils/test-utils/build.gradle.kts
  utils/time-utils/build.gradle
  utils/time-utils/build.gradle.kts
  utils/version-utils/build.gradle
  utils/version-utils/build.gradle.kts
Labels: tag: no release notes, comp: tooling

#9013 Extract Ratpack json body response schemas
  dd-java-agent/instrumentation/ratpack-1.5/src/main/java/datadog/trace/instrumentation/ratpack/JsonRendererAdvice.java
  dd-java-agent/instrumentation/ratpack-1.5/src/main/java/datadog/trace/instrumentation/ratpack/JsonRendererInstrumentation.java
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackAsyncHttpServerTest.groovy
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackForkedHttpServerTest.groovy
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/RatpackHttpServerTest.groovy
  dd-java-agent/instrumentation/ratpack-1.5/src/test/groovy/server/SyncRatpackApp.groovy
  dd-smoke-tests/ratpack-1.5/build.gradle
  dd-smoke-tests/ratpack-1.5/src/main/java/datadog/smoketest/ratpack/RatpackApp.java
  dd-smoke-tests/ratpack-1.5/src/test/groovy/AppSecRatpackSmokeTest.groovy
  settings.gradle
Labels: type: enhancement, comp: asm waf, inst: ratpack

#9033 Add repo root as safe directory on git client creation
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java
Labels: type: enhancement, comp: ci visibility

#8938 Extract Spring json body response schemas
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HttpMessageConverterInstrumentation.java
  dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/boot/SpringBootBasedTest.groovy
  dd-smoke-tests/appsec/springboot/src/main/java/datadog/smoketest/appsec/springboot/controller/WebController.java
  dd-smoke-tests/appsec/springboot/src/test/groovy/datadog/smoketest/appsec/AppSecHttpMessageConverterSmokeTest.groovy
Labels: type: enhancement, inst: spring, comp: asm waf

#9038 Improve benchmark readme
  benchmark/README.MD
Labels: comp: testing, type: documentation, tag: no release notes

#9040 Increase MavenSmokeTest timeout
  dd-smoke-tests/maven/build.gradle
Labels: type: bug, tag: no release notes, comp: tooling

#9022 Upgrade libddwaf-java to 15.0.0
  dd-java-agent/appsec/build.gradle
Labels: type: enhancement, comp: asm waf

#9037 Fixing bug with dropping baggage when `TracePropagationBehaviorExtract=IGNORE`
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/baggage/BaggagePropagator.java
Labels: type: bug, comp: context propagation

#9049 🍒 9019 - Fix NPE in akka-http and pekko-http integrations
  dd-java-agent/instrumentation/akka-http/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/DatadogServerRequestResponseFlowWrapper.java
  dd-java-agent/instrumentation/pekko-http-1.0/src/main/java/datadog/trace/instrumentation/pekkohttp/DatadogServerRequestResponseFlowWrapper.java
Labels: type: bug, inst: akka

#9056 🍒 9026 - Update one pipeline reference
  .gitlab/one-pipeline.locked.yml
Labels: type: enhancement, tag: no release notes, comp: tooling

#9014 Extract Jersey json body response schemas
  dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie
  dd-java-agent/instrumentation/jakarta-rs-annotations-3/src/main/java/datadog/trace/instrumentation/jakarta3/MessageBodyWriterInstrumentation.java
  dd-java-agent/instrumentation/jax-rs-annotations-2/build.gradle
  dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/MessageBodyWriterInstrumentation.java
  dd-java-agent/instrumentation/jersey/build.gradle
  dd-java-agent/instrumentation/jersey/src/jersey2JettyTest/groovy/datadog/trace/instrumentation/jersey2/ClassToConvertBodyTo.groovy
  dd-java-agent/instrumentation/jersey/src/jersey2JettyTest/groovy/datadog/trace/instrumentation/jersey2/Jersey2JettyTest.groovy
  dd-java-agent/instrumentation/jersey/src/jersey2JettyTest/groovy/datadog/trace/instrumentation/jersey2/ServiceResource.groovy
  dd-java-agent/instrumentation/jersey/src/jersey3JettyTest/groovy/datadog/trace/instrumentation/jersey3/ClassToConvertBodyTo.groovy
  dd-java-agent/instrumentation/jersey/src/jersey3JettyTest/groovy/datadog/trace/instrumentation/jersey3/Jersey3JettyTest.groovy
  dd-java-agent/instrumentation/jersey/src/jersey3JettyTest/groovy/datadog/trace/instrumentation/jersey3/ServiceResource.groovy
  dd-smoke-tests/jersey-2/build.gradle
  dd-smoke-tests/jersey-2/src/main/java/com/restserver/RequestBody.java
  dd-smoke-tests/jersey-2/src/main/java/com/restserver/Resource.java
  dd-smoke-tests/jersey-2/src/test/groovy/datadog/smoketest/Jersey2AppsecSmokeTest.groovy
  dd-smoke-tests/jersey-3/build.gradle
  dd-smoke-tests/jersey-3/src/main/java/smoketest/MainApp.java
  dd-smoke-tests/jersey-3/src/main/java/smoketest/RequestBody.java
  dd-smoke-tests/jersey-3/src/main/java/smoketest/Resource.java
  dd-smoke-tests/jersey-3/src/test/groovy/datadog/smoketest/Jersey3AppsecSmokeTest.groovy
  dd-smoke-tests/jersey-3/src/test/groovy/datadog/smoketest/Jersey3SmokeTest.groovy
Labels: type: enhancement, inst: jax-ws, comp: asm waf

#9052 🍒 9037 - Fixing bug with dropping baggage when `TracePropagationBehaviorExtract=IGNORE`
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
  dd-trace-core/src/main/java/datadog/trace/core/baggage/BaggagePropagator.java
Labels: type: bug, comp: context propagation

#9050 🍒 9032 - Fixing NPE in PercentEscaper
  dd-trace-core/src/main/java/datadog/trace/core/util/PercentEscaper.java
Labels: type: bug, comp: api

#9043 Update ddapm-test-agent from v1.11.0 to v1.24.1
  .gitlab-ci.yml
  dd-trace-core/src/test/groovy/datadog/trace/TracerConnectionReliabilityTest.groovy
Labels: type: enhancement, comp: core, tag: no release notes
