Repository DataDog/dd-trace-java, pull requests merged in 2025-07, with the labels that each got.

#9074 Graceful error handling in .gitlab/find-gh-base-ref.sh
  .gitlab-ci.yml
  .gitlab/find-gh-base-ref.sh
Labels: tag: no release notes, comp: tooling

#9078 Disable skipping tests based on git changes
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#9063 Refactor wildcard imports in config
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: comp: core, tag: no release notes, type: refactoring

#9085 Fix wildcard import
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: comp: core, tag: no release notes, type: refactoring

#9071 Introduce environment component
  components/environment/build.gradle.kts
  components/environment/src/main/java/datadog/environment/CommandLine.java
  components/environment/src/main/java/datadog/environment/EnvironmentVariables.java
  components/environment/src/main/java/datadog/environment/JavaVersion.java
  components/environment/src/main/java/datadog/environment/JavaVirtualMachine.java
  components/environment/src/main/java/datadog/environment/JvmOptions.java
  components/environment/src/main/java/datadog/environment/OperatingSystem.java
  components/environment/src/main/java/datadog/environment/SystemProperties.java
  components/environment/src/test/java/datadog/environment/CommandLineHelper.java
  components/environment/src/test/java/datadog/environment/CommandLineTest.java
  components/environment/src/test/java/datadog/environment/EnvironmentVariablesTest.java
  components/environment/src/test/java/datadog/environment/JavaVersionTest.java
  components/environment/src/test/java/datadog/environment/JavaVirtualMachineTest.java
  components/environment/src/test/java/datadog/environment/JvmOptionsTest.java
  components/environment/src/test/java/datadog/environment/OperatingSystemTest.java
  components/environment/src/test/java/datadog/environment/SystemPropertiesTest.java
  components/environment/src/test/resources/argfiles/.gitattributes
  components/environment/src/test/resources/argfiles/carriage-return-separated-expected.txt
  components/environment/src/test/resources/argfiles/carriage-return-separated.txt
  components/environment/src/test/resources/argfiles/new-line-separated-expected.txt
  components/environment/src/test/resources/argfiles/new-line-separated.txt
  components/environment/src/test/resources/argfiles/space-separated-expected.txt
  components/environment/src/test/resources/argfiles/space-separated.txt
  components/environment/src/test/resources/argfiles/tab-separated-expected.txt
  components/environment/src/test/resources/argfiles/tab-separated.txt
  gradle/dependencies.gradle
  settings.gradle
Labels: type: enhancement, comp: platform

#9015 Extract RestEasy json body response schemas
  dd-smoke-tests/resteasy/build.gradle
  dd-smoke-tests/resteasy/src/main/java/smoketest/resteasy/App.java
  dd-smoke-tests/resteasy/src/main/java/smoketest/resteasy/RequestBody.java
  dd-smoke-tests/resteasy/src/main/java/smoketest/resteasy/Resource.java
  dd-smoke-tests/resteasy/src/test/groovy/smoketest/ResteasyAppsecSmokeTest.groovy
Labels: type: enhancement, comp: asm waf

#9082 Ensure client stat reporter is started when the agent is not available at bootstrap
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/ConflatingMetricAggregatorTest.groovy
Labels: type: bug, comp: metrics

#9028 Limit the maximum size of the location path in IAST vulnerabilities
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/XssModuleImpl.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/XssModuleTest.groovy
  dd-smoke-tests/springboot-thymeleaf/src/main/java/datadog/smoketest/springboot/XssController.java
  dd-smoke-tests/springboot-thymeleaf/src/test/groovy/datadog/smoketest/springboot/IastSpringBootThymeleafSmokeTest.groovy
Labels: type: bug, comp: asm iast

#8885 Optimize IAST Vulnerability Detection
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/Reporter.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadContext.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/HttpResponseHeaderModuleImpl.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sink/SinkModuleBase.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastModuleImplTestBase.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastRequestContextTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadContextTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/overhead/OverheadControllerTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HstsMissingHeaderModuleTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/HttpResponseHeaderModuleTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/sink/WeakRandomnessModuleTest.groovy
  dd-java-agent/agent-iast/src/testFixtures/groovy/com/datadog/iast/test/NoopOverheadController.groovy
  dd-smoke-tests/iast-util/src/main/java/datadog/smoketest/springboot/controller/IastSamplingController.java
  dd-smoke-tests/springboot/src/test/groovy/datadog/smoketest/IastOverheadControlSpringBootSmokeTest.groovy
Labels: type: enhancement, comp: asm iast

#9072 Migrate AgentBootStrap to environment component
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Constants.java
  dd-java-agent/build.gradle
  dd-java-agent/src/main/java/datadog/trace/bootstrap/AgentBootstrap.java
  dd-java-agent/src/main/java/datadog/trace/bootstrap/SystemUtils.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/SpockRunner.java
  gradle/dependencies.gradle
Labels: comp: core, tag: no release notes, type: refactoring

#9083 Fix verify error when ctor params are used after a call site
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/Advices.java
  dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/bytebuddy/csi/CallSiteTransformer.java
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/BaseCallSiteTest.groovy
  dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/tooling/csi/CallSiteInstrumentationTest.groovy
  dd-java-agent/agent-tooling/src/test/java/datadog/trace/agent/tooling/csi/SuperInCtorExample.java
  dd-java-agent/instrumentation/java-io/src/test/groovy/datadog/trace/instrumentation/java/io/InputStreamReaderCallSiteTest.groovy
  dd-java-agent/instrumentation/java-io/src/test/java/foo/bar/TestCustomInputStreamReader.java
Labels: type: bug, comp: asm iast, mergequeue-status: in_progress

#9005 Mute tracing for subprocesses executed by bootstrap telemetry logic.
  dd-java-agent/build.gradle
  dd-java-agent/src/main/java/datadog/trace/bootstrap/BootstrapInitializationTelemetry.java
  dd-java-agent/src/test/groovy/datadog/trace/agent/AgentLoadedIntoBootstrapTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/CustomLogManagerTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/CustomMBeanServerBuilderTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/InitializationTelemetryTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/InstrumenterUnloadTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/JMXFetchTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/ListIntegrationsTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/LogLevelTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/agent/integration/classloading/ClassLoadingTest.groovy
  dd-java-agent/src/test/java/datadog/test/SimpleAgentMock.java
  dd-java-agent/src/test/java/datadog/trace/agent/test/IntegrationTestUtils.java
  dd-java-agent/src/test/java/jvmbootstraptest/InitializationTelemetryCheck.java
  dd-java-agent/src/test/java/jvmbootstraptest/LogManagerSetter.java
  dd-java-agent/src/test/java/jvmbootstraptest/SecurityManagerCheck.java
  dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java
Labels: type: enhancement, comp: core, tag: no release notes

#9077 Partition muzzle tasks with the same method as build and tests
  .gitlab-ci.yml
  build.gradle
  gradle/ci_jobs.gradle
Labels: tag: no release notes, comp: tooling

#9088 CircleCI migration leftovers
  .gitignore
  .gitlab-ci.yml
  .gitlab/cgroup-info.sh
  .gitlab/collect_muzzle_deps.sh
  .gitlab/collect_profiles.sh
  .gitlab/collect_reports.sh
  .gitlab/collect_results.sh
  .gitlab/upload_ciapp.sh
  docs/how_to_test.md
  docs/how_to_test/rerun-workflow-from-failed.png
  docs/how_to_test/retry-failed-job.png
  docs/how_to_test/run-again-job.png
  gradle/ci_jobs.gradle
  gradle/configure_tests.gradle
  gradle/spotless.gradle
Labels: tag: no release notes, comp: tooling

#9114 Fix Test Optimization to work with JDK 24
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/AbstractGradleTest.groovy
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit_platform_runner/events.ftl
  dd-smoke-tests/maven/src/test/resources/test_successful_maven_run_junit_platform_runner/pom.xml
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Labels: comp: ci visibility, type: task

#9086 Don't run check-big-regressions on master or release branches
  .gitlab/benchmarks.yml
Labels: tag: performance, tag: no release notes, comp: tooling

#9106 chore(build): Skip empty parent instrumentation projects
  build.gradle
  dd-java-agent/instrumentation/akka-http/build.gradle
  dd-java-agent/instrumentation/akka-http/gradle.lockfile
  dd-java-agent/instrumentation/apache-httpclient/build.gradle
  dd-java-agent/instrumentation/apache-httpcore/build.gradle
  dd-java-agent/instrumentation/armeria/build.gradle
  dd-java-agent/instrumentation/build.gradle
  dd-java-agent/instrumentation/couchbase/build.gradle
  dd-java-agent/instrumentation/couchbase/gradle.lockfile
  dd-java-agent/instrumentation/freemarker/build.gradle
  dd-java-agent/instrumentation/freemarker/gradle.lockfile
  dd-java-agent/instrumentation/graphql-java/build.gradle
  dd-java-agent/instrumentation/graphql-java/gradle.lockfile
  dd-java-agent/instrumentation/redisson/build.gradle
  dd-java-agent/instrumentation/redisson/gradle.lockfile
  dd-java-agent/instrumentation/servicetalk/build.gradle
  dd-java-agent/instrumentation/servicetalk/gradle.lockfile
  dd-java-agent/instrumentation/websocket/build.gradle
  dd-java-agent/instrumentation/websocket/gradle.lockfile
  dd-java-agent/instrumentation/websocket/jetty-websocket/build.gradle
  dd-java-agent/instrumentation/websocket/jetty-websocket/gradle.lockfile
  dd-java-agent/instrumentation/zio/build.gradle
  dd-java-agent/instrumentation/zio/gradle.lockfile
  gradle/ci_jobs.gradle
  settings.gradle
Labels: tag: no release notes, comp: tooling

#9116 Drop useless Gradle wrapper config
  build.gradle
Labels: tag: no release notes, comp: tooling

#9129 Don't be strict on opensearch tests
  dd-java-agent/instrumentation/opensearch/rest/src/test/groovy/OpensearchRestClientTest.groovy
  dd-java-agent/instrumentation/opensearch/transport/src/test/groovy/OpensearchNodeClientTest.groovy
  dd-java-agent/instrumentation/opensearch/transport/src/test/groovy/OpensearchTransportClientTest.groovy
Labels: comp: testing, tag: no release notes, tag: flaky test

#9047 Update file probe format
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationAcceptor.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/ConfigurationFileLoader.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/DebuggerAgent.java
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/util/MoshiHelper.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/ConfigurationFileLoaderTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/DebuggerAgentTest.java
  dd-java-agent/agent-debugger/src/test/resources/test_probe_file.json
Labels: type: enhancement, comp: debugger

#9125 Use token to access Akka secure repository
  .gitlab-ci.yml
  dd-java-agent/instrumentation/akka-http/akka-http-10.6/build.gradle
Labels: tag: no release notes, comp: tooling

#9124 Allow tag builds to access Gitlab cache
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
Labels: tag: no release notes, comp: tooling

#9133 Fix environment unit tests related to IBM / J9
  components/environment/src/test/java/datadog/environment/CommandLineTest.java
  components/environment/src/test/java/datadog/environment/JavaVirtualMachineTest.java
Labels: type: bug, tag: no release notes, comp: platform

#9134 Use parallel artifact resolution in Maven Smoke tests
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Labels: tag: no release notes, comp: ci visibility

#9136 Make client stats reliable in case of downgrade
  dd-trace-core/src/main/java/datadog/trace/common/metrics/ConflatingMetricsAggregator.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsReliabilityTest.groovy
Labels: type: bug, comp: metrics

#9135 Avoid race conditions and multiple agent discovery feature states
  communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
Labels: type: bug, comp: core

#9143 Give more time to structured concurrency tests
  dd-java-agent/instrumentation/java-concurrent/java-concurrent-21/src/previewTest/groovy/StructuredConcurrencyTest.groovy
Labels: type: bug, comp: testing, tag: no release notes, tag: flaky test

#9105 Store the http.route tag value inside the iast request context in Play
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/HttpRouteHandler.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastRequestContext.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/IastSystem.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/overhead/OverheadController.java
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/HttpRouteHandlerTest.groovy
  dd-java-agent/agent-iast/src/test/groovy/com/datadog/iast/IastSystemTest.groovy
  dd-java-agent/instrumentation/play-2.3/src/main/java/datadog/trace/instrumentation/play23/PlayHttpServerDecorator.java
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play24/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.4/src/main/java/datadog/trace/instrumentation/play24/PlayHttpServerDecorator.java
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/PlayAdvice.java
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/PlayHttpServerDecorator.java
  dd-smoke-tests/iast-util/src/testFixtures/groovy/datadog/smoketest/AbstractIastServerSmokeTest.groovy
  dd-smoke-tests/play-2.4/app/controllers/IastController.scala
  dd-smoke-tests/play-2.4/build.gradle
  dd-smoke-tests/play-2.4/conf/routes
  dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/IastPlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.5/app/controllers/IastController.scala
  dd-smoke-tests/play-2.5/build.gradle
  dd-smoke-tests/play-2.5/conf/routes
  dd-smoke-tests/play-2.5/src/test/groovy/datadog/smoketest/IastPlayNettySmokeTest.groovy
  dd-smoke-tests/play-2.6/app/controllers/IastController.scala
  dd-smoke-tests/play-2.6/build.gradle
  dd-smoke-tests/play-2.6/conf/routes
  dd-smoke-tests/play-2.6/src/test/groovy/datadog/smoketest/IastPlaySmokeTest.groovy
  dd-smoke-tests/play-2.7/app/controllers/IastController.scala
  dd-smoke-tests/play-2.7/build.gradle
  dd-smoke-tests/play-2.7/conf/routes
  dd-smoke-tests/play-2.7/src/test/groovy/datadog/smoketest/IastPlaySmokeTest.groovy
  dd-smoke-tests/play-2.8/app/controllers/IastController.scala
  dd-smoke-tests/play-2.8/build.gradle
  dd-smoke-tests/play-2.8/conf/routes
  dd-smoke-tests/play-2.8/src/test/groovy/datadog/smoketest/IastPlaySmokeTest.groovy
Labels: type: enhancement, tag: no release notes, comp: asm iast, inst: play framework

#9137 DSM optimizations for high throughput scenarios
  dd-trace-core/src/main/java/datadog/trace/core/datastreams/DefaultPathwayContext.java
Labels: type: enhancement, comp: data streams

#9148 Specify junit version for llmobs agent
  dd-java-agent/agent-llmobs/build.gradle
Labels: type: enhancement, tag: no release notes, comp: tooling, comp: mlobs

#9144 Backpropagate peer tags
  communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java
  communication/src/test/groovy/datadog/communication/ddagent/DDAgentFeaturesDiscoveryTest.groovy
  communication/src/test/resources/agent-features/agent-info-with-peer-tag-back-propagation.json
Labels: type: enhancement, comp: metrics

#9096 Update builder image for JDK 25 EA
  .gitlab-ci.yml
  gradle/java_no_deps.gradle
Labels: type: enhancement, tag: no release notes, comp: tooling

#9147 Ignore jboss and quarkus smoke tests for JDK 24+
  dd-smoke-tests/jboss-modules/src/test/groovy/datadog/smoketest/JBossModulesV1SmokeTest.groovy
  dd-smoke-tests/jboss-modules/src/test/groovy/datadog/smoketest/JBossModulesV2SmokeTest.groovy
  dd-smoke-tests/quarkus/build.gradle
  dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusJBossLoggingSmokeTest.groovy
  dd-smoke-tests/quarkus/src/test/groovy/datadog/smoketest/QuarkusSlf4jSmokeTest.groovy
Labels: type: enhancement, comp: testing, tag: no release notes

#9158 Fix flaky out of order comparison for http client test
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Labels: type: enhancement, comp: testing, tag: no release notes, tag: flaky test

#9160 Fix AppSec play.mvc.StatusHeader instrumentation for play 2.6
  dd-java-agent/instrumentation/play-2.6/src/main/java/datadog/trace/instrumentation/play26/appsec/StatusHeaderInstrumentation.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Labels: type: bug, comp: asm waf, inst: play framework

#9152 Update ignoreif reason for karate tests on jdk 24
  dd-java-agent/instrumentation/karate/src/test/groovy/KarateTest.groovy
Labels: type: enhancement, comp: testing, tag: no release notes

#9163 Fix flaky out-of-order comparison for http client test.
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpClientTest.groovy
Labels: type: enhancement, comp: testing, tag: no release notes, tag: flaky test

#9153 Enable Fastzip for Gitlab cache
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#9048 Add SSI Appsec System tests
  .gitlab-ci.yml
Labels: comp: testing, tag: no release notes

#9166 Mark Play 2.4 IastPlayNettySmokeTest as flaky
  dd-smoke-tests/play-2.4/src/test/groovy/datadog/smoketest/IastPlayNettySmokeTest.groovy
Labels: tag: no release notes, tag: flaky test, comp: asm waf, tag: flaky test/disabled

#9164 Refactored build scripts to use Spock version from catalog.
  buildSrc/build.gradle.kts
  buildSrc/call-site-instrumentation-plugin/build.gradle.kts
  buildSrc/settings.gradle.kts
  dd-java-agent/instrumentation/spring-webflux-6/build.gradle
  gradle/libs.versions.toml
Labels: type: enhancement, tag: no release notes

#9168 Unify truncation limits between ObjectIntrospection and WAFModule
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/ddwaf/WAFModule.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/event/data/ObjectIntrospection.java
  dd-java-agent/appsec/src/test/groovy/com/datadog/appsec/event/data/ObjectIntrospectionSpecification.groovy
Labels: type: enhancement, tag: no release notes, comp: asm waf

#9175 🍒 9135 - Avoid race conditions and multiple agent discovery feature states
  communication/src/main/java/datadog/communication/ddagent/SharedCommunicationObjects.java
Labels: type: bug, comp: core

#9180 Upgrade Jacoco to 0.8.13. Cleanup Gradle script.
  gradle/jacoco.gradle
Labels: type: enhancement, tag: no release notes, comp: tooling

#9196 Change primary client stats configuration key
  dd-trace-api/src/main/java/datadog/trace/api/config/GeneralConfig.java
  dd-trace-core/src/test/groovy/datadog/trace/common/metrics/MetricsReliabilityTest.groovy
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: type: enhancement, comp: metrics

#9142 Fix dependency resolution retries in MavenSmokeTest
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Labels: tag: no release notes, comp: ci visibility

#9194 Flaky test for REMOTE CONFIG telemetry configuration annotated
  dd-smoke-tests/dynamic-config/src/test/groovy/datadog/smoketest/AppSecActivationSmokeTest.groovy
Labels: tag: no release notes, tag: flaky test, comp: remote config, tag: flaky test/disabled

#9185 feat: add injection metadata fields to telemetry forwarder
  dd-java-agent/src/main/java/datadog/trace/bootstrap/BootstrapInitializationTelemetry.java
  dd-java-agent/src/main/java6/datadog/trace/bootstrap/AgentPreCheck.java
  dd-java-agent/src/test/groovy/datadog/trace/bootstrap/AgentPreCheckTest.groovy
  dd-java-agent/src/test/groovy/datadog/trace/bootstrap/BootstrapInitializationTelemetryTest.groovy
Labels: type: enhancement, comp: core

#9188 Improve environment component null values handling
  components/environment/src/main/java/datadog/environment/EnvironmentVariables.java
  components/environment/src/main/java/datadog/environment/SystemProperties.java
  components/environment/src/test/java/datadog/environment/EnvironmentVariablesTest.java
  components/environment/src/test/java/datadog/environment/SystemPropertiesTest.java
Labels: type: enhancement, tag: no release notes, comp: platform

#9170 Surface potential root cause when agent initialization errors
  dd-java-agent/src/main/java/datadog/trace/bootstrap/BootstrapInitializationTelemetry.java
  dd-java-agent/src/test/groovy/datadog/trace/bootstrap/BootstrapInitializationTelemetryTest.groovy
Labels: type: enhancement, comp: core

#9202 Attempt to fix OOM for `Update Gradle dependencies` action.
  .github/workflows/update-gradle-dependencies.yaml
Labels: tag: no release notes, comp: tooling

#9207 Attempt to fix OOM for GitHub actions.
  .github/workflows/analyze-changes.yaml
Labels: tag: no release notes, comp: tooling

#9208 Granular test exclusions for SecurityManager behavior under Java 24+.
  dd-java-agent/src/test/groovy/datadog/trace/agent/InitializationTelemetryTest.groovy
Labels: comp: core, tag: no release notes

#9198 Add dd-octo-sts trust policy
  .github/chainguard/self.gitlab.release.sts.yaml
Labels: type: enhancement, comp: tooling

#9068 Perf release gate
  .gitlab/benchmarks/bp-runner.fail-on-breach.yml
  .gitlab/macrobenchmarks.yml
Labels: tag: no release notes, comp: tooling

#9201 Match Hands Off Config selectors on process_arguments value
  internal-api/src/main/java/datadog/trace/bootstrap/config/provider/StableConfigParser.java
  internal-api/src/test/groovy/datadog/trace/bootstrap/config/provider/StableConfigParserTest.groovy
Labels: type: bug, comp: core

#9205 Add third-party filtering in SourceFile tracking
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/agent/SourceFileTrackingTransformer.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/agent/SourceFileTrackingTransformerTest.java
  dd-smoke-tests/debugger-integration-tests/src/test/java/datadog/smoketest/InProductEnablementIntegrationTest.java
Labels: type: enhancement, comp: debugger

#9218 Fixed flaky test
  dd-java-agent/instrumentation/kafka-clients-0.11/src/latestDepTest/groovy/KafkaClientTestBase.groovy
  dd-java-agent/instrumentation/kafka-connect-0.11/src/test/groovy/ConnectWorkerInstrumentationTest.groovy
Labels: type: bug, comp: testing, tag: no release notes, comp: data streams

#9095 Migrate libddwaf to maven central
  dd-java-agent/appsec/build.gradle
  gradle/repositories.gradle
Labels: tag: no release notes, tag: dependencies, comp: asm waf

#9215 Refactor the SmapEntry event generation
  dd-java-agent/agent-bootstrap/src/main/java11/datadog/trace/bootstrap/instrumentation/jfr/JfrHelper.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/OpenJdkController.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/AggregatedSmapEntryEvent.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/SmapEntryCache.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/SmapEntryEvent.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/SmapEntryFactory.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/events/SmapEntryCacheTest.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/events/SmapEntryFactoryTest.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/resources/smap/annotated_regions_23.txt
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/resources/smap/annotated_regions_24.txt
Labels: tag: no release notes, type: refactoring, comp: profiling

#9225 Replaced abandoned lib `com.github.kstyrc` with actively maintained `com.github.codemonstur` lib.
  dd-java-agent/instrumentation/jedis-3.0/build.gradle
  dd-java-agent/instrumentation/jedis-3.0/src/test/groovy/Jedis30ClientTest.groovy
  dd-java-agent/instrumentation/jedis-4.0/build.gradle
  dd-java-agent/instrumentation/jedis-4.0/src/test/groovy/Jedis40ClientTest.groovy
  dd-java-agent/instrumentation/lettuce-4/build.gradle
  dd-java-agent/instrumentation/lettuce-4/src/test/groovy/Lettuce4ClientTestBase.groovy
  dd-java-agent/instrumentation/rediscala-1.8.0/build.gradle
  dd-java-agent/instrumentation/rediscala-1.8.0/src/test/groovy/RediscalaClientTest.groovy
Labels: comp: testing, tag: no release notes

#9229 Update .gitlab/one-pipeline.locked.yml
  .gitlab/one-pipeline.locked.yml
Labels: tag: no release notes, comp: tooling

#9231 Avoid initializing SMAP events on JDKs with no JFR
  dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/Agent.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/SmapEntryFactory.java
Labels: type: bug, tag: no release notes, comp: profiling, run-tests: semeru11, run-tests: semeru17

#9210 Improve Git commit info building
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/CiVisibilityRepoServices.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CITagsProvider.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/GithubActionsInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/PullRequestInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/config/ExecutionSettingsFactoryImpl.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/GitClientGitInfoBuilder.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitClient.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataUploaderImpl.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitRepoUnshallow.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/NoOpGitClient.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/ShellGitClient.java
  dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/CiVisibilityRepoServicesTest.groovy
  dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/ci/GithubActionsInfoTest.groovy
  dd-java-agent/agent-ci-visibility/src/test/groovy/datadog/trace/civisibility/git/tree/GitClientTest.groovy
  internal-api/src/main/java/datadog/trace/api/civisibility/telemetry/tag/Command.java
Labels: type: enhancement, comp: ci visibility

#9234 Fix the annotation region format parsing on JDK 24/25
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/main/java/com/datadog/profiling/controller/openjdk/events/SmapEntryCache.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/java/com/datadog/profiling/controller/openjdk/events/SmapEntryFactoryTest.java
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/resources/smap/annotated_regions_23.txt
  dd-java-agent/agent-profiling/profiling-controller-openjdk/src/test/resources/smap/annotated_regions_24.txt
Labels: type: bug, tag: no release notes, comp: profiling

#9237 Add workflow retry to fix Resource not accessible by integration error
  .github/workflows/add-milestone-to-pull-requests.yaml
Labels: type: bug, tag: no release notes, comp: tooling

#9243 Skip check-slo-breaches during POPULATE_CACHE pipelines
  .gitlab/macrobenchmarks.yml
Labels: tag: no release notes, comp: tooling

#9233 Fix debugger test for stable JVM
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/symbol/SymbolExtractionTransformerTest.java
  dd-java-agent/agent-debugger/src/test/java/com/datadog/debugger/util/ClassFileLinesTest.java
Labels: comp: testing, tag: no release notes, type: refactoring, comp: debugger

#9236 Unlimit latestdep for spark 3.x
  dd-java-agent/instrumentation/spark-executor/build.gradle
  dd-java-agent/instrumentation/spark/spark_2.13/build.gradle
Labels: type: enhancement, tag: no release notes, inst: apache spark

#9224 Fix duplicate trace injection for SQL Server and Oracle DBM full propagation mode
  dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/StatementInstrumentation.java
  dd-java-agent/instrumentation/jdbc/src/test/groovy/SQLCommenterTest.groovy
  dd-java-agent/instrumentation/jdbc/src/test/groovy/SQLServerInjectionForkedTest.groovy
Labels: type: bug, inst: jdbc, comp: database

#9227 Clean dd-octo-sts workflow and add pre-release check
  .gitlab-ci.yml
Labels: type: enhancement, tag: no release notes, comp: tooling

#9248 Fix CI_SPLIT for base case test matrix
  .gitlab-ci.yml
Labels: tag: no release notes, comp: tooling

#9247 Fix notify-slo-breaches interaction with POPULATE_CACHE
  .gitlab/macrobenchmarks.yml
Labels: tag: no release notes, comp: tooling

#9250 Minor code cleanup.
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/git/tree/GitDataApi.java
  dd-java-agent/agent-iast/src/main/java/com/datadog/iast/sensitive/HeaderRegexpTokenizer.java
  dd-java-agent/appsec/src/main/java/com/datadog/appsec/gateway/GatewayBridge.java
  dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
  dd-trace-core/src/main/java/datadog/trace/core/TracingConfigPoller.java
  dd-trace-core/src/main/java/datadog/trace/core/propagation/B3HttpCodec.java
  internal-api/src/main/java/datadog/trace/api/Config.java
Labels: type: enhancement, tag: no release notes

#9235 Add new org to Weaver instrumentation
  dd-java-agent/instrumentation/weaver/build.gradle
  dd-java-agent/instrumentation/weaver/gradle.lockfile
  dd-java-agent/instrumentation/weaver/src/main/java/datadog/trace/instrumentation/weaver/DatadogWeaverReporter.java
  dd-java-agent/instrumentation/weaver/src/main/java/datadog/trace/instrumentation/weaver/TaskDefAwareConcurrentLinkedQueueProxy.java
  dd-java-agent/instrumentation/weaver/src/main/java/datadog/trace/instrumentation/weaver/TaskDefAwareLinkedBlockingQueueProxy.java
  dd-java-agent/instrumentation/weaver/src/main/java/datadog/trace/instrumentation/weaver/TaskDefAwareQueueProxy.java
  dd-java-agent/instrumentation/weaver/src/main/java/datadog/trace/instrumentation/weaver/WeaverInstrumentation.java
Labels: type: enhancement, tag: community, comp: ci visibility

#9253 Add script to clean up old Gradle modules
  tooling/cleanup-gradle-module.sh
Labels: type: enhancement, tag: no release notes, comp: tooling

#9261 Use mirrored agent image in CI
  .gitlab-ci.yml
  dd-trace-core/src/traceAgentTest/groovy/AbstractTraceAgentTest.groovy
Labels: tag: no release notes, comp: tooling

#9256 Add `ci.job.id` tag
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/AwsCodePipelineInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/AzurePipelinesInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/BuildkiteInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CIInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CITagsProvider.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/CircleCIInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/GitLabInfo.java
  dd-java-agent/agent-ci-visibility/src/main/java/datadog/trace/civisibility/ci/GithubActionsInfo.java
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/awscodepipeline.json
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/azurepipelines.json
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/buildkite.json
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/circleci.json
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/github.json
  dd-java-agent/agent-ci-visibility/src/test/resources/ci/gitlab.json
  internal-api/src/main/java/datadog/trace/bootstrap/instrumentation/api/Tags.java
Labels: type: enhancement, comp: ci visibility

#9140 Add JDK 25-EA testing to CI
  .gitlab-ci.yml
  dd-java-agent/instrumentation/java-concurrent/java-concurrent-21/build.gradle
  dd-java-agent/instrumentation/java-lang/src/test/groovy/datadog/trace/instrumentation/java/lang/RuntimeCallSiteTest.groovy
  dd-java-agent/instrumentation/log4j1/src/test/groovy/MdcTest.groovy
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/AbstractGradleTest.groovy
  dd-smoke-tests/gradle/src/test/groovy/datadog/smoketest/GradleDaemonSmokeTest.groovy
  dd-smoke-tests/log-injection/build.gradle
  dd-smoke-tests/maven/src/test/groovy/datadog/smoketest/MavenSmokeTest.groovy
Labels: type: enhancement, comp: testing

#9262 Bump ddprof to 1.29.0
  dd-java-agent/ddprof-lib/build.gradle
  gradle/libs.versions.toml
Labels: type: enhancement, comp: profiling

#9216 Convert settings and main build to kotlin
  build.gradle
  build.gradle.kts
  settings.gradle
  settings.gradle.kts
Labels: tag: no release notes, comp: tooling

#9246 Add check to prevent injection of repeated GRPC headers
  dd-java-agent/instrumentation/armeria/armeria-grpc-0.84/src/main/java/datadog/trace/instrumentation/armeria/grpc/client/GrpcInjectAdapter.java
  dd-java-agent/instrumentation/armeria/armeria-grpc-0.84/src/test/groovy/GrpcInjectAdapterTest.groovy
  dd-java-agent/instrumentation/grpc-1.5/src/main/java/datadog/trace/instrumentation/grpc/client/GrpcInjectAdapter.java
  dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcInjectAdapterTest.groovy
Labels: type: bug, inst: grpc

#9279 Disable debugger metrics by default
  dd-java-agent/agent-debugger/src/main/java/com/datadog/debugger/sink/DebuggerSink.java
  dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java
Labels: type: bug, tag: no release notes, comp: debugger
